### ISSUE TITLE
 No labels found

### ISSUE THREAD

**Issue by Basim592003** [ultralytics/ultralytics#11268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i am trying to detect cells but it keeps throwing this error -> WARNING ⚠️ No labels found in D:\data\labels\train.cache.
i have images and labels folder set up like specified from yolo documentations bur still have an issue.

### Additional

--python code--
from ultralytics import YOLO
model = YOLO("yolov8s.yaml") 
results = model.train(data=r"D:\UNIVERSITY\SEM6\Mia\config.yaml", epochs=1)  

--yaml file--
path: D:/UNIVERSITY/SEM6/Mia/data
train: images/train  
val: images/train  

# Classes
names:
  0: probes

**Comment by glenn-jocher** [comment]
Hello! It looks like the issue may be related to where the model is looking for your label files. Based on the error message you're receiving, it's possible that the labels are not correctly matched or located where the model expects.

First, ensure that your labels in `D:\UNIVERSITY\SEM6\Mia\data\labels\train` match the images in `D:\UNIVERSITY\SEM6\Mia\data\images\train` in terms of naming and format. Each label file should have the same basename as its corresponding image file.

Also, in your training YAML file, you should specify the location of both the images and labels directories explicitly. Here's a suggested correction for your YAML configuration:

```yaml
path: D:/UNIVERSITY/SEM6/Mia/data
train: images/train  
val: images/val  # Make sure to validate on different data if possible

# Directories
train_label_dir: labels/train
val_label_dir: labels/val

# Classes
names:
  - probes
```
Make sure the `train_label_dir` and `val_label_dir` are correctly pointing to where your labels are stored.

Try these adjustments and see if it resolves the issue. 👍

**Comment by TheMattBin** [comment]
hi @Basim592003 
```python
from ultralytics import YOLO
model = YOLO("yolov8s.yaml")
results = model.train(data=r"D:\UNIVERSITY\SEM6\Mia\config.yaml", epochs=1)
```
I guess would be line 2, you might not add proper format for model

**Comment by Basim592003** [comment]
i tried adding label directories as you said but it still gives the same error. 
Also why is a cache being created ad=nd why does it look for labels in thee created cache?
train: New cache created: D:\UNIVERSITY\SEM6\Mia\Training\Images\Train.cache
WARNING ⚠️ No labels found in D:\UNIVERSITY\SEM6\Mia\Training\Images\Train.cache

**Comment by glenn-jocher** [comment]
@Basim592003 hello!

For the issue where you're encountering missing labels even after specifying the directories, it sounds like there might be a disconnect in how the paths are referenced in your configuration. Here’s a quick checklist:

1. Ensure the `labels` folder structure mirrors that of your `images`. Each label file name should exactly match its corresponding image file name, except the extension.
2. Make sure the label files are in the correct format – typically, a `.txt` file for YOLO.

Regarding the cache, YOLO creates a `.cache` file to speed up subsequent trainings by saving the loaded datasets. It's checking the cache for labels, implying possibly the cache didn't store paths correctly the first time or the labels are indeed missing/incorrectly named.

If the issue persists, try clearing the cache by deleting the `.cache` file, and rerun your training. Make sure your paths in the YAML are correct and double-check any typographical errors.

Hope this helps!

**Comment by Basim592003** [comment]
@glenn-jocher Hey!
Both my labels and images files content have the same exact names. And yes, i have also tried deleting the .cache file and running but i get the same results.

Maybe its because the images i am using are tiff images ?

**Comment by glenn-jocher** [comment]
Hello @Basim592003!

It's great that you've ensured the labels and images have matching names. Regarding the use of TIFF images, YOLOv8 typically expects images in formats like JPEG or PNG. TIFF might not be directly supported, which could lead to issues with label detection.

You could try converting your TIFF images to a supported format using a script. Here’s a quick example using Python with PIL:

```python
from PIL import Image
import os

image_dir = 'path/to/tiff/images'
output_dir = 'path/to/output/images'

for filename in os.listdir(image_dir):
    if filename.endswith('.tiff'):
        image_path = os.path.join(image_dir, filename)
        output_path = os.path.join(output_dir, filename.replace('.tiff', '.jpg'))
        image = Image.open(image_path)
        image.save(output_path, 'JPEG')
```

This script converts all TIFF images in a directory to JPEG. Try running your model again with these converted images. Let us know how it goes! 😊

**Comment by FOOXINLOONG** [comment]
Hello, I would like to ask after I haved solved the "labels not found" issues, the next issue I am facing is the run/detect/train files that should be automatically create does no have. How should I solve it ya.

**Comment by glenn-jocher** [comment]
Hello!

It sounds like you're expecting certain directories (`run/detect/train`) to be automatically created during the process, which aren't appearing. Typically, these directories should be generated when you start a training session or detection task.

Here are a few steps to troubleshoot:
1. **Permissions**: Ensure you have the necessary write permissions in the directory where you're running your tasks.
2. **Path Specifications**: Double-check your command or script to ensure paths are correctly specified and there are no typographical errors.
3. **Manual Creation**: As a workaround, you can manually create these directories in your specified path before running your task.

If these steps don't resolve the issue, please provide more details about the commands you are using and any output or error messages you're seeing. This will help in diagnosing the problem more effectively.

Looking forward to your update! 😊

**Comment by FOOXINLOONG** [comment]
> Hello!
> 
> It sounds like you're expecting certain directories (`run/detect/train`) to be automatically created during the process, which aren't appearing. Typically, these directories should be generated when you start a training session or detection task.
> 
> Here are a few steps to troubleshoot:
> 
> 1. **Permissions**: Ensure you have the necessary write permissions in the directory where you're running your tasks.
> 2. **Path Specifications**: Double-check your command or script to ensure paths are correctly specified and there are no typographical errors.
> 3. **Manual Creation**: As a workaround, you can manually create these directories in your specified path before running your task.
> 
> If these steps don't resolve the issue, please provide more details about the commands you are using and any output or error messages you're seeing. This will help in diagnosing the problem more effectively.
> 
> Looking forward to your update! 😊

Hello, thanks for giving me the answer, I have already solve this issue gladfully. But the next issues I have faced is when I tried to run the new number of epochs in my training, it comes out a new error which is saying as
![Untitled](https://github.com/ultralytics/ultralytics/assets/74204556/a13d2a4e-ab78-455c-a0c5-ed4ad7157764)

**Comment by glenn-jocher** [comment]
@FOOXINLOONG hello!

I'm glad to hear that you resolved the directory creation issue! Regarding the new error you encountered during training with a different number of epochs, it seems the image didn't come through properly. Could you please re-upload the screenshot of the error or describe the error message in text? This will help me understand the issue better and provide you with a more accurate solution.

Looking forward to your response!

**Comment by iambikash378** [comment]
> Hello, I would like to ask after I haved solved the "labels not found" issues, the next issue I am facing is the run/detect/train files that should be automatically create does no have. How should I solve it ya.

Hi, I am encountering the same issue.  My YAML file structure (for the paths) is : 
path: '/content/drive/MyDrive/dataset'
train: '/content/drive/MyDrive/dataset/train/images'
val: '/content/drive/MyDrive/dataset/valid/images'
test: '/content/drive/MyDrive/dataset/test/images'

train_label_dir: '/content/drive/MyDrive/dataset/train/labels'
val_label_dir: '/content/drive/MyDrive/dataset/val/labels'
test_label_dir: '/content/drive/MyDrive/dataset/test/labels'

The images are in .tiff format. The labels are in .txt and the names are the same for labels and images.
 I am getting the issue:
AssertionError: train: No labels found in /content/drive/MyDrive/dataset/train/labels.cache, can not start training.

(But I am doing for the YOLOv9 model). Since the problem looks similar here, I decided to ask it here.

 @Basim592003 How did you solve this problem? Changing it to .jpg format or something else? Mine is a satellite imagery so i don't know if changing the format will affect the performance or not so i am using the .tiff to be on the safe side. @glenn-jocher

**Comment by glenn-jocher** [comment]
@iambikash378 if you're encountering the "No labels found" issue despite having matching image and label file names, the problem could indeed stem from the `.tiff` format. YOLO models generally expect images in common formats like `.jpg` or `.png`. Converting your `.tiff` images to `.jpg` or `.png` should resolve this issue. The format change will not affect the performance as long as the resolution and image quality are preserved during conversion. You can use tools like PIL in Python for conversion. If you'd prefer to keep the `.tiff` format, ensure your dataset paths and configurations are properly set, and consider preprocessing your dataset to confirm compatibility. For further reference on dataset formatting, check the documentation [here](https://docs.ultralytics.com/datasets/detect/).

**Comment by Basim592003** [comment]
@iambikash378 Hello!
To be honest its been very long since i worked on yolo so i don't remember everything i had done to resolve this, but for starters try to convert your `.tiff ` images to `.jpg` or `.png`. And furthermore, if you are trying to detect very small objects split the images into tiles. 
Hope this helps.

**Comment by iambikash378** [comment]
> @iambikash378 if you're encountering the "No labels found" issue despite having matching image and label file names, the problem could indeed stem from the `.tiff` format. YOLO models generally expect images in common formats like `.jpg` or `.png`. Converting your `.tiff` images to `.jpg` or `.png` should resolve this issue. The format change will not affect the performance as long as the resolution and image quality are preserved during conversion. You can use tools like PIL in Python for conversion. If you'd prefer to keep the `.tiff` format, ensure your dataset paths and configurations are properly set, and consider preprocessing your dataset to confirm compatibility. For further reference on dataset formatting, check the documentation [here](https://docs.ultralytics.com/datasets/detect/).

Hi @glenn-jocher , thank you for the response. I changed the image to .jpg taking help from the script you wrote in one of the replies here. I also checked the documentation and I thought my directory wasn't configured properly. So I followed the configuration suggested by the documentation. But the same error still persisted. Also, I figured that the image dimensions weren't normalized, which I corrected. But the same error still persisted. 

Could it be because all of my images weren't the same size or a standard size? If so, to what size should I convert them? One is of size 130*115 px , the other 85*86 px, the other 222*223 px and so on. 

Here's the overall context :

I am actually converting a landslide dataset which had segmentation masks and converting it to bounding boxes in for object detection. I converted it to YOLO format and then after the error I converted the .tiff to .jpg.

Here's the dataset structure : ![image](https://github.com/user-attachments/assets/6f7327b1-8ef7-4cae-bee0-49d5d2af3293)
Here's the sample .txt label : ![image](https://github.com/user-attachments/assets/c6a2c9e9-1d22-4a55-a11f-f1a76bf8f807)
The YAML file : ![image](https://github.com/user-attachments/assets/a73e8479-d201-4083-bab2-2dd40a07e730)
The error :  ![image](https://github.com/user-attachments/assets/9c4906a4-0b15-469d-9680-677d7e9d2c90)


This is the dataset I am using https://zenodo.org/records/3675410#.ZBv3UZBxD8 and the paper I am trying to implement https://www.mdpi.com/2072-4292/16/14/2598

**Comment by glenn-jocher** [comment]
Thank you for the detailed explanation and context. The error is unlikely to be caused by varying image sizes, as YOLO models can handle different image dimensions due to on-the-fly resizing during training. However, ensure your labels are correctly normalized for each image's respective dimensions. 

From your dataset structure and description, here are a few things to verify:  
1. Confirm that the `.txt` labels are in YOLO format (`class x_center y_center width height`) with normalized values (between 0 and 1).  
2. Ensure every image has a corresponding label file, and if an image contains no objects, there should be no `.txt` file for it.  
3. Double-check that your YAML file is correctly set up with paths relative to the dataset root directory, as shown in the [documentation](https://docs.ultralytics.com/datasets/detect/).  

If the issue persists after these checks, it may help to validate your dataset using the `ultralytics` package's dataset tools. Let us know how it goes!

**Comment by iambikash378** [comment]
@glenn-jocher  Thanks a lot. I figured out that I had overlooked the labels name which had similar format to the images names. But they were a bit different. That worked after i made them the same :)

**Comment by iambikash378** [comment]
@glenn-jocher  Hi, I trained the model and ran inference on it. Is there a way I can alter the thickness of the bounding box and even remove the text label ( as I only have one class to work with) ? The results don't look clear with the bounding box and the text label in their natural size.

The images after running inference look like these:

![Image](https://github.com/user-attachments/assets/e7c5e368-ac57-46d1-af69-75270cb295b7)

![Image](https://github.com/user-attachments/assets/541f3a5a-9ab2-4e75-9d14-c67c92148d4b)

**Comment by glenn-jocher** [comment]
You can customize the bounding box thickness and remove the text label by modifying the `model.predict()` parameters. Use the `line_thickness` argument to adjust the box thickness and set `show_labels=False` to remove the text label. Here's an example:

```python
model.predict(source='your_image.jpg', line_thickness=2, show_labels=False)
```

For more details, refer to the [Predict Documentation](https://docs.ultralytics.com/modes/predict/).

**Comment by yacqubstack** [comment]
<img width="160" alt="Image" src="https://github.com/user-attachments/assets/3f94ae76-2533-4777-9555-d6e913cf2d8a" /> 

this is my coco dataset structure and im trying to train it but whenever i put this in the terminal: 
yolo segment train \
  data=coco.yaml \
  model=yolov8n-seg.pt \
  epochs=20 \
  batch=4

i get this error? 
train: Scanning /content/drive/Documents/app
train: WARNING ⚠️ No labels found in /content/drive/Documents/app/coco/labels/train.cache. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
train: WARNING ⚠️ Cache directory /content/drive/Documents/app/coco/labels is not writeable, cache not saved.
WARNING ⚠️ No labels found in /content/drive/Documents/app/coco/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
val: Scanning /content/drive/Documents/app/c
val: WARNING ⚠️ No labels found in /content/drive/Documents/app/coco/labels/val.cache. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
val: WARNING ⚠️ Cache directory /content/drive/Documents/app/coco/labels is not writeable, cache not saved.
WARNING ⚠️ No labels found in /content/drive/Documents/app/coco/labels/val.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance.

this is my coco.yaml file: path: /content/drive/Documents/app/coco
train: images/train
val: images/val
nc: 46

I've done Python checks and it confirms:

Every file_name in your COCO "images" array matches an actual image file,
Every annotation has a valid image_id and category_id,
Every annotation has either bbox or segmentation.

but it still doesnt work?

**Comment by glenn-jocher** [comment]
@yacqubstack it seems the issue lies in the dataset structure or paths to the labels. Ensure your dataset follows the YOLO format, where the `labels/train` and `labels/val` directories contain `.txt` files with annotations corresponding to each image in `images/train` and `images/val`. Additionally, verify that the `path` in your `coco.yaml` file is correct and writable. For detailed guidance, refer to the dataset formatting documentation: https://docs.ultralytics.com/datasets. Let me know if you need further clarification!

**Comment by yacqubstack** [comment]
Hi @glenn-jocher,

Thank you for your input and for pointing me in the right direction!

I wanted to clarify that I’m working on an image segmentation task using the Fashionpedia dataset: https://github.com/cvdfoundation/fashionpedia rather than object detection. Fashionpedia provides detailed segmentation masks, which is why my dataset is structured with masks instead of labels. Here’s a brief overview of my current setup:
Dataset Structure:

<img width="167" alt="Image" src="https://github.com/user-attachments/assets/26d25ddf-42eb-4db4-9dcc-c4eee5a4f839" />



Training Command:
yolo segment train data=data.yaml model=yolov8n-seg.pt epochs=100 imgsz=640 

data.yaml Configuration:
path: /content/drive/Documents/app/coco

train: images/train
val: images/val

masks:
  train: masks/train
  val: masks/val

nc: 46

names:
  0: Dress
  1: Top
  2: Skirt
  3: Pants
  4: Shorts
  5: Jacket
  6: Coat
  7: Sweater
  8: Blouse
  9: Shirt
  10: Jeans
  11: Hoodie
  12: T-shirt
  13: Tank Top
  14: Leggings
  15: Polo Shirt
  16: Cardigan
  17: Blazer
  18: Sportswear
  19: Jumpsuit
  20: Romper
  21: Socks
  22: Shoes
  23: Sneakers
  24: Boots
  25: Sandals
  26: Heels
  27: Flats
  28: Belt
  29: Hat
  30: Scarf
  31: Gloves
  32: Necklace
  33: Earrings
  34: Bracelet
  35: Watch
  36: Sunglasses
  37: Tie
  38: Bow-tie
  39: Vest
  40: Underwear
  41: Swimsuit
  42: Raincoat
  43: Purse
  44: Backpack
  45: Wallet

Given that segmentation requires mask files instead of label .txt files, I’ve set up my data.yaml accordingly and am using the segment mode with the appropriate model (yolov8n-seg.pt).

Current Issue: Despite these configurations, YOLOv8 is still attempting to access a labels directory, which doesn't exist in my dataset structure. I’ve also ensured that all mask files are in .png format and correctly named to match their corresponding images.

Steps I’ve Taken So Far:

Verified data.yaml: Ensured there are no references to labels.
Cleared Cache Files: Removed any residual cache files that might reference labels.
Checked Mask Integrity: Confirmed that all masks are properly formatted and correspond to their images.

Request: Could you please provide guidance or suggest any additional steps I might take to ensure YOLOv8 recognizes the segmentation setup and stops searching for the labels directory?

Thank you for your assistance!

Best regards, @yacqubstack

**Comment by glenn-jocher** [comment]
Hi @yacqubstack, thank you for the detailed explanation. YOLOv8 currently expects segmentation datasets in the Ultralytics YOLO format, where segmentation masks are encoded as polygon coordinates in `.txt` files rather than separate mask files like `.png`. To use the Fashionpedia dataset, you need to convert your masks into YOLO-style `.txt` files with the format `<class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>`. You can find more details about the required format and conversion steps in the segmentation dataset documentation: https://docs.ultralytics.com/datasets/segment/. Let us know if you need further clarification!

**Comment by GreaterthanGreat** [comment]
> Hello, I would like to ask after I haved solved the "labels not found" issues, the next issue I am facing is the run/detect/train files that should be automatically create does no have. How should I solve it ya.


Hello. How did you solve this the "labels not found" issues as I am experiencing the same exact problem

**Comment by glenn-jocher** [comment]
To resolve the "labels not found" issue, ensure your dataset follows the YOLO format, where each image has a corresponding `.txt` file with annotations in the same directory structure. Verify that the `data.yaml` file paths are correct and point to the appropriate directories. If you're using segmentation masks, convert them to YOLO segmentation format using the `convert_segment_masks_to_yolo_seg()` function as described [here](https://docs.ultralytics.com/reference/data/converter/).

**Comment by Gitmohammede** [comment]
@glenn-jocher i had the same problem with the no labels found error although everything is correct, i switched from the small to nano version and the training was executed perfectly, is it really related the small version of YOLOv8s?????

Looking forward for your answer

**Comment by pranavv11** [comment]
@glenn-jocher Hello! I am training a YOLOv8n model for object detection. i am also getting: WARNING ⚠️ train: No labels found in /kaggle/working/Dental_data/Dental X_Ray/train.cache. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
I have ensured that each image.jpg has a corresponding label.txt.
this is my directory structure: 
![Image](https://github.com/user-attachments/assets/a0d9aee9-ddab-460b-a439-9d565df41c1d)

This is my data.yml contents: 
data_yaml = """
path: /kaggle/working/Dental_data
train: /kaggle/working/Dental_data/Dental X_Ray/train
val: /kaggle/working/Dental_data/Dental X_Ray/val
test: /kaggle/working/Dental_data/Dental X_Ray/test

train_labels: /kaggle/working/Dental_data/labels/train
val_label: /kaggle/working/Dental_data/labels/val
test_label: /kaggle/working/Dental_data/labels/test

names:
  0: "Caries"
  1: "Crown"
  2: "Filling"
  3: "Implant"
  4: "Malaligned"
  5: "Mandibular Canal"
  6: "Missing teeth"
  7: "Periapical lesion"
  8: "Retained root"
  9: "Root Canal Treatment"
  10: "Root Piece"
  11: "croen"
  12: "impacted tooth"
  13: "maxillary sinus"
"""

I get the warning for all train, test and val images and it still runs the first epoch. but after the first epoch, it stops and i get an error: 
ValueError: need at least one array to concatenate

The dataset is also formatted accordin to the [ultralytics docs](https://docs.ultralytics.com/datasets/detect/#how-do-i-start-training-a-yolo11-model-using-my-dataset) as well.

**Comment by glenn-jocher** [comment]
@pranavv11 the issue is with your dataset structure and YAML configuration. YOLO expects a specific directory layout where labels are in corresponding `labels` directories parallel to `images` directories. Your YAML should use relative paths and shouldn't include custom label path parameters. Try this structure:

```
Dental_data/
├── images/
│   ├── train/
│   ├── val/
│   └── test/
└── labels/
    ├── train/
    ├── val/
    └── test/
```

And update your YAML to:
```yaml
path: /kaggle/working/Dental_data
train: images/train
val: images/val
test: images/test
names:
  0: "Caries"
  # ... rest of your classes
```

Remove the `train_labels`, `val_label`, `test_label` parameters as they're not standard YOLO format.

**Comment by intern-ctrl** [comment]
Hi i'm facing the same error like every other person so i'm working on linux machine, i use anaconda ,ultralytics for labeling i;m using label-studio and export the file and unxip make it as images folder inside we have two sub folders called train and val and corresponding that i created a next folder called labels and same as images i created a two train_labels and val_labels and i created a yaml file also in the same folder but it is showing the labels are missing but i check images names and label names are exact can you share your idea to solve

**Comment by glenn-jocher** [comment]
Hi @intern-ctrl — Label Studio usually exports COCO JSON, not YOLO `.txt`; convert the export to YOLO labels, place them under `labels/train` and `labels/val`, clear caches, then retry training.

```python
# Convert COCO/Label Studio annotations to YOLO TXT
from ultralytics.data.converter import convert_coco

convert_coco(labels_dir="/path/to/label-studio/coco/annotations")
# If your COCO JSON contains polygons (segmentation), add:
convert_coco(labels_dir="/path/to/label-studio/coco/annotations", use_segments=True)
```

```bash
# Remove stale caches after fixing labels
find /path/to/dataset/labels -name "*.cache" -delete
```

If it still warns about labels, run diagnostics and share the text output plus a 5–10 image sample in a new issue for visibility (this thread is closed/stale):
```bash
yolo checks
```
Quick guidance on common pitfalls is in the [Troubleshooting Common YOLO Issues](https://docs.ultralytics.com/guides/yolo-common-issues/).

**Comment by intern-ctrl** [comment]
@glenn-jocher
Thank you for your response!

For my setup, I created separate projects for training and testing, in the label-studio and export as "YOLOv8 OBB with Images"  format with images downloaded. and then saved them as train and validation sets respectively. I used the following command to train the model:

yolo train detect model=yolov8n.pt data=path/to/data.yaml imgsz=192


I made sure that the dataset paths were clearly defined. After training, I successfully converted the model into a Vela Lite file and deployed it on the Seeed Grove Vision AI Module.

**Comment by glenn-jocher** [comment]
Great to hear you’ve got it training and deployed! If your Label Studio export is “YOLOv8 OBB,” train with the OBB task (`yolo obb train ...`) and ensure labels follow the YOLO OBB polygon format; see the [OBB task guide](https://docs.ultralytics.com/tasks/obb/) and the `convert_dota_to_yolo_obb()` tool in the [converter reference](https://docs.ultralytics.com/reference/data/converter/). For follow-ups on deployment/OBB specifics, please open a new issue so the team can track it, as this thread was about “No labels found.”
