### ISSUE TITLE
default.yaml missing from from yolo/configs folder

### ISSUE THREAD

**Issue by YuccaBrev** [ultralytics/ultralytics#1158]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\joshn.DESKTOP-B2Q3TN2\\.conda\\envs\\antCV_test\\Lib\\site-packages\\ultralytics\\yolo\\configs\\default.yaml'

### Environment

-YOLO ultralytics 8.0.45

### Minimal Reproducible Example

yolo task=init

### Additional

This error message I was originally seeing when trying to run predictions. I did a lot of searching and cannot find anything out there with the same issues. I did find something sort of close that lead me to running the yolo task-init command   but that also produced the FileNotFoundError message. going directly to the folder I can see that is is missing, but I cannot seem to find out how to get that file. Any help would be very much appreciated.  

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@YuccaBrev that's strange. The file is here, you can download it again if you need it. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml

**Comment by glenn-jocher** [comment]
@YuccaBrev oh, it looks like you have an out-of-date version of the code that is looking for default.yaml in a 'configs' directory. This is deprecated. You should `pip install -U ultralytics` to update to the latest version of the package.

**Comment by YuccaBrev** [comment]
YES!!  that fixed it. (updating the pip package that is).  Thank you!

**Comment by duy1851999** [comment]
> YES!! that fixed it. (updating the pip package that is). Thank you!

What utralytics version you update, the ultralytics version change update continueously.

**Comment by santhoshkumar07** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\santh\\AppData\\Local\\Temp\\_MEI99802\\ultralytics\\yolo\\cfg\\default.yaml'

**Comment by santhoshkumar07** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\santh\\AppData\\Local\\Temp\\_MEI99802\\ultralytics\\yolo\\cfg\\default.yaml'

need help this issue.

**Comment by aavci22** [comment]
> FileNotFoundError: [Errno 2] Böyle bir dosya veya dizin yok: 'C:\Users\santh\AppData\Local\Temp\_MEI99802\ultralytics\yolo\cfg\default.yaml'
> 
> bu konuda yardıma ihtiyacım var.


Aynı sorun bendede var.  exe oluşturup farklı konumda ve farklı bilgisayarda uygulama açılırken bu hatayı veriyor. 
Projenin mevcut konumunda uygulama çalışıyor. Hata vermiyor. 
cfg dosyasınıda uygulama ile aynı klasöre koydum . farklı deneme olarak  exe oluşturuken cfg dosyasınıda import ettim ama düzelmiyor.
Bu sorunu nasıl aşabiliriz?

**Comment by glenn-jocher** [comment]
@aavci22 hi there, 

It seems like you're encountering a FileNotFoundError while attempting to access the 'default.yaml' file. 

The directory path you're using 'C:\Users\santh\AppData\Local\Temp\_MEI99802\ultralytics\yolo\cfg\' is either incorrect or it does not contain the 'default.yaml' file. 

Make sure that the file is present in the correct directory and that the directory path you're using in your code matches the location of the file in your system. 

Also, from your description, it seems you've moved your application's location which might have caused problems with relative paths. Please ensure all your files maintain their relative paths from each other if moved.

As a side note, always ensure that your Ultralytics package is up to date. Execute `pip install -U ultralytics` in your terminal to update to the latest version of the package, this might help resolve some unexpected issues.

If you continue to face this problem, a good step would be to provide more context about your setup and the steps leading to the error, to allow for more specific guidance.

Remember to always run your applications in environments where all dependencies are properly installed and paths correctly set.

**Comment by panek0033312232** [comment]
I compiled my code, and after I launch it I get this error 
### No such file or directory: "C:\Users\Kuba
AppData\Local\Temp\_MEI109522\ultralytics\cfg\defalut.yaml"

**Comment by aavci22** [comment]
I overcame this problem by following the steps below.  I removed all installed IDEs and VENVs.  I created the project folder.  I opened the folder by typing CMD in the address bar.  I created the VENV folder with pip.  Adds other pip requirements while VENV is active.  I did the exe compilation with --onedir.  I downloaded the cfg file and moved it to this folder.  this way the problem is solved.

**Comment by glenn-jocher** [comment]
Hi @panek0033312232,

Thank you for sharing this information. Your findings will indeed be beneficial to other users who might encounter an issue similar to what you had.

Your approach of clearing all installed Development Environments (IDEs) and other Virtual Environments (VENVs), then setting up a new project, is a good one. This fresh start ensures that any conflicting or outdated packages are not causing issues.

Creating the Virtual Environment (VENV) via pip and installing the necessary packages in an active VENV is a solid advice. That way, you isolate the dependencies needed for the Ultralytics environment away from your global Python environment.

Building the executable with "--onedir" is a good point too. It tells PyInstaller to create a one-folder bundle with the executable. This approach diversifies the contained files during runtime, which can help avoid potential conflicts and improve reliability.

Downloading the missing file manually and moving it to the correct folder is a workable though unconventional approach. YOLOv8 should typically be able to locate these files automatically, but the odd structures or paths in certain environments might sometimes prevent it. Nonetheless, it's great to hear that it solved your issue.

Always remember to make sure you're working with the most updated version of Ultralytics by running `pip install -U ultralytics` in your terminal. This way, you ensure to have the most recent and consistent file structure.

Thank you again for sharing your workaround method. It might help someone facing the same challenge.

**Comment by vladyskai** [comment]
> I overcame this problem by following the steps below. I removed all installed IDEs and VENVs. I created the project folder. I opened the folder by typing CMD in the address bar. I created the VENV folder with pip. Adds other pip requirements while VENV is active. I did the exe compilation with --onedir. I downloaded the cfg file and moved it to this folder. this way the problem is solved.

So it is impossible to do it with --onefile ?? I have the same problem when creating the .exe. In my testing it didn't matter the IDEs nor the VENVs installed, the same error appeared again.

Furthermore, when doing it with --onedir, the "ultralytics" folder does not appear. I have to manually create the "ultralytics" folder, then the "cfg" folder and then paste then paste the "defalut.yaml" inside it. 

I believe there is some incompatibility between the pyinstaller and the ultralytics libraries.

**Comment by glenn-jocher** [comment]
@vladyskai hi there,

Thank you for sharing this issue you're experiencing. It does seem that you're doing everything right, but are still encountering errors.

To clarify, the `--onefile` and `--onedir` options during compilation refer to the way PyInstaller bundles the application. With `--onefile`, there's a single executable file and with `--onedir`, the executable and all dependencies are in a single directory.

While it's usually more convenient to use `--onefile` for distribution purposes, the `--onedir` option can be more reliable in some situations.

If you're unable to see the "ultralytics" folder after building with `--onedir`, it suggests that PyInstaller is either not bundling these files correctly, or they're being placed in a different location.

With regards to the issue you're having with PyTorch and PyInstaller, that warning message is indicating that PyInstaller is unable to retrieve the source for a specific PyTorch function. This is a common issue when using PyInstaller with complex libraries like PyTorch. 

The issue with PyTorch often requires more advanced solutions that involve modifying the spec file that PyInstaller uses to bundle the application, or even modifying the settings of PyTorch itself.

Given these complexities, the error you're running into is not straightforward to solve without adjusting more significant aspects of your environment or the packages in question. 

I hope this helps clarify what could be causing the issues you're encountering. Keep in mind, the world of bundling python into an executable can be tricky, but with some maneuvering and persistence, it's certainly manageable.

**Comment by santhoshkumar07** [comment]
after exc generate this error.

FileNotFoundError: [Errno 2] Böyle bir dosya veya dizin yok: 'C:\Users\santh\AppData\Local\Temp_MEI99802\ultralytics\yolo\cfg\default.yaml'

**Comment by aavci22** [comment]
> exc'ten sonra bu hatayı üretin.
> 
> FileNotFoundError: [Errno 2] Böyle bir dosya veya dizin yok: 'C:\Users\santh\AppData\Local\Temp_MEI99802\ultralytics\yolo\cfg\default.yaml'

Make an exe with --onedir.  Download cfg manual and move it to the folder with exe.  Do you get the same error like this?

**Comment by glenn-jocher** [comment]
@aavci22 yes, this error message is indicating that the system cannot find the 'default.yaml' file in the directory 'C:\Users\santh\AppData\Local\Temp_MEI99802\ultralytics\yolo\cfg\'. This could be because the file does not exist, or the path to the file is incorrect.

When you create an executable using the `--onedir` option with PyInstaller, it should create a directory that contains your executable along with all the dependencies it needs to run, including the 'default.yaml' file.

However, it seems like in this case, the 'default.yaml' file is not being included in that directory. Downloading the 'default.yaml' file manually and moving it into the same directory as your executable could help to resolve this issue.

But if you are still getting the same error after doing this, it could be that the path to the 'default.yaml' file is hardcoded somewhere in your code or in the Ultralytics YOLOv8 package itself, and it does not match the actual location of the 'default.yaml' file in your system.

You might need to modify your code or the YOLOv8 package to correct this path. Just ensure that wherever the 'default.yaml' file is being loaded from in the code, it corresponds to the actual location of the 'default.yaml' file in your system.

**Comment by VinuraJayakody** [comment]
"FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vinur\\AppData\\Local\\Temp\\_MEI5962\\ultralytics\\cfg\\default.yaml' " 
I got the same error. Please help me with this. I tried updating the ultralytics as well from pip install -U ultralytics command.

**Comment by glenn-jocher** [comment]
@VinuraJayakody hello,

The error message you're encountering suggests the system is having trouble accessing the 'default.yaml' file at the path provided. 

In general, issues with FileNotFoundError could stem from:
1. The file 'default.yaml' does not exist in the mentioned location.
2. The path to the 'default.yaml' file is incorrect in the code.
3. The relative path, if any, has been disrupted due to movement of files or directories.

Given that you've already attempted to update the Ultralytics package, here are a few more steps you might want to consider:

Firstly, verify that the 'default.yaml' file actually exists in the path stated in the error message. If it doesn't, you might need to download the necessary file and place it in the right directory.

Secondly, if the 'default.yaml' file is indeed in the correct location as stated by the code but the system is not able to identify it, this suggests an error in the way your code is addressing its location. In such a case, you would need to revise your code and correct the path being used.

Lastly, ensure all related files maintain their proximity if moved or copied. Altering the relative positioning of interdependent files could disrupt the pathing system.

Remember to always run your application in an environment where all dependencies are properly installed and paths are correctly set.

I hope this helps guide you towards a resolution of the issue. Should the problem persist, more context about your setup and the steps leading to the error would allow for more specific advice.

**Comment by VinuraJayakody** [comment]
@glenn-jocher could you please tell me how can I download the 'default.yaml' file

**Comment by glenn-jocher** [comment]
@VinuraJayakody hello, 

The 'default.yaml' file is typically included within the Ultralytics YOLOv8 package. When you clone or download the YOLOv8 repository, it should include a "cfg" directory that contains the 'default.yaml' file.

If the file is missing from this location for some reason, one option can be to manually create a 'default.yaml' file based on the configurations detailed within the YOLOv8 documentation.

Please bear in mind that when creating an executable, the bundling process should include the 'default.yaml' file and it must be in the correct specified location to ensure the software runs properly.

I hope this information helps. If issues persist, I recommend double-checking your environment, the installation of the YOLOv8 package, and your understanding of the YOLOv8 usage instructions. It might also be a good idea to revisit the configuration settings within the 'default.yaml' file for any misconfigurations that could lead to the FileNotFoundError.

Remember, the community is here to support you. Don't hesitate to reach out if you need further assistance.

**Comment by ZeeshanKhalid2k01** [comment]
I encountered a similar issue to what @YuccaBrev described. In my case, I faced the error while utilizing **--onefile** with **pyinstaller**.

### To tackle this problem:

1. Use the **--onedir** command alongside pyinstaller.
2. After generating the .exe, check if it's working properly. If the error persists, indicating the absence of 'data.yaml':
3. Verify if the 'ultralytics' folder is created by pyinstaller; if not, proceed to the next step.
4. Manually create the 'ultralytics\cfg' directory under the same directory as the generated .exe.
5. Add the 'data.yaml' file within the 'ultralytics\cfg' directory.

This adjustment enabled the .exe file to run successfully without encountering the missing 'data.yaml' error.

Hope this workaround helps!

**Comment by fridary** [comment]
Solution: `pyinstaller --onedir --collect-all ultralytics file.py`

**Comment by glenn-jocher** [comment]
@fridary the solution you've provided using `pyinstaller --onedir --collect-all ultralytics file.py` is a good approach. This command tells PyInstaller to bundle the application in one directory and to collect all files from the `ultralytics` package, which should include the necessary configuration files like `default.yaml`. This can help ensure that all the required files are packaged with your executable. If you still encounter issues, make sure that the `ultralytics` package is properly installed in your environment and that the `default.yaml` file is located in the correct directory within the package.

**Comment by thinhemb** [comment]
@fridary  you can --add-data "C:/Users/KNT21818/AppData/Roaming/Python/Python39/site-packages/ultralytics;ultralytics/" I tried it and it worked.

**Comment by JDOS** [comment]
Thanks @glenn-jocher  it's works!!

**Comment by glenn-jocher** [comment]
@JDOS glad to hear it's working for you! If you encounter any more issues or have further questions, feel free to reach out. Always happy to help!

**Comment by ZeeshanKhalid2k01** [comment]
@JDOS, I'm glad my suggestion helped you out. Thanks for the appreciation!

**Comment by zoldaten** [comment]
just hardcoded file path, as i built with one file (auto-py-to-exe):

```
venv\Lib\site-packages\ultralytics\utils\__init.py__
line 477:
#with open(file, errors="ignore", encoding="utf-8") as f:
with open('default.yaml', errors="ignore", encoding="utf-8") as f:

and put  default.yaml (from venv\Lib\site-packages\ultralytics\cfg) to dir after build exe.
```
