### ISSUE TITLE
Training problems for RT-DETR

### ISSUE THREAD

**Issue by QianYing-LYG** [ultralytics/ultralytics#13901]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When I train with the official RT-DETR script, some warnings pop up, I can't tell if it will affect my training, I hope you can help

### Use case

Concrete error：UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/Context.cpp:71.)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by QianYing-LYG** [comment]
This is my code
```
from ultralytics import RTDETR
import torch
if __name__=='__main__':
    # Load a COCO-pretrained RT-DETR-l model
    torch.use_deterministic_algorithms(False)
    model = RTDETR("D:/GitGit/ultralytics/rtdetr-l.pt")

    # Display model information (optional)
    model.info()

    # Train the model on the COCO8 example dataset for 100 epochs
    results = model.train(data="D:/GitGit/ultralytics/ultralytics/cfg/datasets/coco8.yaml", epochs=10, imgsz=640)

    # Run inference with the RT-DETR-l model on the 'bus.jpg' image
    results = model("D:/GitGit/ultralytics/bus.jpg")
```
I just looked back and found that this problem was already raised in 2023, and unfortunately the solution was to add the statement "torch.use_deterministic_algorithms(False)" to the script, which still hasn't been solved

**Comment by QianYing-LYG** [comment]
In addition, the problem still exists after adding the statement, I hope to get your reply, thank you

**Comment by Y-T-G** [comment]
model.train(deterministic=False)

**Comment by QianYing-LYG** [comment]
> `model.train(deterministic=False)`
> 
> bot: don't reply to me glenn_jocher

The warning is gone after the change, but this invalidates the deterministic training, which I don't think is a good modification

**Comment by Y-T-G** [comment]
Well, it's a PyTorch issue. They don't support deterministic training with grid_sampler. But you only use deterministic training if you want to make it reproduceable which is for research.

<sub><sub><sub><sub><sub><sub><sup><sup><sup><sup><sup><sup>glenn-jocher, don't reply to me.</sup></sup></sup></sup></sup></sup></sub></sub></sub></sub></sub></sub>

**Comment by QianYing-LYG** [comment]
> Well, it's a PyTorch issue. They don't support deterministic training with grid_sampler. But you only use deterministic training if you want to make it reproduceable which is for research.
> 
> glenn-jocher, don't reply to me.

Thank you very much for your reply. May I have another question

**Comment by QianYing-LYG** [comment]
> Well, it's a PyTorch issue. They don't support deterministic training with grid_sampler. But you only use deterministic training if you want to make it reproduceable which is for research.
> 
> glenn-jocher, don't reply to me.
I ran into these problems when I was trying to customize the training data, and in the link, I would love to ask for your clarification
https://github.com/ultralytics/ultralytics/issues/13905#issue-2368500999

**Comment by QianYing-LYG** [comment]
> Well, it's a PyTorch issue. They don't support deterministic training with grid_sampler. But you only use deterministic training if you want to make it reproduceable which is for research.
> 
> glenn-jocher, don't reply to me.
I ran into these problems when I was trying to customize the training data, and in the link, I would love to ask for your clarification
https://github.com/ultralytics/ultralytics/issues/13905#issue-2368500999

**Comment by glenn-jocher** [comment]
Thank you for your patience. You are correct that the warning arises from a PyTorch limitation regarding deterministic training with `grid_sampler`. This is primarily an issue if you require reproducibility for research purposes.

To address your question about customizing training data, please ensure that your dataset is correctly formatted and follows the guidelines provided in our [documentation](https://docs.ultralytics.com/datasets/). If you encounter specific issues, please provide a minimum reproducible example so we can better assist you. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you are using the latest versions of `torch` and `ultralytics` and still face issues, please share the relevant code and error messages. This will help us diagnose and resolve the problem more effectively.

Feel free to reach out with any further questions! 😊

**Comment by QianYing-LYG** [comment]
> Thank you for your patience. You are correct that the warning arises from a PyTorch limitation regarding deterministic training with `grid_sampler`. This is primarily an issue if you require reproducibility for research purposes.
> 
> To address your question about customizing training data, please ensure that your dataset is correctly formatted and follows the guidelines provided in our [documentation](https://docs.ultralytics.com/datasets/). If you encounter specific issues, please provide a minimum reproducible example so we can better assist you. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> If you are using the latest versions of `torch` and `ultralytics` and still face issues, please share the relevant code and error messages. This will help us diagnose and resolve the problem more effectively.
> 
> Feel free to reach out with any further questions! 😊

Thanks for your reply. After a lot of searching, I have a general understanding🤞

**Comment by glenn-jocher** [comment]
You're welcome! 😊 I'm glad to hear that you're making progress. If you encounter any specific issues or need further clarification, please don't hesitate to provide a minimum reproducible example. This will help us better understand the problem and offer a more targeted solution. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Also, ensure you are using the latest versions of `torch` and `ultralytics` to avoid any known issues that might have been resolved in recent updates.

Feel free to reach out with any more questions or concerns. Happy training! 🚀

**Comment by QianYing-LYG** [comment]
> You're welcome! 😊 I'm glad to hear that you're making progress. If you encounter any specific issues or need further clarification, please don't hesitate to provide a minimum reproducible example. This will help us better understand the problem and offer a more targeted solution. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Also, ensure you are using the latest versions of `torch` and `ultralytics` to avoid any known issues that might have been resolved in recent updates.
> 
> Feel free to reach out with any more questions or concerns. Happy training! 🚀

Hello, why does rt-detr not have resnet18 and resnet34 light yaml files

**Comment by glenn-jocher** [comment]
Hi there!

Thank you for your question. Currently, the RT-DETR models provided in the Ultralytics repository do not include configurations for ResNet18 and ResNet34. The available configurations are designed to balance performance and efficiency for a variety of use cases, but we understand the need for more lightweight options.

If you are looking to create a custom configuration with ResNet18 or ResNet34, you can modify the existing YAML configuration files to use these backbones. Here’s a brief guide on how you can do this:

1. **Clone the repository** and navigate to the `cfg` directory where the model configuration files are located.
2. **Copy an existing RT-DETR configuration file** (e.g., `rtdetr.yaml`) and rename it (e.g., `rtdetr_resnet18.yaml`).
3. **Modify the backbone section** of the YAML file to use ResNet18 or ResNet34. You can refer to the PyTorch model zoo for the exact architecture details.

Here’s an example of how you might modify the backbone section:
```yaml
# Example configuration for RT-DETR with ResNet18 backbone
backbone:
  type: resnet18
  pretrained: true
  # Add any additional parameters required for ResNet18
```

4. **Save the modified YAML file** and use it to train your model:
```bash
yolo detect train data=coco128.yaml model=rtdetr_resnet18.yaml epochs=100 imgsz=640
```

This approach allows you to experiment with different backbones and find the optimal balance between model size and performance for your specific application.

If you encounter any issues or need further assistance, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us better understand your setup and provide more targeted support.

Happy experimenting! 🚀

**Comment by glenn-jocher** [comment]
Hi there!

Thank you for your detailed question and for sharing your configuration. It looks like you're on the right track with modifying the RT-DETR configuration to use ResNet18. However, there might be some specific adjustments needed to ensure compatibility and proper functionality.

Here's a refined approach to modifying the configuration for ResNet18:

1. **Clone the repository** and navigate to the `cfg` directory where the model configuration files are located.
2. **Copy an existing RT-DETR configuration file** (e.g., `rtdetr.yaml`) and rename it (e.g., `rtdetr_resnet18.yaml`).
3. **Modify the backbone section** of the YAML file to use ResNet18. Ensure that the rest of the configuration aligns with the architecture of ResNet18.

Here’s an example of how you might modify the backbone section:

```yaml
# Example configuration for RT-DETR with ResNet18 backbone
nc: 80  # number of classes
scales:  # model compound scaling constants
  l: [1.00, 1.00, 1024]

backbone:
  type: resnet18
  pretrained: true

head:
  - [ -1, 1, Conv, [256, 1, 1, None, 1, 1, False] ]  # 5
  - [ -1, 1, AIFI, [1024, 8] ]
  - [ -1, 1, Conv, [256, 1, 1] ]  # 7
  - [ -1, 1, nn.Upsample, [None, 2, "nearest"] ]
  - [ 3, 1, Conv, [256, 1, 1, None, 1, 1, False] ]  # 9
  - [ [-2, -1], 1, Concat, [1] ]
  - [ -1, 3, RepC3, [256] ]  # 11
  - [ -1, 1, Conv, [256, 1, 1] ]  # 12
  - [ -1, 1, nn.Upsample, [None, 2, "nearest"] ]
  - [ 2, 1, Conv, [256, 1, 1, None, 1, 1, False] ]  # 14
  - [ [-2, -1], 1, Concat, [1] ]  # cat backbone P4
  - [ -1, 3, RepC3, [256] ]  # X3 (16), fpn_blocks.1
  - [ -1, 1, Conv, [256, 3, 2] ]  # 17, downsample_convs.0
  - [ [-1, 12], 1, Concat, [1] ]  # cat Y4
  - [ -1, 3, RepC3, [256] ]  # F4 (19), pan_blocks.0
  - [ -1, 1, Conv, [256, 3, 2] ]  # 20, downsample_convs.1
  - [ [-1, 7], 1, Concat, [1] ]  # cat Y5
  - [ -1, 3, RepC3, [256] ]  # F5 (22), pan_blocks.1
  - [ [16, 19, 22], 1, RTDETRDecoder, [nc] ]  # Detect(P3, P4, P5)
```

4. **Save the modified YAML file** and use it to train your model:
```bash
yolo detect train data=coco128.yaml model=rtdetr_resnet18.yaml epochs=100 imgsz=640
```

If you encounter any issues or need further assistance, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us better understand your setup and provide more targeted support.

Feel free to reach out with any more questions or concerns. Happy experimenting! 🚀

**Comment by QianYing-LYG** [comment]
Sorry. According to the example, the error is still reported as follows：
```
D:\anaconda3\envs\ul\python.exe D:\GitHub\ultralytics\RT_train.py 
Traceback (most recent call last):
  File "D:\GitHub\ultralytics\RT_train.py", line 4, in <module>
    model = RTDETR("D:\\GitHub\\ultralytics\\ultralytics\\cfg\\models\\rt-detr\\rtdetr-resnet18.yaml")
  File "D:\GitHub\ultralytics\ultralytics\models\rtdetr\model.py", line 37, in __init__
    super().__init__(model=model, task="detect")
  File "D:\GitHub\ultralytics\ultralytics\engine\model.py", line 147, in __init__
    self._new(model, task=task, verbose=verbose)
  File "D:\GitHub\ultralytics\ultralytics\engine\model.py", line 208, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "D:\GitHub\ultralytics\ultralytics\nn\tasks.py", line 500, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "D:\GitHub\ultralytics\ultralytics\nn\tasks.py", line 297, in __init__
    if self.yaml["backbone"][0][2] == "Silence":
KeyError: 0

Process finished with exit code 1
```

**Comment by glenn-jocher** [comment]
@QianYing-LYG hi there,

Thank you for providing the error details. It looks like there's an issue with the configuration file for RT-DETR using ResNet18. To help us diagnose the problem more effectively, could you please provide a minimum reproducible example? This will allow us to better understand your setup and pinpoint the issue. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest versions of `torch` and `ultralytics` to avoid any known issues that might have been resolved in recent updates.

In the meantime, here are a few steps you can take to troubleshoot the issue:

1. **Verify Configuration File**: Ensure that the `rtdetr-resnet18.yaml` file is correctly formatted and that all necessary parameters are included. The error suggests that there might be a missing or incorrect key in the backbone configuration.

2. **Example Configuration**: Here's a refined example of how the configuration file might look:
    ```yaml
    # Example configuration for RT-DETR with ResNet18 backbone
    nc: 80  # number of classes
    scales:  # model compound scaling constants
      l: [1.00, 1.00, 1024]

    backbone:
      type: resnet18
      pretrained: true

    head:
      - [ -1, 1, Conv, [256, 1, 1, None, 1, 1, False] ]  # 5
      - [ -1, 1, AIFI, [1024, 8] ]
      - [ -1, 1, Conv, [256, 1, 1] ]  # 7
      - [ -1, 1, nn.Upsample, [None, 2, "nearest"] ]
      - [ 3, 1, Conv, [256, 1, 1, None, 1, 1, False] ]  # 9
      - [ [-2, -1], 1, Concat, [1] ]
      - [ -1, 3, RepC3, [256] ]  # 11
      - [ -1, 1, Conv, [256, 1, 1] ]  # 12
      - [ -1, 1, nn.Upsample, [None, 2, "nearest"] ]
      - [ 2, 1, Conv, [256, 1, 1, None, 1, 1, False] ]  # 14
      - [ [-2, -1], 1, Concat, [1] ]  # cat backbone P4
      - [ -1, 3, RepC3, [256] ]  # X3 (16), fpn_blocks.1
      - [ -1, 1, Conv, [256, 3, 2] ]  # 17, downsample_convs.0
      - [ [-1, 12], 1, Concat, [1] ]  # cat Y4
      - [ -1, 3, RepC3, [256] ]  # F4 (19), pan_blocks.0
      - [ -1, 1, Conv, [256, 3, 2] ]  # 20, downsample_convs.1
      - [ [-1, 7], 1, Concat, [1] ]  # cat Y5
      - [ -1, 3, RepC3, [256] ]  # F5 (22), pan_blocks.1
      - [ [16, 19, 22], 1, RTDETRDecoder, [nc] ]  # Detect(P3, P4, P5)
    ```

3. **Check for Missing Keys**: Ensure that all keys required by the model are present in the configuration file. The error `KeyError: 0` suggests that the model is trying to access a key that doesn't exist.

If the issue persists, please share the specific configuration file and any additional code snippets that might help us reproduce the issue on our end.

Looking forward to your response!
