### ISSUE TITLE
Yolov8 trains 100 epochs on the coco8 dataset with a map of 0

### ISSUE THREAD

**Issue by Vayne0227** [ultralytics/ultralytics#14103]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello author, I attempted to train 100 epochs on the coco8 dataset with a map of 0 and no decrease in loss
![607f9a4bc214d3a507c474619c29d81](https://github.com/ultralytics/ultralytics/assets/66624169/7cf0ec97-f675-4a06-9644-0fc50fff5a6a)
![6e7f231d43ff3356835fdfc8f958537](https://github.com/ultralytics/ultralytics/assets/66624169/006558dc-2922-4592-a50d-a0e8930a979d)

**Comment by glenn-jocher** [comment]
@Vayne0227 hello,

Thank you for reaching out and providing details about your training issue with the COCO8 dataset. To better assist you, could you please provide a minimum reproducible example of your training script? This will help us diagnose the problem more effectively. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest version of the Ultralytics packages. Sometimes, issues are resolved in newer releases, and updating might fix the problem.

Here is a quick checklist to verify:
1. **Update Packages**: Ensure you have the latest versions of Ultralytics and YOLOv8.
2. **Reproducible Example**: Share a snippet of your training code.
3. **Environment Details**: Provide information about your environment (e.g., Python version, OS, GPU/CPU details).

For reference, here is a basic example of how to train YOLOv8 on the COCO8 dataset:

```python
from ultralytics import YOLO

# Load a pretrained model
model = YOLO("yolov8n.pt")

# Train the model
results = model.train(data="coco8.yaml", epochs=100, imgsz=640)
```

If you have already followed these steps and the issue persists, please let us know, and we will investigate further.

Looking forward to your response!

**Comment by Vayne0227** [comment]
Thank you for your answer. I can indeed solve the problem by using pre trained weights as per your suggestion. 
![40eedab04a60b652c1b05017f961c94](https://github.com/ultralytics/ultralytics/assets/66624169/336bc191-b73c-4634-8f55-65026a268e87)
![dbcc666ee9520de8bb6d2877cae92e7](https://github.com/ultralytics/ultralytics/assets/66624169/88ca9bb5-d4bf-49d2-beb6-8c4a190d489c)
But when I retrain through the. yaml file, there is still a situation where the loss does not decrease and the map is 0. I am already using the latest version of the Ultralytics software package.
![5a81bf9cfda37ccc58f608419a30d39](https://github.com/ultralytics/ultralytics/assets/66624169/a1344b64-7f69-4cdd-a275-43a45a7022b6)
![f980afd1088a89b75685e004acbf737](https://github.com/ultralytics/ultralytics/assets/66624169/d1ab0cdf-0dc2-415e-a32c-f478f2c574f0)

**Comment by glenn-jocher** [comment]
@Vayne0227 thank you for the update! I'm glad to hear that using pretrained weights helped resolve part of the issue. 😊

Given that the problem persists when retraining through the `.yaml` file, let's delve deeper into a few potential areas:

1. **Configuration Verification**:
   Ensure that your `.yaml` configuration file is correctly set up. Sometimes, minor misconfigurations can lead to unexpected results. Double-check the paths, class labels, and other parameters.

2. **Data Quality**:
   Verify the quality and format of your dataset. Ensure that the annotations are correct and that the images are properly labeled. Poor data quality can significantly impact training performance.

3. **Learning Rate and Batch Size**:
   Experiment with different learning rates and batch sizes. Sometimes, the default values may not be optimal for your specific dataset. You can adjust these parameters in your `.yaml` file or directly in your training script.

4. **Training Script**:
   If possible, share a snippet of your training script and the relevant parts of your `.yaml` file. This will help us better understand your setup and provide more targeted advice.

Here’s a quick example of how you might adjust the learning rate and batch size in your training script:

```python
from ultralytics import YOLO

# Load a pretrained model
model = YOLO("yolov8n.pt")

# Train the model with custom parameters
results = model.train(data="coco8.yaml", epochs=100, imgsz=640, lr0=0.01, batch=16)
```

5. **Monitoring Tools**:
   Utilize tools like TensorBoard or Comet to monitor your training metrics in real-time. This can provide insights into what might be going wrong during training.

If you continue to face issues, please provide a minimum reproducible example of your training setup. This will greatly assist in diagnosing the problem. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Looking forward to your response! Let's get this resolved together. 🚀

**Comment by Vishawjeet-rmsl** [comment]
I have a similar Issue.
I'm trying to train yolov8n.yaml on my custom dataset, but even after training for a 1000 epochs, Accuracy, Precision and mAP is still 0. The training loss started from 2 and isn't going below 0.5. 

My dataset.yaml file is like this:
`path: ../datasets/blob # dataset root dir
train: images/train # train images (relative to 'path') 20 images
val: images/val # val images (relative to 'path') 3 images
test: images/test # test images (optional) 0 images

# Classes for blob
names:
  0: deformed
  `

So, it's a one class detection task.

My training file is like this:
`from ultralytics import YOLO
model = YOLO("yolov8n.yaml")
results = model.train("dataset.yaml", epochs =1000, imgsz = 640, batch = 12, single_cls=True)
`

I've been at this for many hours now, but I can't figure out what's the issue. My ground truth is in the format that is required by yolob8n.yaml: 0 0.378551 0.612994 0.261987 0.311516, also visualized this using script and the bounding boxes are correctly placed.

I've tried with different epochs and batch. 

This is the first time I'm working with YOLO/Object Detection. Am I doing something wrong? Because no matter what, after training for a 1000 epochs, it should detect something!

And, in my custom dataset as of now i have 115 images for training and 8 images for validation. If I'm training for 1000 epochs, at least it should overfit. 

Snapshot:

![image](https://github.com/user-attachments/assets/a787cf0a-d37c-4e37-a9a0-cdaf27bbef66)

**Comment by pderrenger** [comment]
It sounds like you're facing a frustrating issue. Given your setup, let's ensure a few things: First, verify that you're using the latest version of the Ultralytics package. Sometimes, issues are resolved in newer releases. Also, check if your dataset annotations are correctly formatted and consistent. Since it's a one-class detection task, ensure that the `single_cls=True` argument is correctly applied. If the problem persists, try reducing the complexity by training for fewer epochs initially to see if there's any improvement. If none of these steps help, please share more details about your dataset and training environment.

**Comment by Vishawjeet-rmsl** [comment]
Hi, thanks for responding. Yes, I have verified the dataset annotation format, have included the single_cls=True argument, and have also check by training for a fewer number of epochs.

As for the ultralytics version, I installed it just 2 days back using `pip install ultralytics`

Training environment is as follows:
1. Name: torch , Version: 1.9.0+cu111
2. Name: torchvision, Version: 0.10.0+cu111
3. Name: ultralytics, Version: 8.2.58
4. The whole list:
```
Package                      Version
---------------------------- ------------
absl-py                      0.15.0
albumentations               1.3.0
altgraph                     0.17.2
appdirs                      1.4.4
asttokens                    2.2.1
astunparse                   1.6.3
backcall                     0.1.0
cachetools                   5.3.0
certifi                      2022.12.7
charset-normalizer           3.0.1
colorama                     0.4.6
coloredlogs                  15.0.1
comm                         0.1.3
contextlib2                  0.5.5
contourpy                    1.0.7
cycler                       0.11.0
Cython                       0.29.35
debugpy                      1.6.7
decorator                    5.1.1
defusedxml                   0.7.1
easyfsl                      1.3.0
efficientnet                 1.0.0
exceptiongroup               1.1.1
executing                    1.2.0
filelock                     3.15.4
flatbuffers                  1.12
fonttools                    4.38.0
fsspec                       2023.9.2
gast                         0.3.3
gin                          0.1.6
gin-config                   0.5.0
google-auth                  2.16.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.32.0
h5py                         2.10.0
huggingface-hub              0.18.0
humanfriendly                10.0
idna                         3.4
image-classifiers            1.0.0
imageio                      2.25.0
imgaug                       0.4.0
iniconfig                    2.0.0
ipykernel                    6.23.1
ipython                      8.12.2
ipython-genutils             0.2.0
jedi                         0.18.2
Jinja2                       3.1.2
joblib                       1.2.0
jupyter_client               8.2.0
jupyter_core                 5.3.0
keras                        2.7.0
Keras-Applications           1.0.8
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
kneed                        0.8.5
libclang                     15.0.6.1
lvis                         0.5.3
Mako                         1.2.4
Markdown                     3.4.1
MarkupSafe                   2.1.2
matplotlib                   3.6.3
matplotlib-inline            0.1.6
monai                        1.0.0
mpmath                       1.3.0
natsort                      8.3.1
nest-asyncio                 1.5.6
networkx                     3.0
numpy                        1.24.4
oauthlib                     3.2.2
onnx                         1.14.0
onnxruntime                  1.15.1
opencv-python                4.10.0.84
opencv-python-headless       4.7.0.72
opt-einsum                   3.3.0
packaging                    24.1
pandas                       1.5.3
parso                        0.8.3
pickleshare                  0.7.5
Pillow                       9.4.0
pip                          24.1.2
platformdirs                 3.5.1
pluggy                       1.0.0
prompt-toolkit               3.0.38
protobuf                     3.20.3
psutil                       5.9.5
pure-eval                    0.2.2
py-cpuinfo                   9.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycocotools-windows          2.0.0.2
Pygments                     2.15.1
pyinstaller-hooks-contrib    2021.4
pynvml                       11.5.0
pyparsing                    3.0.9
pyreadline3                  3.4.1
pytest                       7.3.1
python-dateutil              2.8.2
pytools                      2022.1.14
pytz                         2024.1
PyWavelets                   1.4.1
pywin32                      306
pywin32-ctypes               0.2.0
PyYAML                       6.0.1
pyzmq                        25.0.2
qudida                       0.0.4
regex                        2023.10.3
requests                     2.28.2
requests-oauthlib            1.3.1
rsa                          4.9
RVP                          21.0
safetensors                  0.4.0
scikit-image                 0.17.2
scikit-learn                 1.2.1
scipy                        1.10.0
seaborn                      0.13.2
segment-anything             1.0
segmentation-models          1.0.1
setuptools                   69.5.1
shapely                      2.0.5
six                          1.15.0
stack-data                   0.6.2
supervision                  0.22.0
sympy                        1.12
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.0
tensorflow-estimator         2.7.0
tensorflow-io                0.31.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    1.1.0
tf-slim                      1.1.0
tf2onnx                      1.14.0
threadpoolctl                3.1.0
tifffile                     2023.2.3
tokenizers                   0.15.0
tomli                        2.0.1
torch                        1.9.0+cu111
torchaudio                   0.9.0
torchvision                  0.10.0+cu111
tornado                      6.3.2
tqdm                         4.65.0
traitlets                    5.9.0
transformers                 4.35.2
typing_extensions            4.6.2
ultralytics                  8.2.58
ultralytics-thop             2.0.0
urllib3                      1.26.14
wcwidth                      0.1.7
webencodings                 0.5.1
Werkzeug                     3.0.3
wheel                        0.40.0
wrapt                        1.12.1
zipp                         3.6.0
```


I also noticed something strange, even though the mAP, A, and P is 0 throughout the training process, and in the **runs/obb/train/** folder the generated val_predict file contains no bounding boxes, when I manually do "model.predict(path and other stuffs)", it does generate bounding boxes. And when I do "model.val(yaml file and other stuffs..)" it does print the metrics values.

So, is it a bug? Because I can't see these metric values during the training period.

Another thing, slightly off the topic, when I was training the model, and I used "model.predict()" function to predict on testing samples from a directory, it generated some output, then I exited the terminal, and after a while I loaded the weights stored in "best.pt" and "last.pt", but this time the predicted bounding boxes aren't the same. So, is it possible that for different calls of predict function on the same image using the same weight file, we get different results?


Thanks in advance!

**Comment by pderrenger** [comment]
Thank you for the detailed information. It seems like you've covered most of the basics. Given that your `model.predict()` and `model.val()` functions are working correctly but the training metrics are not updating as expected, this might indicate a potential issue with the training loop or logging mechanism.

First, ensure that your dataset annotations are correctly formatted and consistent. Since you mentioned that predictions work but training metrics don't update, it might be worth double-checking the dataset paths and labels.

Regarding the discrepancy in predictions when using the same weights, predictions should generally be consistent if the model and weights are the same. However, slight variations can occur due to non-deterministic operations in the model or preprocessing steps. Ensure that you set a random seed for reproducibility if consistent results are required.

If the issue persists, please try updating to the latest versions of all relevant packages, including PyTorch and Ultralytics. Sometimes, bugs are fixed in newer releases.

For further assistance, you can refer to the [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/) for more troubleshooting tips. If the problem continues, consider opening an issue on the Ultralytics GitHub repository with your findings.

**Comment by cainiao123s** [comment]
> Ultralytics

In fact, the problem still exists. I have used the latest version of Ultralytics, but there are still cases where p, r, and map are all 0.

**Comment by cainiao123s** [comment]
> 嗨，感谢您的回复。是的，我已经验证了数据集注释格式，已包含 single_cls=True 参数，并且还通过训练了较少的 epoch 数进行了检查。
> 
> 至于 ultralytics 版本，我两天前刚刚安装过，使用`pip install ultralytics`
> 
> 训练环境如下：
> 
> 1. 名称：torch，版本：1.9.0+cu111
> 2. 名称：torchvision，版本：0.10.0+cu111
> 3. 名称：ultralytics，版本：8.2.58
> 4. 完整列表：
> 
> ```
> Package                      Version
> ---------------------------- ------------
> absl-py                      0.15.0
> albumentations               1.3.0
> altgraph                     0.17.2
> appdirs                      1.4.4
> asttokens                    2.2.1
> astunparse                   1.6.3
> backcall                     0.1.0
> cachetools                   5.3.0
> certifi                      2022.12.7
> charset-normalizer           3.0.1
> colorama                     0.4.6
> coloredlogs                  15.0.1
> comm                         0.1.3
> contextlib2                  0.5.5
> contourpy                    1.0.7
> cycler                       0.11.0
> Cython                       0.29.35
> debugpy                      1.6.7
> decorator                    5.1.1
> defusedxml                   0.7.1
> easyfsl                      1.3.0
> efficientnet                 1.0.0
> exceptiongroup               1.1.1
> executing                    1.2.0
> filelock                     3.15.4
> flatbuffers                  1.12
> fonttools                    4.38.0
> fsspec                       2023.9.2
> gast                         0.3.3
> gin                          0.1.6
> gin-config                   0.5.0
> google-auth                  2.16.0
> google-auth-oauthlib         0.4.6
> google-pasta                 0.2.0
> grpcio                       1.32.0
> h5py                         2.10.0
> huggingface-hub              0.18.0
> humanfriendly                10.0
> idna                         3.4
> image-classifiers            1.0.0
> imageio                      2.25.0
> imgaug                       0.4.0
> iniconfig                    2.0.0
> ipykernel                    6.23.1
> ipython                      8.12.2
> ipython-genutils             0.2.0
> jedi                         0.18.2
> Jinja2                       3.1.2
> joblib                       1.2.0
> jupyter_client               8.2.0
> jupyter_core                 5.3.0
> keras                        2.7.0
> Keras-Applications           1.0.8
> Keras-Preprocessing          1.1.2
> kiwisolver                   1.4.4
> kneed                        0.8.5
> libclang                     15.0.6.1
> lvis                         0.5.3
> Mako                         1.2.4
> Markdown                     3.4.1
> MarkupSafe                   2.1.2
> matplotlib                   3.6.3
> matplotlib-inline            0.1.6
> monai                        1.0.0
> mpmath                       1.3.0
> natsort                      8.3.1
> nest-asyncio                 1.5.6
> networkx                     3.0
> numpy                        1.24.4
> oauthlib                     3.2.2
> onnx                         1.14.0
> onnxruntime                  1.15.1
> opencv-python                4.10.0.84
> opencv-python-headless       4.7.0.72
> opt-einsum                   3.3.0
> packaging                    24.1
> pandas                       1.5.3
> parso                        0.8.3
> pickleshare                  0.7.5
> Pillow                       9.4.0
> pip                          24.1.2
> platformdirs                 3.5.1
> pluggy                       1.0.0
> prompt-toolkit               3.0.38
> protobuf                     3.20.3
> psutil                       5.9.5
> pure-eval                    0.2.2
> py-cpuinfo                   9.0.0
> pyasn1                       0.4.8
> pyasn1-modules               0.2.8
> pycocotools-windows          2.0.0.2
> Pygments                     2.15.1
> pyinstaller-hooks-contrib    2021.4
> pynvml                       11.5.0
> pyparsing                    3.0.9
> pyreadline3                  3.4.1
> pytest                       7.3.1
> python-dateutil              2.8.2
> pytools                      2022.1.14
> pytz                         2024.1
> PyWavelets                   1.4.1
> pywin32                      306
> pywin32-ctypes               0.2.0
> PyYAML                       6.0.1
> pyzmq                        25.0.2
> qudida                       0.0.4
> regex                        2023.10.3
> requests                     2.28.2
> requests-oauthlib            1.3.1
> rsa                          4.9
> RVP                          21.0
> safetensors                  0.4.0
> scikit-image                 0.17.2
> scikit-learn                 1.2.1
> scipy                        1.10.0
> seaborn                      0.13.2
> segment-anything             1.0
> segmentation-models          1.0.1
> setuptools                   69.5.1
> shapely                      2.0.5
> six                          1.15.0
> stack-data                   0.6.2
> supervision                  0.22.0
> sympy                        1.12
> tensorboard                  2.11.2
> tensorboard-data-server      0.6.1
> tensorboard-plugin-wit       1.8.1
> tensorflow                   2.7.0
> tensorflow-estimator         2.7.0
> tensorflow-io                0.31.0
> tensorflow-io-gcs-filesystem 0.31.0
> termcolor                    1.1.0
> tf-slim                      1.1.0
> tf2onnx                      1.14.0
> threadpoolctl                3.1.0
> tifffile                     2023.2.3
> tokenizers                   0.15.0
> tomli                        2.0.1
> torch                        1.9.0+cu111
> torchaudio                   0.9.0
> torchvision                  0.10.0+cu111
> tornado                      6.3.2
> tqdm                         4.65.0
> traitlets                    5.9.0
> transformers                 4.35.2
> typing_extensions            4.6.2
> ultralytics                  8.2.58
> ultralytics-thop             2.0.0
> urllib3                      1.26.14
> wcwidth                      0.1.7
> webencodings                 0.5.1
> Werkzeug                     3.0.3
> wheel                        0.40.0
> wrapt                        1.12.1
> zipp                         3.6.0
> ```
> 
> 我还注意到一些奇怪的事情，尽管在整个训练过程中 mAP、A 和 P 都为 0，并且在**/train/**文件夹中生成的 val_predict 文件不包含边界框，但当我手动执行“model.predict(path and other stuffs)”时，它确实会生成边界框。当我执行“model.val(yaml file and other stuffs..)”时，它确实会打印度量值。
> 
> 那么，这是一个错误吗？因为在训练期间我看不到这些指标值。
> 
> 还有一件事，稍微偏离主题，当我训练模型时，我使用“model.predict()”函数对目录中的测试样本进行预测，它生成了一些输出，然后我退出终端，过了一会儿，我加载了存储在“best.pt”和“last.pt”中的权重，但这次预测的边界框不一样。那么，对于使用相同权重文件对同一图像进行不同的预测函数调用，我们是否会得到不同的结果？
> 
> 提前致谢！

By the way, has the questioner resolved the issue?

**Comment by glenn-jocher** [comment]
Thanks for providing detailed feedback. Based on your observations, it seems that the metrics during training might not be updating correctly, even though the model performs as expected when using `model.predict()` or `model.val()`. This could potentially be a logging or evaluation issue during the training loop. To investigate further:

1. Confirm the dataset paths and annotations are correctly set during training (e.g., `data.yaml`).
2. Check if `single_cls=True` is properly applied across all relevant operations.
3. Try using a different PyTorch version (e.g., `1.12+`) for compatibility improvements.
4. If the issue persists, please open a GitHub issue with a minimal reproducible example to help us debug further: https://github.com/ultralytics/ultralytics/issues.

Regarding prediction inconsistencies: Predictions may vary slightly due to non-deterministic operations or augmentations during training. For consistent results, ensure reproducibility by setting a random seed at the start of your script. Let us know if you need additional clarification!
