### ISSUE TITLE
class issue for customdata set

### ISSUE THREAD

**Issue by anut123** [ultralytics/ultralytics#2374]
I am using yolov8 model for deepsort algorithm for object tracking so I have trained the model by using yolov8 model as an class of mango And when I try to execute the command for deepsort object tracking then the output is coming broccoli as an class so in deepsort code where should I change?
So that the output should get as an mango class instead of broccoli class
@AyushExel

**Comment by AyushExel** [comment]
Please share the data.yaml for the dataset that you've used to train the model.

**Comment by anut123** [comment]
path: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\dataset\\'  
train: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\dataset\\train\\'   
val: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\dataset\\val\\' 
test: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\dataset\\test\\' 
# Classes
nc: 1 # number of classes
names: ['mango'] # class names

**Comment by AyushExel** [comment]
When you run `yolo train data=path_to_data.yaml model=model.pt` you don't see any errors and it trains fine? I think it might error out due to your path settings here but if it does train it should output the correct class.

**Comment by anut123** [comment]
but actually i am running this command of object tracking to get the output ---> python predict
py model='C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\runs\\detect\\train12\\weights\\best.pt' source='C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\video.mp4' model=yolov8n.pt show=True

**Comment by AyushExel** [comment]
You are passing the model twice? if you're overriding the model=best.pt with model=yolov8n.pt then you won't get the correct output.

**Comment by anut123** [comment]
but by using this command i am getting correct output --> python predict
py model='C:\Users\PycharmProjects\YOLOv8-DeepSORT-Object-Tracking\runs\detect\train12\weights\best.pt' source='C:\Users\PycharmProjects\YOLOv8-DeepSORT-Object-Tracking\video.mp4' model=yolov8n.pt show=True
only facing issue with the class name

**Comment by AyushExel** [comment]
You're getting the correct output because apple is a class in yolov8n.pt which is trained on coco. So it'll show apple which is correct. You are not using you're custom trained model here.

**Comment by anut123** [comment]
and sometimes the class name is getting as brocolli also instead of mango class

**Comment by AyushExel** [comment]
Yes because that is also a class in coco dataset that the yolov8n.pt model is trained on. You can either use your model which is the first one or the coco model, but not both

**Comment by anut123** [comment]
okay can you tell me the steps how to get the mango class then as i trained the model with mango class only

**Comment by AyushExel** [comment]
You should not get anything other than mango when you use this model if it is trained on your dataset:
```
python predict
py model='C:\Users\PycharmProjects\YOLOv8-DeepSORT-Object-Tracking\runs\detect\train12\weights\best.pt' source='C:\Users\PycharmProjects\YOLOv8-DeepSORT-Object-Tracking\video.mp4' show=True
```

**Comment by anut123** [comment]
but i am getting broccoli as class name instead of mango class then how to get the mango class i have trained the model many times but still the same issue

**Comment by AyushExel** [comment]
Most probably there is something wrong with how you've trained the model. Can you paste the training command you've used here?

**Comment by anut123** [comment]
yolo task=detect mode=train epochs=3 data=data_custom.yaml model=yolov8n.pt imgsz=640

**Comment by AyushExel** [comment]
run this command and see if output matches your classes
```
from ultralytics import YOLO

model = YOLO("path to model") # load your custom model here
print(model.names)
```

**Comment by anut123** [comment]
okay sure

**Comment by anut123** [comment]
error came like this AttributeError: 'YOLO' object has no attribute 'names'

**Comment by AyushExel** [comment]
Please paste the complete code that you're running

**Comment by anut123** [comment]
from ultralytics import YOLO 
>>> model = YOLO("C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\yolov8n.pt") 
>>> print(model.names)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'YOLO' object has no attribute 'names'

**Comment by AyushExel** [comment]
Paste the complete console output. Make sure you're on the latest version of the repo

**Comment by anut123** [comment]
python
Python 3.7.0 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLO                                                                                                  
>>> model = YOLO("C:\\Users\\PycharmProject\\YOLOv8-DeepSORT-Object-Tracking\\yolov8n.pt")
>>> print(model.names)                                                                                                            
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'YOLO' object has no attribute 'names'

**Comment by AyushExel** [comment]
Ultralytics version not python

**Comment by anut123** [comment]
ultralytics --version
Hydra 1.2.0

**Comment by AyushExel** [comment]
I was aksing for ultralytics version not hydra version. Please make sure you're running the latest version. the error you encountered should be fixed in the latest version

**Comment by anut123** [comment]
I am using latest version of ultralytics  is 8.0.0  and i am running this command for  object tracking to get the output > python predict.py source='C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\video2.mp4' model=yolov8n.pt show=True and still facing the same issue broccoli as class name instead of mango class

**Comment by glenn-jocher** [comment]
@anut123 thank you for reaching out. It seems that you are encountering an issue with YOLOv8 object detection during object tracking. In the command you shared, it seems that you are using the 'yolov8n.pt' YOLOv8 model to predict object classes for the video feed. However, you are getting an unexpected class name (broccoli instead of mango). 

There could be various reasons why this issue is occurring, including model training issues or configuration issues. It would be helpful to know more details about how you trained the YOLOv8 model, and whether you have any custom configurations set up. Additionally, it would be helpful to see the output of the object detector on a single frame of the video feed to better diagnose the issue. You can try running the command with the 'show=False' flag to inspect the output.

Please let us know if there's anything else we can do to help.

**Comment by anut123** [comment]
okay sure i will try and let you know @glenn-jocher

**Comment by glenn-jocher** [comment]
@anut123 thank you for your response. I appreciate your willingness to try and resolve the issue. It would be helpful if you can provide more details about the issue, such as the exact problem you are encountering, and if possible, any error messages that you have received. Additionally, if you could provide information on the dataset used to train the YOLOv8 model, and any modifications made to the model or configuration settings, it would be easier to troubleshoot the issue. 

Once we have more information, we can work together to resolve the issue. Please feel free to ask any questions or provide additional information as needed.

**Comment by anut123** [comment]
![0](https://user-images.githubusercontent.com/68511266/236196560-4157df34-f4d7-4fc1-b38c-38afaea16c4c.jpg)
(1) I need number of rows, number of columns and total number of crops  for videos on yolov8 model
(2) and also need id, class name and confidence score for videos on yolov8 model
this my requirements

**Comment by glenn-jocher** [comment]
@anut123 hello! Thank you for reaching out. If I understand your question correctly, you are looking to obtain additional information such as the number of rows, number of columns, and total number of crops for videos using the YOLOv8 model. You also need the identification (ID), class name, and confidence score for these videos.

To obtain the number of rows, number of columns, and total number of crops, you can modify the predict.py file to output these additional metadata fields. You can access these fields using the detect() method in the YOLOv8 class. For example, you can modify the 'app.py' file in the 'demo' directory to output the metadata fields you need.

Regarding the issue with getting 'broccoli' as the predicted class name instead of 'mango', there could be many reasons why this is happening. Some possible causes could be issues with the training dataset or model configuration. It would be helpful to see more information such as the training dataset, any modifications made to the model or configuration settings, and the output of the object detector on a single frame of the video feed to better diagnose the issue. 

Please let us know if you have any additional questions or if there's anything else we can do to help. Thank you!

**Comment by anut123** [comment]
![0](https://user-images.githubusercontent.com/68511266/236380402-62cb240e-c845-4dd0-9f4a-7d46aced91c0.jpg)  --> training dataset image

default.yaml
# Ultralytics YOLO 🚀, GPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: "detect" # choices=['detect', 'segment', 'classify', 'init'] # init is a special case. Specify task to run.
mode: "train" # choices=['train', 'val', 'predict'] # mode to run task in.

# Train settings -------------------------------------------------------------------------------------------------------
model: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\yolov8n.pt' # i.e. yolov8n.pt, yolov8n.yaml. Path to model file
data: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\data.yaml' # i.e. coco128.yaml. Path to data file
epochs: 100 # number of epochs to train for
patience: 50  # TODO: epochs to wait for no observable improvement for early stopping of training
batch: 16 # number of images per batch
imgsz: 640 # size of input images
save: True # save checkpoints
cache: False # True/ram, disk or False. Use cache for data loading
device: null # cuda device, i.e. 0 or 0,1,2,3 or cpu. Device to run on
workers: 8 # number of worker threads for data loading
project: null # project name
nc: 1
names: ['mango']
#name: null # experiment name
exist_ok: False # whether to overwrite existing experiment
pretrained: False # whether to use a pretrained model
optimizer: 'SGD' # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
verbose: False # whether to print verbose output
seed: 0 # random seed for reproducibility
deterministic: True # whether to enable deterministic mode
single_cls: False # train multi-class data as single-class
image_weights: False # use weighted image selection for training
rect: False # support rectangular training
cos_lr: False # use cosine learning rate scheduler
close_mosaic: 10 # disable mosaic augmentation for final 10 epochs
resume: False # resume training from last checkpoint
# Segmentation
overlap_mask: True # masks should overlap during training
mask_ratio: 4 # mask downsample ratio
# Classification
dropout: 0.0  # use dropout regularization

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True # validate/test during training
save_json: False # save results to JSON file
save_hybrid: False # save hybrid version of labels (labels + additional predictions)
conf: null # object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7 # intersection over union (IoU) threshold for NMS
max_det: 300 # maximum number of detections per image
half: False # use half precision (FP16)
dnn: False # use OpenCV DNN for ONNX inference
plots: True # show plots during training

# Prediction settings --------------------------------------------------------------------------------------------------
source: 'C:\\Users\\PycharmProjects\\YOLOv8-DeepSORT-Object-Tracking\\video2.mp4' # source directory for images or videos
show: True # show results if possible
save_txt: False # save results as .txt file
save_conf: False # save results with confidence scores
save_crop: False # save cropped images with results
hide_labels: False # hide labels
hide_conf: False # hide confidence scores
vid_stride: 1 # video frame-rate stride
line_thickness: 3 # bounding box thickness (pixels)
visualize: False # visualize results
augment: False # apply data augmentation to images
agnostic_nms: False # class-agnostic NMS
retina_masks: False # use retina masks for object detection

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript # format to export to
keras: False  # use Keras
optimize: False  # TorchScript: optimize for mobile
int8: False  # CoreML/TF INT8 quantization
dynamic: False  # ONNX/TF/TensorRT: dynamic axes
simplify: False  # ONNX: simplify model
opset: 17  # ONNX: opset version
workspace: 4  # TensorRT: workspace size (GB)
nms: False  # CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final OneCycleLR learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr
box: 7.5  # box loss gain
cls: 0.5  # cls loss gain (scale with pixels)
dfl: 1.5  # dfl loss gain
fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
label_smoothing: 0.0
nbs: 64  # nominal batch size
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)

# Hydra configs --------------------------------------------------------------------------------------------------------
hydra:
  output_subdir: null  # disable hydra directory creation
  run:
    dir: .

# Debug, do not modify -------------------------------------------------------------------------------------------------
v5loader: False  # use legacy YOLOv5 dataloader

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # tracker type, ['botsort.yaml', 'bytetrack.yaml']

**Comment by glenn-jocher** [comment]
@anut123 hello! Thank you for reaching out. From the information provided, it's unclear what could have caused the issue with your predicted class name. It could be that there are issues with the dataset, or there could be other configuration settings that need to be adjusted. In order to diagnose and resolve the issue, we would need more information such as the training dataset, any modifications made to the model or configuration settings, and the output of the object detector on a single frame of the video feed. 

If you could provide more detail on these aspects, we can work together to identify the cause of the issue and develop a solution. Thank you!

**Comment by anut123** [comment]
![0](https://user-images.githubusercontent.com/68511266/236621052-fd6e4fb1-3edf-415f-bf79-bd65cdcec630.jpg)
![1](https://user-images.githubusercontent.com/68511266/236621055-9f1ca992-fbe9-4774-b14f-0967e6c69316.jpg)
![2](https://user-images.githubusercontent.com/68511266/236621056-9fd0534b-1abf-4d9a-870f-a0765bda049b.jpg)
![3](https://user-images.githubusercontent.com/68511266/236621059-967a6de6-73cd-4b34-b4df-c87b02f2638a.jpg)
![4](https://user-images.githubusercontent.com/68511266/236621060-fa891b26-a9e4-4581-a9eb-95fbbe0835c8.jpg)
![5](https://user-images.githubusercontent.com/68511266/236621063-aff60e83-e4a1-43fd-ac4f-3eb354ed4c80.jpg)
![6](https://user-images.githubusercontent.com/68511266/236621064-03b73658-a0c3-4d73-9082-c4bf169f1b77.jpg)
![7](https://user-images.githubusercontent.com/68511266/236621065-1bfd2d04-f3bb-453a-8517-f80ce76df42d.jpg)
![8](https://user-images.githubusercontent.com/68511266/236621067-6728abbb-45c9-472a-a1e6-017ed21ae846.jpg)
![9](https://user-images.githubusercontent.com/68511266/236621068-6290ea84-26d0-4b4b-b90e-f7169c5344c7.jpg)
![10](https://user-images.githubusercontent.com/68511266/236621069-9d56e123-86bc-4fdc-864d-db634e00b700.jpg)
![11](https://user-images.githubusercontent.com/68511266/236621070-bb92fdcf-ef12-44b7-a190-62f5feef8e63.jpg)
![12](https://user-images.githubusercontent.com/68511266/236621071-02be6313-99ac-45b1-8a3a-1bcdf3c2cf54.jpg)
![13](https://user-images.githubusercontent.com/68511266/236621072-acd54582-0f13-41f4-a354-7601149dedaa.jpg)
![14](https://user-images.githubusercontent.com/68511266/236621073-b878c288-a722-403b-8bd0-66043f993caf.jpg)
![15](https://user-images.githubusercontent.com/68511266/236621074-f816534e-2814-47b5-9740-afc81d76650d.jpg)
![16](https://user-images.githubusercontent.com/68511266/236621075-bc7bc777-3e72-4ab6-8c48-09b487b705c1.jpg)
![17](https://user-images.githubusercontent.com/68511266/236621076-f0f0deb7-ab18-4318-b998-8b0128f92c0a.jpg)
![18](https://user-images.githubusercontent.com/68511266/236621077-42392242-bbd1-4c27-9f16-cf2aad95b775.jpg)
![19](https://user-images.githubusercontent.com/68511266/236621078-814808dd-b27d-4e75-a1c2-fd2c7ef4e3e2.jpg)
![20](https://user-images.githubusercontent.com/68511266/236621079-b945bb52-7764-49c6-9cfe-a8ac9a645415.jpg)
![21](https://user-images.githubusercontent.com/68511266/236621080-d45ee013-c00c-4977-8dc7-3f36bfcba71a.jpg)
![22](https://user-images.githubusercontent.com/68511266/236621081-2aef9053-284f-47bc-a832-9fd9c6c68ca7.jpg)
![23](https://user-images.githubusercontent.com/68511266/236621082-ea344abe-71c1-4ff9-8afc-b76180e6c65f.jpg)
![24](https://user-images.githubusercontent.com/68511266/236621083-ae8d523d-923c-4242-b6cf-baed95db7fa0.jpg)
![25](https://user-images.githubusercontent.com/68511266/236621084-cc5ea4e0-e3a1-47b2-ac41-a1e60cfd95b4.jpg)
![26](https://user-images.githubusercontent.com/68511266/236621086-52492b76-9b6e-4be4-a123-aa66817e2d06.jpg)
![27](https://user-images.githubusercontent.com/68511266/236621087-845d074b-13d3-45fb-b6a9-06d8ff7277e9.jpg)
![28](https://user-images.githubusercontent.com/68511266/236621088-e0941815-5ace-4c5b-8abc-8d6b558d8448.jpg)
![29](https://user-images.githubusercontent.com/68511266/236621090-a64fc191-3132-4e4b-90a6-1c9e07c9d518.jpg)
![30](https://user-images.githubusercontent.com/68511266/236621091-d06d84b3-7608-4af3-86fb-58a7fcb99e6f.jpg)
![31](https://user-images.githubusercontent.com/68511266/236621092-5a68d1bd-f6b7-4425-bdd4-5d1e388a359f.jpg)
![32](https://user-images.githubusercontent.com/68511266/236621093-66e2a2a6-7de6-4be2-ab3e-90eb44335dfc.jpg)
![33](https://user-images.githubusercontent.com/68511266/236621094-00ff50be-946b-4159-926a-97c00b483c95.jpg)
![34](https://user-images.githubusercontent.com/68511266/236621095-66d0d97a-82f6-4d01-9f59-ab19007279c5.jpg)
![35](https://user-images.githubusercontent.com/68511266/236621098-d19114cf-4f2a-4b4a-869a-1486f3c22a76.jpg)
![36](https://user-images.githubusercontent.com/68511266/236621099-94a86e16-e4ba-4d36-8d37-c453a30d5e8d.jpg)
![37](https://user-images.githubusercontent.com/68511266/236621100-878761da-a338-48e0-8b4e-6467416bd1f0.jpg)
![38](https://user-images.githubusercontent.com/68511266/236621101-8540dabd-f27e-4d52-98c2-6b24f49fca97.jpg)
![39](https://user-images.githubusercontent.com/68511266/236621102-3ac89c6a-bb6b-4a5b-a070-9387522470ca.jpg)
![40](https://user-images.githubusercontent.com/68511266/236621104-b300ce3b-beef-44dd-9864-be08beedfff5.jpg)
![41](https://user-images.githubusercontent.com/68511266/236621105-67bf6bca-cf7b-417b-a249-c185decf4bf9.jpg)
![42](https://user-images.githubusercontent.com/68511266/236621106-e568a5aa-7cdd-4a2e-8341-87510a904abe.jpg)
![43](https://user-images.githubusercontent.com/68511266/236621110-35798bb2-cea9-4612-bdce-518b03be1a9d.jpg)
![44](https://user-images.githubusercontent.com/68511266/236621112-8fe7c992-8029-48a6-b0a3-3a9d16557c90.jpg)
![45](https://user-images.githubusercontent.com/68511266/236621113-42d11970-713a-4b7f-9516-9dd488cf0241.jpg)
![46](https://user-images.githubusercontent.com/68511266/236621114-7aff331c-066b-4a57-b2cb-472867a5710c.jpg)
![47](https://user-images.githubusercontent.com/68511266/236621117-fe81229c-47a8-4b15-aeb9-fadb9f60ee29.jpg)
![48](https://user-images.githubusercontent.com/68511266/236621118-6483d699-76b4-4019-bd8d-d1e23f71fc43.jpg)
![49](https://user-images.githubusercontent.com/68511266/236621119-17f668b0-a85c-40e8-abcb-b5869bd6b7d9.jpg)
![50](https://user-images.githubusercontent.com/68511266/236621120-4711c74e-9f8e-4f36-84b8-c8c4f317bfd7.jpg)
![51](https://user-images.githubusercontent.com/68511266/236621122-5376bd39-46e1-4e5a-859f-277794cccce3.jpg)
![52](https://user-images.githubusercontent.com/68511266/236621123-0a2ecae3-1f8c-43d3-99f5-5ba6e64d5c38.jpg)
![53](https://user-images.githubusercontent.com/68511266/236621126-721dee9f-8bef-462a-909f-090f5cc46efe.jpg)
![54](https://user-images.githubusercontent.com/68511266/236621127-2e035e33-cfa7-429a-ad97-af5b222e8294.jpg)
![55](https://user-images.githubusercontent.com/68511266/236621128-7180559d-2ba6-4802-9505-4a28c4601791.jpg)
![56](https://user-images.githubusercontent.com/68511266/236621129-d4d87f3e-82e8-4c53-8b65-decc736304a3.jpg)
![57](https://user-images.githubusercontent.com/68511266/236621130-87b03b4d-a715-4f99-b65d-7a83c88b1f2b.jpg)
![58](https://user-images.githubusercontent.com/68511266/236621131-68641eaa-06b4-49e9-a989-c1a8476722af.jpg)
![59](https://user-images.githubusercontent.com/68511266/236621132-a94c7168-2556-4596-bc18-fe99c455277d.jpg)
![60](https://user-images.githubusercontent.com/68511266/236621133-6e842b0d-2344-4f18-bed0-d3318bec7fca.jpg)
![61](https://user-images.githubusercontent.com/68511266/236621136-a5fc65d0-bd6c-42d1-b0b4-f55e4ccafdd2.jpg)
![62](https://user-images.githubusercontent.com/68511266/236621137-0172eb05-acda-4e70-b3c6-4c53f50867e9.jpg)
![63](https://user-images.githubusercontent.com/68511266/236621140-e8e3b5d6-30b3-4955-9aa0-55f9830106ae.jpg)
![64](https://user-images.githubusercontent.com/68511266/236621141-3ffcffb3-d5b0-447f-99f5-36b965f840a9.jpg)
![65](https://user-images.githubusercontent.com/68511266/236621142-373276a9-c984-43b7-9821-f099ef118c0c.jpg)
![66](https://user-images.githubusercontent.com/68511266/236621143-2036b8ce-4ed5-4a77-8a19-a08d189593ad.jpg)
![67](https://user-images.githubusercontent.com/68511266/236621144-46f1c274-ba0d-4faf-8353-2a335e45735c.jpg)
![68](https://user-images.githubusercontent.com/68511266/236621145-1ce6e2fa-67e4-4896-b1df-5198abef51cb.jpg)
![69](https://user-images.githubusercontent.com/68511266/236621146-e0b481b5-61ad-4b3e-97be-62644903203c.jpg)
![70](https://user-images.githubusercontent.com/68511266/236621148-2e1aca39-d815-4e6e-a676-3b73c981436e.jpg)
![71](https://user-images.githubusercontent.com/68511266/236621149-b9ff0203-264b-46a9-a6ac-e23b91e69ece.jpg)
![72](https://user-images.githubusercontent.com/68511266/236621150-af93a674-d77b-43e3-b8e1-c6b33e993a46.jpg)
![73](https://user-images.githubusercontent.com/68511266/236621151-8f2cb61f-dbe5-449a-980f-1ebec6fde4c9.jpg)
![74](https://user-images.githubusercontent.com/68511266/236621152-75341d66-1482-45fc-85bd-fe707a24332c.jpg)
![75](https://user-images.githubusercontent.com/68511266/236621153-6d0f7f1f-f6ce-44a1-9a8c-8b81f087f9dd.jpg)
![76](https://user-images.githubusercontent.com/68511266/236621154-42263e47-786f-450a-b5b7-ee9733103961.jpg)
![77](https://user-images.githubusercontent.com/68511266/236621155-196bb083-5b0e-439d-ae2d-9bf88586839b.jpg)
![78](https://user-images.githubusercontent.com/68511266/236621156-ccad2ee2-58a8-4f1d-82fa-f8b20d8a1807.jpg)
![79](https://user-images.githubusercontent.com/68511266/236621157-439efc52-95b7-4b8a-b36e-52b5752c60eb.jpg)
![80](https://user-images.githubusercontent.com/68511266/236621160-96d5b755-50bf-4abf-9392-c63c8a8a5650.jpg)
![81](https://user-images.githubusercontent.com/68511266/236621162-79e3a0db-f2e2-4a1e-8c80-8a54890c6cb8.jpg)
![82](https://user-images.githubusercontent.com/68511266/236621165-2e6d52eb-0c34-47ce-aade-f8994c35af4c.jpg)
![83](https://user-images.githubusercontent.com/68511266/236621167-d4e696dc-2502-451d-b106-9aa102eb80be.jpg)
![84](https://user-images.githubusercontent.com/68511266/236621168-0b66f613-0edb-4a19-9626-bde621777c7c.jpg)
![85](https://user-images.githubusercontent.com/68511266/236621169-9655e9aa-0600-43a5-bc6e-e74e4b7e0103.jpg)
![86](https://user-images.githubusercontent.com/68511266/236621170-aeef02fa-6833-4347-95c5-ecac91b785de.jpg)
![87](https://user-images.githubusercontent.com/68511266/236621171-9802e907-089d-4a0c-bb45-7806beaf9fad.jpg)
![88](https://user-images.githubusercontent.com/68511266/236621172-e7eee723-b87e-4eff-a699-a0abd2af76af.jpg)
![89](https://user-images.githubusercontent.com/68511266/236621173-dbf3b0f9-c82a-45b9-8ad4-10110e906fc2.jpg)
![90](https://user-images.githubusercontent.com/68511266/236621174-2befe1ec-2105-4f6d-9a1d-dd9947956970.jpg)
![91](https://user-images.githubusercontent.com/68511266/236621175-63a17bad-7ada-42c3-a7ed-4741d2734ec5.jpg)
![92](https://user-images.githubusercontent.com/68511266/236621177-135ca82f-799f-41da-ab72-2a275a5b86b8.jpg)
![93](https://user-images.githubusercontent.com/68511266/236621178-cdea35d1-43ed-4440-899f-43b7949f5467.jpg)
![94](https://user-images.githubusercontent.com/68511266/236621179-bb8c5b3a-9d07-4c48-8adb-fbcd73389594.jpg)
![95](https://user-images.githubusercontent.com/68511266/236621182-752db7fc-ee08-4f29-a0c0-8587726c085c.jpg)
![96](https://user-images.githubusercontent.com/68511266/236621184-ec9b95ca-f965-40fd-a0d2-196736809e83.jpg)
![97](https://user-images.githubusercontent.com/68511266/236621185-64e21eff-7e01-43f1-9319-a5b4f7728cb4.jpg)

https://user-images.githubusercontent.com/68511266/236621010-82b95a56-bf65-456e-84d2-5831d83cf5e3.mp4

This is my dataset for videos and frames it is not showing any output so when I try to run with video then I am getting the output as 'broccoli' as the predicted class name instead of 'mango' class  and I need number of rows, number of columns and total number of crops for videos on yolov8 model and also need id, class name and confidence score for videos on yolov8 model this my requirements I have tired alot but couldn't find any solution so kindly give me the solution
@glenn-jocher

**Comment by anut123** [comment]
![0](https://github.com/ultralytics/ultralytics/assets/68511266/a8135356-e2e9-47c2-a114-ffba82e1db29)

https://github.com/ultralytics/ultralytics/assets/68511266/e983c1a3-58e8-43c6-8774-fc2ae183e55a

I need number of rows, number of columns and total number of crops for videos on yolov8 model this my requirements I have tired alot but couldn't find any solution so kindly give me the solution

@glenn-jocher

**Comment by glenn-jocher** [comment]
@anut123 hello! Thank you for reaching out to us. To obtain the number of rows, number of columns, and total number of crops for videos using the YOLOv8 model, you will need to modify the predict.py file. You can access this metadata using the detect() method in the YOLOv8 class. Specifically, you can modify the 'app.py' file in the 'demo' directory to output the metadata fields you need.

To do this, you can add additional variables to hold the number of rows, number of columns, and total number of crops, and then update these variables during the detection process using the detect() method. Once you have these variables, you can output them as needed.

We hope this helps! If you have any additional questions or concerns, please don't hesitate to ask.

**Comment by anut123** [comment]
trigger line object counting issue in a row if 8 crops are there then it is counting 10  i mean it is counting 2 crops extra  in yolov8 modeI have tired alot but couldn't find any solution so kindly give me the solution 
code -
 if center[1]==(cy1+100):
            crops_count+=1

@glenn-jocher

**Comment by glenn-jocher** [comment]
@anut123 hello! It sounds like you are experiencing an issue with object counting in YOLOv8. Without more context, it is difficult to determine the cause of the issue. However, it may be helpful to check if there are any overlapping or closely spaced objects in the row, as this can affect the count. Additionally, it may be helpful to review the code snippet you provided to ensure that the if statement is properly capturing the center of the crop and that there are no issues with the values you are using for cy1 and center[1]. 

If these steps do not resolve the issue, please provide more information, such as a full code sample and any additional details about the data and detection process, so that we can better assist you. Thanks!
