### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by aymeric75** [ultralytics/ultralytics#3330]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when running:

`yolo task=detect mode=train model=yolov8n.pt data=custom.yaml epochs=1`

I get:
```

File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 239, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/v8/detect/train.py", line 54, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/v8/detect/train.py", line 28, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/data/dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/data/base.py", line 72, in __init__
    self.labels = self.get_labels()
  File "/root/anaconda3/envs/yolo8/lib/python3.9/site-packages/ultralytics/yolo/data/dataset.py", line 132, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)
```

### Environment

Ubuntu 20

Yolo8

Conda

### Minimal Reproducible Example

custom.yaml
```

path: '/workspace/latplan/yolo/'
train: "/workspace/latplan/yolo/train"
test: "/workspace/latplan/yolo/test"
val: "/workspace/latplan/yolo/val"
#Classes
nc: 1 # replace according to your number of classes

#classes names
#replace all class names list with your classes names
names: ['topPin']


```

on the same location as the custom.yaml, I have 3 folders: **train**, **test**, and **val**

In each I have **images** and **labels** folders

In images folder I have png images and in labels folders I have txt files (the labels)

Here is a sample of a label file

```

15 0.652344 0.655093 0.024479 0.030556
15 0.513021 0.615741 0.021875 0.027778
15 0.468490 0.614815 0.019271 0.035185
15 0.423438 0.616667 0.018750 0.040741
15 0.224740 0.615278 0.017188 0.036111
15 0.184375 0.621759 0.019792 0.036111
15 0.150260 0.619907 0.015104 0.032407
15 0.131510 0.627315 0.022396 0.047222
15 0.101302 0.625463 0.018229 0.034259
15 0.076042 0.619907 0.011458 0.030556
15 0.070833 0.633796 0.020833 0.036111
15 0.044531 0.630556 0.014063 0.035185
15 0.019531 0.631019 0.019271 0.026852

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aymeric75** [comment]
...

**Comment by glenn-jocher** [comment]
@aymeric75 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Laughing-q** [comment]
@aymeric75 your labels looks incorrect, it seems you only got 1 category but the indices are `15` in your label file.

**Comment by assia855** [comment]
Hi @aymeric75 I got the same error here's the format of my label:
```
0 3294.0 1831.0 3293.2360679774997 1833.3511410091699 3291.2360679774997 1834.8042260651805
0 3325.0 1830.0 3324.0450849718745 1832.9389262614623 3321.5450849718745 1834.7552825814757 
0 3295.0 1846.0 3294.0450849718745 1848.9389262614623 3291.5450849718745 1850.7552825814757
```
How can I solve that please?

**Comment by assia855** [comment]
Thanks for your reply @glenn-jocher  actually I'm trying to segment and the 7 values correspond to polygon coordinates and I found out that I didn't normalize at the end the values by dividing them by height and width like that: 
```
for i in polygon_coords:
      out = f"{i[0]/w} {i[1]/h} 
```

**Comment by glenn-jocher** [comment]
Hello @assia855, 

I see what you're trying to accomplish! YOLOv8 certainly supports segmentation. However, for this, we employ bounding boxes instead of polygons. The label format YOLOv8 expects involves a simpler structure i.e., class index followed by x, y, width, and height. These represent the center of the bounding box and its dimensions.

Your current approach with multiple points for polygons does not align with the model's expected input. You would need to convert your polygon coordinates into bounding box format. To accomplish this, you could determine the minimum and maximum x and y coordinates of your polygon to generate a bounding box. Once you have this box, compute the center by adding the minimum and maximum values and dividing by 2 for both x and y. The width would be `max_x - min_x` and the height would be `max_y - min_y`. Don't forget to normalize these values by dividing by the width and height of the image.

Hope this helps you in resolving the issue!

**Comment by hecheng000** [comment]
![8b0b5b188cb6bf1e8cf730bb717d503a](https://github.com/ultralytics/ultralytics/assets/116163624/39c41586-a9f8-4b30-b51f-3196d2aada96)

**Comment by hecheng000** [comment]
This is my label, and it has the same mistake

**Comment by hecheng000** [comment]
![Uploading 8b0b5b188cb6bf1e8cf730bb717d503a.JPG…]()
This is my label, and it has the same mistake

**Comment by glenn-jocher** [comment]
@hecheng000 hello! Your error 'ValueError: not enough values to unpack' generally occurs when you're trying to unpack more values than those available in the iterable. 

In the context of YOLOv8, this likely means that there is an issue with the format of the labels in your dataset. The format of each line in your label file should be `<object-class> <x> <y> <width> <height>`. All the values should be normalized, meaning they should be between 0 and 1.

1. `object-class` is an integer representing the index of the object from 0 to (classes-1)
2. `x`, `y` is the center of the box, also normalized by image dimensions
3. `width`, `height` are the width and height of the box, also normalized by image dimensions

It would be helpful to check your label to make sure they adhere to this format.

**Comment by hecheng000** [comment]
I normalized the data set between 0 and 1 and I got the same error
















At 2023-11-01 20:09:12, "Glenn Jocher" ***@***.***> wrote:

@hecheng000 hello! Your error 'ValueError: not enough values to unpack' generally occurs when you're trying to unpack more values than those available in the iterable.

In the context of YOLOv8, this likely means that there is an issue with the format of the labels in your dataset. The format of each line in your label file should be <object-class> <x> <y> <width> <height>. All the values should be normalized, meaning they should be between 0 and 1.

object-class is an integer representing the index of the object from 0 to (classes-1)
x, y is the center of the box, also normalized by image dimensions
width, height are the width and height of the box, also normalized by image dimensions

It would be helpful to check your label to make sure they adhere to this format.

**Comment by glenn-jocher** [comment]
@hecheng000 hello! If you're still encountering the 'ValueError: not enough values to unpack' error despite normalizing, then the error may be due to the structure of your dataset rather than the values themselves. Please ensure that each line in your label file follows the format `<object-class> <x> <y> <width> <height>`. Here's what each of these values represent:

1. `object-class`: This is an integer that represents the index of the object, ranging from 0 to (classes-1).
2. `x` and `y`: These values represent the center of the bounding box, and should be normalized by the image dimensions.
3. `width` and `height`: These represent the width and height of the bounding box, and they too should be normalized by the image dimensions.

In simpler words, all values should be floating-point numbers within [0.0, 1.0] range, and each line should contain exactly 5 values. If any line in your label files doesn't adhere to this format, that could be the cause of your error. Hence, make sure your label files follow this format.

**Comment by KingAsperin** [comment]
I have the same issue here i want to use yolov8 for keypoints detection bu it is giving me this error

ValueError: not enough values to unpack (expected 3, got 0)


and here is my labe.. i have a bounding box and 24 keypoints on my annotation. i hope you can help me

0 0.3529265873015873 0.33548280423280424 0.6245039682539683 0.41104497354497355 0.051587301587301584 0.2820767195767196 0.1810515873015873 0.24537037037037038 0.30282738095238093 0.23412698412698413 0.36408730158730157 0.2466931216931217 0.43874007936507936 0.25595238095238093 0.4816468253968254 0.28273809523809523 0.5431547619047619 0.30092592592592593 0.5711805555555556 0.34523809523809523 0.5381944444444444 0.3921957671957672 0.4749503968253968 0.3921957671957672 0.4126984126984127 0.41865079365079366 0.2378472222222222 0.4176587301587302 0.046875 0.30423280423280424 0.05555555555555555 0.29398148148148145 0.0873015873015873 0.30456349206349204 0.16468253968253968 0.31845238095238093 0.17261904761904762 0.2943121693121693 0.328125 0.13723544973544974 0.34771825396825395 0.1574074074074074 0.36160714285714285 0.18518518518518517 0.36086309523809523 0.21891534391534392 0.6587301587301587 0.2328042328042328 0.46081349206349204 0.4540343915343915 0.23883928571428573 0.49173280423280424

**Comment by glenn-jocher** [comment]
@KingAsperin hey there! 🌟 It looks like you're diving into some advanced usage of YOLOv8 for keypoint detection - that's awesome! From the error you're encountering, it seems there might be a slight mismatch in the expected format for your labels or the way the keypoints are being processed.

For YOLOv8 to correctly unpack your data, each label file should strictly follow the format required for the task at hand. Since you're working with keypoints, ensure that your label format aligns with YOLOv8's expectations for such tasks. Typically, for bounding boxes, YOLO expects `<class> <x_center> <y_center> <width> <height>`, all normalized to `[0, 1]`. For keypoints, additional normalized `<x> <y>` pairs are appended after the bounding box info.

Given your description, it seems you have the right idea but let's double-check:
- Ensure each keypoint pair `<x> <y>` is normalized and correctly placed in the sequence after the bounding box info.
- Verify there's no extra or missing data for each annotated object.

Your YAML configuration looks good, focusing on the keypoints setup. If the issue persists, it might be helpful to review a smaller subset of your dataset to ensure the format is consistently applied.

If you could share a bit more about how you're processing or generating these label files, we might be able to pinpoint the issue more directly. Sometimes, a fresh pair of eyes on the preprocessing script can catch something that's easy to overlook. 

Keep up the great work, and I'm here to help you get past this hurdle! 🚀

**Comment by KingAsperin** [comment]
@glenn-jocher 

I appreciate your thorough instructions, which proved immensely helpful in troubleshooting my issue.

Upon careful examination, I identified the root cause of the problem. It appears that all my data and YAML configurations are accurate. The sole discrepancy lies in the train.cache. After deleting the train.cache file and rerunning the program, the training process initiated successfully, and the model training commenced as expected.

Thank you once again for your guidance.

**Comment by glenn-jocher** [comment]
@YSA-github hey there! 🌟 It sounds like you're on the right track with your annotations. If you're using rectangular boxes and not keypoints, your label files should be just fine with the format `<class> <x_center> <y_center> <width> <height>`, all normalized to `[0, 1]`.

If you're encountering issues, a common culprit can be the cache files. Try deleting any `.cache` files in your dataset directory and rerun your training command. This forces YOLOv8 to re-read your dataset and often clears up any discrepancies.

Also, ensure your `custom.yaml` paths for train, val, and test are correctly pointing to your dataset. If the problem persists, could you share a snippet of your label file? Sometimes a quick look can help spot any formatting issues.

Looking forward to getting you past this hurdle! 🚀

**Comment by YSA-github** [comment]
@glenn-jocher 
Thank you very much for your answer, I've also deleted the .cache file, but I'm still confused about how kpt_shape assign values.
There is a snippet of my label file.I'm really looking forward to your guidance!
![屏幕截图 2024-03-01 120152](https://github.com/ultralytics/ultralytics/assets/91165861/0fa90b06-d1c8-4024-84af-d01bc9bca2a0)

**Comment by glenn-jocher** [comment]
@YSA-github hey there! 🌞 I'm glad to hear you've cleared the cache. Regarding `kpt_shape`, it's used to define the shape of your keypoints array. For instance, if you have 24 keypoints and each keypoint has 2 dimensions (x, y), you'd set `kpt_shape: [24, 2]` in your YAML file. This tells YOLOv8 how to interpret the keypoints in your label files.

Your label file should then follow the format: `<class> <x_center> <y_center> <width> <height> <kpt1_x> <kpt1_y> ... <kpt24_x> <kpt24_y>`, with all values normalized to `[0, 1]`.

If you're still facing issues, ensure each keypoint pair is correctly placed and normalized in your label files. Sometimes, a small typo can throw things off. Keep up the great work, and don't hesitate to reach out if you have more questions!

**Comment by YSA-github** [comment]
@glenn-jocher 
Thank you very much for your guidance again. When I don't have a keypoint, how to set the kpt_shape? I'm really looking forward to your guidance!

**Comment by glenn-jocher** [comment]
@YSA-github You're welcome! If you're not using keypoints, you can simply omit the `kpt_shape` from your YAML configuration. YOLOv8 will default to handling just the bounding boxes without expecting any keypoints. Keep up the great work, and feel free to reach out if you have more questions! 🚀

**Comment by Lotfi-MERAD** [comment]
The problem is in the label file; at the end, there is a blank line that needs to be removed.
![Sans titre](https://github.com/ultralytics/ultralytics/assets/60255295/fed48251-c40a-469c-a1d4-ee7b2d765ef9)

**Comment by glenn-jocher** [comment]
Hi @Lotfi-MERAD,

Thank you for pointing that out! Indeed, a blank line at the end of the label file can cause issues during training. Removing any extraneous lines or characters from your label files should resolve this problem.

If you continue to experience issues, please ensure you're using the latest versions of `torch` and `ultralytics`. You can update them using:
```bash
pip install --upgrade torch ultralytics
```

If the problem persists, could you provide a minimal reproducible example? This will help us investigate further. You can find guidelines for creating one here: https://docs.ultralytics.com/help/minimum_reproducible_example.

Thanks for your cooperation, and happy training! 🚀

**Comment by zxm-a11y** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/156500479/593de86f-555b-466c-82b0-a0942d4db756)
@glenn-jocher hi! This problem also occurs when I use yolov8-pose for keypoint detection. I have cleared the cache, but this error still occurs

**Comment by zxm-a11y** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/156500479/25bbe083-aae5-4977-879c-d9f336591e12)
![image](https://github.com/ultralytics/ultralytics/assets/156500479/c2798018-6050-4807-8499-26c4ff2f2100)
@glenn-jocher

**Comment by zxm-a11y** [comment]
please help me!!!! @glenn-jocher

**Comment by Lotfi-MERAD** [comment]
@zxm-a11y remove blank line 
![blank line](https://github.com/ultralytics/ultralytics/assets/60255295/e9c7b239-5e2a-4c84-b7ef-f74c6e89e442)

**Comment by zxm-a11y** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/156500479/c1d9e3b5-7d64-49fb-93f9-8eee2869d4ad)
There are still mistakes @Lotfi-MERAD

**Comment by Taylorblue123** [comment]
@glenn-jocher Hi Glenn-other, I also encountered a similar issue, but there are some differences. 

### The issue I am encountered with:
![image](https://github.com/user-attachments/assets/ce07baa4-3c46-4f14-9e68-3a2d951213c2)
![image](https://github.com/user-attachments/assets/3b755bd5-062e-4ad7-96e4-eb9192a66ea5)

It warns me that：
train: WARNING ⚠️ /content/FactoryVision2/generated/yolo_data/images/train/2023-06-26 21_30_19_073.jpg: ignoring corrupt image/label: cannot identify image file '/content/FactoryVision2/generated/yolo_data/images/train/2023-06-26 21_30_19_073.jpg'
train: WARNING ⚠️ No labels found in /content/FactoryVision2/generated/yolo_data/labels/train.cache. See https://docs.ultralytics.com/datasets for dataset formatting guidance.

And it throws an error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> [<ipython-input-55-389cabc3e204>](https://bt2gh6m81tg-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240729-060216_RC00_657091656#) in <cell line: 7>()
>       8 
>       9     # Train the model
> ---> 10     model.train(data=dataset, epochs=50, imgsz=640, device=device, project=MLFLOW_PROJECT)
>      11 
>      12     # Run and log the test set
> 
> 9 frames
> [/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py](https://bt2gh6m81tg-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240729-060216_RC00_657091656#) in get_labels(self)
>     160         # Check if the dataset is all boxes or all segments
>     161         lengths = ((len(lb["cls"]), len(lb["bboxes"]), len(lb["segments"])) for lb in labels)
> --> 162         len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
>     163         if len_segments and len_boxes != len_segments:
>     164             LOGGER.warning(
> 
> ValueError: not enough values to unpack (expected 3, got 0)

_It seems to be caused by corrupt images and labels, but after careful checking for both path and file, I found that both image and label files are not corrupt and can be opened successfully on collab._

### Additional information:

1. My code for running:
![image](https://github.com/user-attachments/assets/6c23c63d-fb5c-44a7-afd1-2893d414405a)

2. My data folder and dataset folder:
I store the dataset for training in generated/yolo_data

![image](https://github.com/user-attachments/assets/0284b3ab-010d-4b7d-a57b-6dc6cd8e9b68)
<img width="590" alt="image" src="https://github.com/user-attachments/assets/084615f7-563e-4264-8e57-ec07753e3b7b">

3. An example of my labels file:
![image](https://github.com/user-attachments/assets/8fdbeff4-dcbe-4b20-8356-c2aa313ffbbb)

4. My custom_yolo.yaml 
<img width="488" alt="image" src="https://github.com/user-attachments/assets/91f0b124-925a-483b-bc5b-11fbb97e06f7">


It is so weird that I could open any image files successfully by clicking or downloading (I am training on colab), but when I try to debug it with the following code - try to open an image by image.open(path) -, it throws error:
<img width="881" alt="image" src="https://github.com/user-attachments/assets/59dadd56-c09e-48d6-8eb2-3dd3f4dcb273">
_BUT I CAN FIND THIS IMAGE FILE AND OPEN IT BY CLICKING OR DOWNLOADING, it turns out to be an uncorrupt image_

**Comment by glenn-jocher** [comment]
@Taylorblue123 it looks like you're encountering issues with corrupt images or labels during training. Even if the images open correctly outside the training script, they might still have metadata or format issues that cause problems during processing. Ensure all images are in a supported format (e.g., JPEG, PNG) and that labels are correctly formatted without extra lines or characters.

To further diagnose, try running the latest versions of `torch` and `ultralytics` to ensure compatibility. If the issue persists, consider re-encoding the images using an image processing tool to eliminate any hidden corruptions.

For more detailed guidance, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/guides/yolo-common-issues/).

**Comment by octo-syakovenko** [comment]
The rootcause is that some label files have all labels outside of image, this is a bug indeed.

**Comment by glenn-jocher** [comment]
@octo-syakovenko thank you for identifying the issue. Please ensure that all label coordinates are within the image boundaries to avoid this error. If you need further assistance, feel free to ask.
