### ISSUE TITLE
Instance Segmentation Prediction Looks Slow.

### ISSUE THREAD

**Issue by jitaxis** [ultralytics/ultralytics#425]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I am running the following code:
` import numpy as np
import cv2 # OpenCV library
from ultralytics import YOLO
import gc
import torch
import time

gc.collect()
torch.cuda.empty_cache()

img_path = "/ssd/images/test_crop.png"

#Load a model
model = YOLO("/ssd/yolov8_dev/weights/230117-best-60ep.pt")  # load a pre-trained model
model.to(device=0)

def main():
    # cv2.imnread()
    tp=time.perf_counter()
    results = model.predict(img_path,return_outputs=True,show=True,imgsz=640,conf=0.65,iou=0.5,max_det = 5)  # predict on an image
    print(f"<<<<<<<<<<<<< IS prediction Time elapsed: ", (time.perf_counter() - tp)," >>>>>>>>>>>>>>>>") # CPU seconds elapsed (floating point)

if __name__ == "__main__":
    main()`
    
 The output is as follows:
`Ultralytics YOLOv8.0.6 🚀 Python-3.8.10 torch-1.11.0+cu113 CUDA:0 (Quadro RTX 3000, 5935MiB)
Fusing layers... 
YOLOv8s-seg summary: 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs
<<<<<<<<<<<<< IS prediction Time elapsed:  0.24524189298972487  >>>>>>>>>>>>>>>>`

245ms seems slow, is there a particular reason? and am I able to speed this up?

**Comment by AyushExel** [comment]
@jitaxis hey currently return_result=True will slow down the process but it's been fixed in this PR which'll be available soon
https://github.com/ultralytics/ultralytics/pull/314

**Comment by jitaxis** [comment]
I pulled the latest repo, with the changes and the speed hasn't changed and I don't know how to access the results.
My output using pretty much the same code as above is as follows:
`Ultralytics YOLOv8.0.7 🚀 Python-3.8.10 torch-1.11.0+cu113 CUDA:0 (Quadro RTX 3000, 5935MiB)
Fusing layers... 
YOLOv8s-seg summary: 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs
<<<<<<<<<<<<< IS prediction Time elapsed:  0.25353596300010395  >>>>>>>>>>>>>>>>
[Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Results'> instance
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([1, 6])
dtype: torch.float32
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Masks'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([1, 640, 640])
dtype: torch.float32
original size: (471, 465)`

But now I am just print the the results variable

> @jitaxis hey currently return_result=True will slow down the process but it's been fixed in this PR which'll be available soon #314

**Comment by Laughing-q** [comment]
@jitaxis hi, you can read more info from the predict page of our docs. [https://docs.ultralytics.com/predict/](https://docs.ultralytics.com/predict/)

**Comment by jitaxis** [comment]
> @jitaxis hi, you can read more info from the predict page of our docs. https://docs.ultralytics.com/predict/

After the prediction is made I followed the steps on the doc by trying to `print (results.masks.masks)` and `print (results.boxes[0].xyxy)` and get the following error:
`AttributeError: 'list' object has no attribute 'masks'` and `AttributeError: 'list' object has no attribute 'boxes'`

**Comment by Laughing-q** [comment]
@jitaxis results is a list which you could access the masks and boxes like this:
```python
for result in results:
    boxes = results.boxes # Boxes object for bbox outputs
    masks = results.masks # Masks object for segmenation masks outputs
    probs = results.probs # Class probabilities for classification outputs
```

**Comment by jitaxis** [comment]
Thanks, that was a stupid mistake on my end. I appreciate the help. Any idea why the speed is still around 260ms for the whole prediction and results? The actual inference time is fast when I do it in the Command Line more like 20-30ms

**Comment by AyushExel** [comment]
@jitaxis how are you getting the time 260ms? Can it be the combined time for all images in your source or is it the time for individual images? Ideally the inference time now should be same for both cli and python

**Comment by jitaxis** [comment]
Im running this exact code:

```
#!/usr/bin/env python3

import numpy as np
import cv2 # OpenCV library
from ultralytics import YOLO
import gc
import torch
import time

gc.collect()
torch.cuda.empty_cache()

img_path = "/ssd/images/test_crop.png"

# Load a model
model = YOLO("/ssd/weights/230117-best-60ep.pt")  # load a pretrained model
model.to(device=0)


def main():
    img = cv2.imread(img_path)
    tp=time.perf_counter()
    results = model.predict(img,show=False,imgsz=640,conf=0.65,iou=0.5,max_det = 5, save=False)  # predict on an image
    print(f"<<<<<<<<<<<<< IS prediction Time elapsed: ", (time.perf_counter() - tp)," >>>>>>>>>>>>>>>>") # CPU seconds elapsed (floating point)
    # results = results.cuda().cpu().to("cpu").numpy()
    masks = results[0].masks.masks
    print (masks)
    # results = results.cuda()
    # results = results.cpu()
    # results = results.to("cpu")
    # results = results.numpy()


if __name__ == "__main__":
    main()
```
    
    And get the following output
    
   ```
Ultralytics YOLOv8.0.7 🚀 Python-3.8.10 torch-1.11.0+cu113 CUDA:0 (Quadro RTX 3000, 5935MiB)
Fusing layers... 
YOLOv8s-seg summary: 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs
<<<<<<<<<<<<< IS prediction Time elapsed:  0.35800018300000147  >>>>>>>>>>>>>>>>
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
```
         
When I run it in cli using:
        ` yolo task=segment mode=predict model='/ssd/weights/230117-best-60ep.pt' conf=0.25 source='/ssd/images/test_crop.png'`
         
     I get the output as follows:
     
```
Ultralytics YOLOv8.0.7 🚀 Python-3.8.10 torch-1.11.0+cu113 CUDA:0 (Quadro RTX 3000, 5935MiB)
  Fusing layers... 
  YOLOv8s-seg summary: 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs
  image 1/1 /ssd/Projects/Machine_Learning/yolov7_dev/images/test_crop.png: 640x640 1 Visible mask, 23.8ms
  Speed: 0.7ms pre-process, 23.8ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)
  Results saved to runs/segment/predict8
```

**Comment by AyushExel** [comment]
Your issues might have been resolved in the latest release please upgrade

**Comment by jitaxis** [comment]
> Your issues might have been resolved in the latest release please upgrade

Same outcome:
```
Ultralytics YOLOv8.0.9 🚀 Python-3.8.10 torch-1.11.0+cu113 CUDA:0 (Quadro RTX 3000, 5935MiB)
Fusing... 
YOLOv8s-seg summary: 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs
<<<<<<<<<<<<< IS prediction Time elapsed:  0.2539124610000272  >>>>>>>>>>>>>>>>
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
```

**Comment by jitaxis** [comment]
My git says I am up to date. Has 8.0.10 been pushed to the main branch?

**Comment by AyushExel** [comment]
You can use `pip install --upgrade ultralytics `

**Comment by jitaxis** [comment]
If I only do one prediction it is still the same, but I tried running the prediction multiple times and got the time for each. I got the following for 3 predictions:
```
<<<<<<<<<<<<< IS prediction Time elapsed: 0.24991373399996064 >>>>>>>>>>>>>>>>
<<<<<<<<<<<<< IS prediction Time elapsed: 0.042104829999971116 >>>>>>>>>>>>>>>>
<<<<<<<<<<<<< IS prediction Time elapsed: 0.03933751099998517 >>>>>>>>>>>>>>>>
```
So some reason the first prediction takes 200ms longer. Any thoughts as to why this might occur? But this is fine with me, thank you for your help the speed it what i think it should be now :)

**Comment by AyushExel** [comment]
@jitaxis first prediction calls model.fuse() that's why it takes time. you can manually call model.fuse() to avoid that
