### ISSUE TITLE
training interrupted with last.pt cannot be opened

### ISSUE THREAD

**Issue by tonychengchen** [ultralytics/ultralytics#7087]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I'm training my model with the code below:
```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("yolov8s.pt")
    results = model.train(
        data=r"classes.yaml",
        epochs=1000,
        batch=64,
        workers=2,
        patience=200,
        device=[1],
        cache=True,
        project="COPAPPLE_0208",
        privacy_mode=True
    )
```
However, after several epochs it raises this error:
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    75/1000      2.55G      1.039     0.7968      1.094         56        640: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 30.31it/s]
                   all          1          4       0.88          1      0.995      0.771
  0%|          | 0/1 [00:00<?, ?it/s]
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    76/1000      2.54G      1.057      0.834      1.055         84        640: 100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 31.25it/s]
                   all          1          4      0.751          1      0.995      0.771
  0%|          | 0/1 [00:00<?, ?it/s]
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    77/1000      2.55G      1.013     0.8719      1.037         65        640: 100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 31.25it/s]
                   all          1          4      0.772          1      0.995      0.746
Traceback (most recent call last):
  File "D:\Cheng.Chen\code\ultralytics_cjf\training.py", line 6, in <module>
    results = model.train(
  File "D:\Cheng.Chen\code\ultralytics_cjf\ultralytics\engine\model.py", line 338, in train
    self.trainer.train()
  File "D:\Cheng.Chen\code\ultralytics_cjf\ultralytics\engine\trainer.py", line 190, in train
    self._do_train(world_size)
  File "D:\Cheng.Chen\code\ultralytics_cjf\ultralytics\engine\trainer.py", line 385, in _do_train
    self.save_model()
  File "D:\Cheng.Chen\code\ultralytics_cjf\ultralytics\engine\trainer.py", line 433, in save_model
    torch.save(ckpt, self.last)
  File "D:\Cheng.Chen\code\ultralytics_cjf\ultralytics\utils\patches.py", line 77, in torch_save
    return _torch_save(*args, **kwargs)
  File "D:\Cheng.Chen\code\ultralytics_cjf\venv\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "D:\Cheng.Chen\code\ultralytics_cjf\venv\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "D:\Cheng.Chen\code\ultralytics_cjf\venv\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: File COPAPPLE_0208\train\weights\last.pt cannot be opened.

Process finished with exit code 1
```

I tried for 5 times and it keeps on raising this error: ```train\weights\last.pt cannot be opened.``` I also tried reproduce the dataset but still not working. I used to run the same training code several weeks ago without any issue. Don't know what happened recently. Please help me to check out this issue.

### Environment

Ultralytics YOLOv8.0.226 🚀 
Python-3.9.13 
torch-2.0.1+cu118 
CUDA:0 (NVIDIA RTX A4000, 16376MiB)
Setup complete ✅ (24 CPUs, 63.7 GB RAM, 1440.6/1863.0 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("yolov8s.pt")
    results = model.train(
        data=r"classes.yaml",
        epochs=1000,
        batch=64,
        workers=2,
        patience=200,
        device=[1],
        cache=True,
        project="COPAPPLE_0208",
        privacy_mode=True
    )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tonychengchen hello! It seems like you're encountering an issue where the `last.pt` checkpoint file cannot be opened during training. This problem usually indicates a permissions issue or that the file is being accessed or blocked by another process.

Here are a few things you could check:
1. Ensure that your project directory `COPAPPLE_0208` and subdirectories have proper write permissions.
2. Verify that no other process (like a previously interrupted training run) is accessing the file. 
3. Check your disk space to make sure there's enough room for saving checkpoints.
4. If you're running this on a shared system or server, ensure that no other user or process could be interfering with your file access. 

In the meantime, make sure you're using the latest version of YOLOv8 and review any system or environment changes that might have occurred since the last successful training session.

Feel free to open an issue with detailed error logs on our Ultralytics YOLOv8 repo if the problem persists. The team is always here to assist! 😊💻🛠️

**Comment by tonychengchen** [comment]
> @tonychengchen hello! It seems like you're encountering an issue where the `last.pt` checkpoint file cannot be opened during training. This problem usually indicates a permissions issue or that the file is being accessed or blocked by another process.
> 
> Here are a few things you could check:
> 
> 1. Ensure that your project directory `COPAPPLE_0208` and subdirectories have proper write permissions.
> 2. Verify that no other process (like a previously interrupted training run) is accessing the file.
> 3. Check your disk space to make sure there's enough room for saving checkpoints.
> 4. If you're running this on a shared system or server, ensure that no other user or process could be interfering with your file access.
> 
> In the meantime, make sure you're using the latest version of YOLOv8 and review any system or environment changes that might have occurred since the last successful training session.
> 
> Feel free to open an issue with detailed error logs on our Ultralytics YOLOv8 repo if the problem persists. The team is always here to assist! 😊💻🛠️

Thanks for the advice! I have tested several datasets regarding this issue:
1. 5,000+ images with GPU training, approximately 10s/epoch, no this issue
2. 200 images with GPU training, faster than 1s/epoch, raised this issue
3. 200 images with CPU training, approximately 90s/epoch, no this issue

So I was wondering that will it be the epoch time too short to trigger this issue? So fast for each epoch that the ```last.pt``` file is on both writing and reading?

**Comment by glenn-jocher** [comment]
Hello @tonychengchen! It's interesting that the issue seems to be related to the training speed. When epochs are very fast, there could indeed be a race condition where the file system has not yet finished writing the `last.pt` file before a new save attempt is made. Here's what you can consider:

1. Add a slight delay or synchronization mechanism if epochs complete very quickly, to allow file I/O operations to finish properly.
2. Ensure that the disk write speed is not a bottleneck for your system.
3. As a temporary fix, you might try reducing the frequency of checkpoint saving if that's an option.

Remember to keep your YOLOv8 version up to date and consider system performance. Reach out with an issue on the Ultralytics YOLOv8 repo for further analysis if needed. 🚀

**Comment by tonychengchen** [comment]
> Hello @tonychengchen! It's interesting that the issue seems to be related to the training speed. When epochs are very fast, there could indeed be a race condition where the file system has not yet finished writing the `last.pt` file before a new save attempt is made. Here's what you can consider:
> 
> 1. Add a slight delay or synchronization mechanism if epochs complete very quickly, to allow file I/O operations to finish properly.
> 2. Ensure that the disk write speed is not a bottleneck for your system.
> 3. As a temporary fix, you might try reducing the frequency of checkpoint saving if that's an option.
> 
> Remember to keep your YOLOv8 version up to date and consider system performance. Reach out with an issue on the Ultralytics YOLOv8 repo for further analysis if needed. 🚀

Yeah, I solved this issue after I set the save_period=10. Thanks!

**Comment by tonychengchen** [comment]
Issue solved.

**Comment by glenn-jocher** [comment]
@tonychengchen great to hear the issue is resolved! If you have any more questions in the future, don't hesitate to reach out. Happy training! 😊🎉

**Comment by psaxton** [comment]
I am experiencing this issue as well. I believe it is being caused by anti-virus software not finishing the scan of the previous _last.pt_ when yolo is trying to write the new one. Setting `save_period=10` does not resolve the issue when running from the cli as it continues to save _last.pt_ on each epoch. This is particularly problematic when training yolov8n against a smallish dataset.

I'll submit a PR to add a back-off retry to the save function that fixes the issue on my machine.
