### ISSUE TITLE
Yolov8-World export onnx

### ISSUE THREAD

**Issue by shituo123456** [ultralytics/ultralytics#8371]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/64970397/ab8a02fb-a104-4349-bde9-75675dfbd820)

![image](https://github.com/ultralytics/ultralytics/assets/64970397/b5797275-c9da-44e7-8802-f8cabad6f41b)

Exporting onnx using yolov8-world failed
Look forward to reply. thanks a lot.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shituo123456 hi there! 👋 It looks like you're encountering an issue with exporting YOLOv8-World to ONNX format. To better assist you, could you please share the command you used to export the model? Additionally, if there are any error messages, kindly include the full text or screenshots of them. This information will help us pinpoint the issue and provide a more accurate solution.

In the meantime, here's a general example of how to export a YOLOv8 model to ONNX:

```bash
yolo export model=yolov8-world.pt format=onnx
```

Make sure you're using the latest version of the Ultralytics repository, as updates often include fixes and improvements. If the issue persists, we're here to help! 🛠️

**Comment by shituo123456** [comment]
Thanks for your reply. The following is the running command and error message.

yolo export model=yolov8s-world.pt format=onnx

Ultralytics YOLOv8.1.16 🚀 Python-3.8.18 torch-1.9.1+cu111 CPU (Intel Xeon Silver 4216 2.10GHz)
YOLOv8s-world summary (fused): 211 layers, 13372904 parameters, 0 gradients, 71.2 GFLOPs

PyTorch: starting from 'yolov8s-world.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (25.9 MB)

ONNX: starting export with onnx 1.15.0 opset 12...
ONNX: export failure ❌ 1.4s: Unsupported: ONNX export of operator adaptive_max_pool2d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/data_01/code/ultralytics-main/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/model.py", line 577, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 277, in __call__
    f[2], _ = self.export_onnx()
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 136, in outer_func
    raise e
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 131, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 363, in export_onnx
    torch.onnx.export(
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 982, in symbolic_fn
    return sym_help._onnx_unsupported(name + ', since output size is not factor of input size')
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 247, in _onnx_unsupported
    raise RuntimeError('Unsupported: ONNX export of operator {}. '
RuntimeError: Unsupported: ONNX export of operator adaptive_max_pool2d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.

onnx                      1.15.0
torch                     1.9.1+cu111  
torchaudio                0.9.1                  
torchvision               0.10.1+cu111          

The anticipation of your  response is greatly appreciated.

**Comment by glenn-jocher** [comment]
Hey @shituo123456, thanks for providing the detailed error log! It seems the issue is with the `adaptive_max_pool2d` operator during ONNX export, as the output size isn't a factor of the input size. This is a known limitation with ONNX's support for certain PyTorch operations.

As a quick workaround, you might want to try adjusting your model's architecture to avoid using `adaptive_max_pool2d` or modify the layer to have an output size that's a factor of the input size. If that's not feasible, another option is to wait for ONNX to support this operation in future releases or consider contributing to the ONNX community with a PR.

In the meantime, if you need to deploy your model urgently, you might want to explore other export formats that don't have this limitation, such as TorchScript or TensorRT, which might not face the same issue.

If you have any more questions or need further assistance, feel free to reach out. We're here to help! 🛠️

**Comment by glenn-jocher** [comment]
@Laughing-q hey do you think we might be able to get export support on these models or are the modules simply not supported by our export partners like ONNX?

**Comment by Laughing-q** [comment]
@glenn-jocher yes there's an operator `AdaptiveMaxPool2d` in the `ImagePoolingAttn` module that has not been supported in onnx.
https://github.com/ultralytics/ultralytics/blob/0572b294458524f3861bb4af6204150eaf47852b/ultralytics/nn/modules/block.py#L477

**Comment by shituo123456** [comment]
@Laughing-q hello

Another error was reported when I saved as person_yolov8s_world.pt and then exported onnx as follows
`from ultralytics import YOLO

# Initialize a YOLO-World model
model = YOLO('yolov8s-world.pt')  # or select yolov8m/l-world.pt

# Define custom classes
model.set_classes(["person"])

# Save the model with the defined offline vocabulary
model.save("person_yolov8s_world.pt")
`

`yolo export model=person_yolov8s——world.pt format=onnx`
Tensor:
(1,.,.) = 
 Columns 1 to 9  0.0150  0.0077  0.0137  0.0069  0.0004 -0.0283 -0.0278 -0.1049 -0.0197
Columns 10 to 18 -0.0002 -0.0111 -0.0108  0.0072  0.0106  0.0214  0.0292  0.0296  0.0285
Columns 19 to 27 -0.0213 -0.0083  0.0524  0.0288 -0.0005 -0.0107 -0.0323  0.0178  0.0088
Columns 28 to 36  0.0397 -0.0349  0.0250  0.0275 -0.0144 -0.0585  0.0062 -0.0103 -0.0327
Columns 37 to 45  0.0051  0.0051  0.0051 -0.0176 -0.0182 -0.0098  0.0013  0.0381  0.0197
Columns 46 to 54  0.0410 -0.0250  0.0292  0.0133  0.0328 -0.0207 -0.0202 -0.0035 -0.0009
Columns 55 to 63  0.0009 -0.0197 -0.0142  0.0242 -0.0284 -0.0002  0.0356 -0.0157  0.0297
Columns 64 to 72 -0.0037  0.0135 -0.0359 -0.0024 -0.0033  0.0074  0.0045  0.0282  0.0017
Columns 73 to 81  0.0083  0.0049 -0.0024  0.0149  0.0241  0.0126 -0.0161 -0.0373 -0.0155
Columns 82 to 90  0.0098 -0.0223  0.0415 -0.0089  0.0045  0.0184 -0.0280 -0.0080 -0.0254
Columns 91 to 99 -0.0056 -0.0110 -0.1582  0.0273  0.0142 -0.0041  0.0187  0.0065  0.0174
Columns 100 to 108  0.0136  0.0155  0.0151  0.0525  0.0030 -0.0014 -0.0063  0.0054 -0.0220
Columns 109 to 117  0.0025 -0.0402  0.0161 -0.0051  0.0039  0.0196  0.0413 -0.0304 -0.0122
Columns 118 to 126  0.0011 -0.0273 -0.0133 -0.0049 -0.0275 -0.0277 -0.0221 -0.0118 -0.0302
Columns 127 to 135  0.0148  0.0049 -0.0241  0.0416 -0.0074 -0.0123 -0.0216  0.5984  0.0112
Columns 136 to 144  0.0032 -0.0088 -0.0341  0.0125 -0.0305 -0.0012  0.0056 -0.0230  0.0083
Columns 145 to 153 -0.0307  0.0117 -0.0189  0.0046 -0.0093 -0.0174  0.0139  0.0108  0.0247
Columns 154 to 162 -0.0146 -0.0197 -0.0272 -0.0163  0.0028 -0.0164 -0.0138 -0.0309 -0.0120
Columns 163 to 171  0.0012 -0.0151  0.0065 -0.0073 -0.0056 -0.0144  0.0198 -0.0195  0.0013
Columns 172 to 180  0.0112 -0.0262  0.0153 -0.0171  0.0414 -0.0107  0.0124  0.0096 -0.0035
Columns 181 to 189  0.0050  0.0372  0.0118 -0.0153 -0.0504  0.0051  0.0041 -0.0064  0.0107
Columns 190 to 198 -0.0176 -0.0002 -0.0213  0.0130  0.0046 -0.0012  0.0257  0.0078  0.0126
Columns 199 to 207 -0.0041 -0.0268  0.0359 -0.0201 -0.0206  0.0129  0.0134  0.0091 -0.0034
Columns 208 to 216 -0.0060  0.0086  0.0046  0.0458  0.0566 -0.0044 -0.0014  0.0219  0.0090
Columns 217 to 225 -0.0203 -0.0130  0.0081 -0.0387 -0.0089 -0.0106 -0.0214  0.0003 -0.0332
Columns 226 to 234  0.0094 -0.0071  0.0125 -0.0112 -0.0192  0.0072  0.0059 -0.0186 -0.0199
Columns 235 to 243  0.0300  0.0004  0.0049  0.0061 -0.0080  0.0100  0.0106  0.0014  0.0130
Columns 244 to 252  0.0002 -0.0493 -0.0282 -0.0231  0.0243 -0.0075  0.0140 -0.0001 -0.0020
Columns 253 to 261  0.0446  0.0143 -0.0251 -0.0081 -0.0085 -0.0213  0.0066 -0.0244  0.0233
Columns 262 to 270 -0.0214  0.0116 -0.0156 -0.0361  0.0083  0.0327  0.0077  0.0036  0.0211
Columns 271 to 279 -0.0038 -0.0336  0.0244 -0.0248 -0.0013  0.0236  0.0307  0.0080  0.0108
Columns 280 to 288 -0.0111  0.0212 -0.0115  0.0206  0.0045  0.0032 -0.0002 -0.0117  0.0128
Columns 289 to 297 -0.0179 -0.0151  0.0174  0.0021  0.0086  0.0146  0.0053 -0.0095 -0.0316
Columns 298 to 306 -0.0062  0.0054 -0.0052  0.0262 -0.0132  0.0149  0.0133 -0.0049  0.0001
Columns 307 to 315 -0.0091  0.0125  0.0095  0.0207 -0.0033 -0.0010  0.5981 -0.0133 -0.0141
Columns 316 to 324  0.0435 -0.0330  0.0013  0.0310  0.0119  0.0272  0.0331  0.0309  0.0326
Columns 325 to 333 -0.0051  0.0246 -0.0031  0.0019  0.0040 -0.2171  0.0298  0.0323  0.0104
Columns 334 to 342 -0.0111 -0.0222  0.0417 -0.0099  0.0173 -0.0175 -0.0363  0.0273  0.0042
Columns 343 to 351  0.0336  0.0245  0.0020  0.0100 -0.0059  0.0282  0.0219 -0.0005 -0.0091
Columns 352 to 360  0.0093 -0.0153  0.0033 -0.0045  0.0406  0.0230 -0.0040 -0.0011 -0.0015
Columns 361 to 369  0.0372 -0.0189 -0.0290  0.0025  0.0037 -0.0160  0.0174  0.0238 -0.0053
Columns 370 to 378  0.0225  0.0049  0.0124  0.0013  0.0331  0.0063 -0.0025  0.0156  0.0236
Columns 379 to 387 -0.0394  0.0091 -0.0230  0.0101  0.0025 -0.0192  0.0170 -0.0260  0.0083
Columns 388 to 396  0.0059 -0.0051  0.0087 -0.0159 -0.0023  0.0289  0.0101  0.0012  0.0446
Columns 397 to 405 -0.0050 -0.0052 -0.0054  0.0562  0.0236  0.0072 -0.0007  0.0083  0.0049
Columns 406 to 414  0.0078  0.0178 -0.0042 -0.0112  0.0061  0.0174  0.0041  0.0100  0.0414
Columns 415 to 423 -0.0350  0.0114 -0.0142 -0.0028  0.0136  0.0159  0.0244  0.0005  0.0321
Columns 424 to 432 -0.0009  0.0093  0.0219 -0.0023 -0.0067  0.0078  0.0323 -0.0223 -0.0065
Columns 433 to 441 -0.0134  0.0030 -0.0006  0.0357  0.0035 -0.0072 -0.0228 -0.0079 -0.0141
Columns 442 to 450 -0.0036 -0.0223 -0.0138 -0.0109 -0.0179 -0.0360 -0.0041 -0.0052 -0.0028
Columns 451 to 459 -0.0034 -0.0092  0.0242  0.0347  0.0129  0.0404  0.0283 -0.0067 -0.0093
Columns 460 to 468 -0.0266  0.0033 -0.0110 -0.0019 -0.0031  0.0247 -0.0067  0.0229  0.0086
Columns 469 to 477  0.0097 -0.0065  0.0120 -0.0216  0.0246 -0.0107  0.0217  0.0402  0.0005
Columns 478 to 486 -0.0001  0.0102  0.0421 -0.0031 -0.0534  0.0160  0.0180 -0.0037 -0.0064
Columns 487 to 495  0.0208  0.0286  0.0068 -0.0374 -0.0072  0.0160 -0.0038  0.0445 -0.0059
Columns 496 to 504  0.0053  0.0304  0.0059 -0.0068  0.0281 -0.0268  0.0011  0.0094  0.0243
Columns 505 to 512  0.0168 -0.0297 -0.0217 -0.0348 -0.0296 -0.0235 -0.0191  0.0013
[ torch.FloatTensor{1,1,512} ]
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/data_01/code/ultralytics-main/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/model.py", line 577, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 277, in __call__
    f[2], _ = self.export_onnx()
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 136, in outer_func
    raise e
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 131, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/data/data_01/code/ultralytics-main/ultralytics/engine/exporter.py", line 363, in export_onnx
    torch.onnx.export(
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 458, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/data_01/code/ultralytics-main/ultralytics/nn/tasks.py", line 83, in forward
    return self.predict(x, *args, **kwargs)
  File "/data/data_01/code/ultralytics-main/ultralytics/nn/tasks.py", line 594, in predict
    txt_feats = self.txt_feats.to(device=x.device, dtype=x.dtype)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:

I eagerly anticipate your response. Thank you.

**Comment by Laughing-q** [comment]
@shituo123456 hi, 
For this error we'll need to add `detach()` when generating `txt_feats`:
https://github.com/ultralytics/ultralytics/blob/0572b294458524f3861bb4af6204150eaf47852b/ultralytics/nn/tasks.py#L573
```python
self.txt_feats = txt_feats.reshape(-1, len(text), txt_feats.shape[-1]).detach()
```
I noticed this issue before, but haven't fixed it to main branch since the export would fail even I fix it because of the above operator issue.
BTW actually I fixed it in the `yolo-world-training` branch I'm working on, and I'll also try to make some efforts to make the export work while implementing yolo-world training.

**Comment by shituo123456** [comment]
@Laughing-q hi.

yes, the detach() work was performed, an same error still occurred. I am looking forward to your subsequent optimization. Thank you very much.

**Comment by Laughing-q** [comment]
@shituo123456 hi! currently we've added yolo-world2 support, which can be smoothly export to onnx. I figured you might want to have a try! :)

**Comment by shituo123456** [comment]
@Laughing-q
hi. Thank you very much. I'll give it a try

**Comment by shituo123456** [comment]
@Laughing-q hi，Now the ultralytics model is based on CoCo training, can you provide the pretrain model in YOLO-World. Thank you so much

**Comment by Laughing-q** [comment]
@shituo123456 you can create your own model by:
```python
from ultralytics import YOLO

# Initialize a YOLO-World model
model = YOLO('yolov8s-worldv2.pt')  # or select yolov8m/l-world.pt

# Define custom classes
model.set_classes(["person", "bus"])

# Save the model with the defined offline vocabulary
model.save("custom_yolov8s.pt")
```
and then try to export your `custom.pt` model.
More info please check out our docs page: https://docs.ultralytics.com/models/yolo-world/#set-prompts

**Comment by shituo123456** [comment]
@Laughing-q hi. 
I mean yolov8-world in ultralytics is based on coco training.
1. Can we provide pre-training weights based on obj365 and lvis in Tencent project?
2. Or how to convert the weights of YOLO-World into the form of yolov8-world in ultralytics.
Thank you so much.
![image](https://github.com/ultralytics/ultralytics/assets/64970397/76719fb1-09b8-41ac-a744-e4b629239d7a)

**Comment by Laughing-q** [comment]
@shituo123456 they are based on obj365 and lvis... and also they are directly migrated weights from official YOLO-World repo. We just embedded the embedding of coco categories in it as default. Just try any other prompts you want.

**Comment by fatfishZhao** [comment]
Hi, is there any scripts to convert the official YOLO-World V2 checkpoints to this repo? Thanks.

**Comment by glenn-jocher** [comment]
@fatfishZhao hi there! 😊 It seems like you're right on track. When exporting to ONNX, dynamic dimensions can sometimes be produced depending on operations like `torch.cat`. To achieve a static output dimension, you might consider specifying the output dimensions explicitly if your application demands a fixed shape. However, note that ONNX and many consuming applications can work well with dynamic dimensions, especially for varying input sizes or batch sizes.

To explicitly set static dimensions during the export, you could try modifying the export call with `dynamic_axes` argument to restrict dynamic behavior only to necessary axes:

```python
torch.onnx.export(model, dummy_input, "model.onnx", 
                  opset_version=11,
                  input_names=['input'], 
                  output_names=['output'], 
                  dynamic_axes={'input': {0: 'batch_size'}, 
                                'output': {0: 'batch_size'}})
```

This tells ONNX to keep dynamic behavior for the batch size (axis 0), but you might need to adjust this based on your model's specifics.

Keep in mind, adjusting the model's code for output dimensions might require a deeper dive into its architecture and the specifics of your classes and detection boxes. If certain operations cause dynamic outputs and you need them static, ensuring the output shapes are explicitly managed within your model before export might be necessary.

Let us know how it goes or if you have more questions!
