### ISSUE TITLE
Counting based on different category 

### ISSUE THREAD

**Issue by NandiniLReddy** [ultralytics/ultralytics#8442]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I have been working on counting based on different types of fishes on a conveyer belt; 
This is the code that I have implemented; (Could You please help me resolve this error, and provide additional suggestions if I'm doing it in right way.)

`from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

# Define the categories you want to count
FISH_CATEGORIES = [0, 1, 2, 3, 4, 5, 6]  # Example: counting all fish categories

MODEL = f"{HOME}/runs/{task}/{train_nos}/weights/best.pt"
model = YOLO(MODEL)
cap = cv2.VideoCapture("/Desktop/Yolo-Video/videos/fish-video1.avi")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Define region points
region_points = [(750, 100), (750, 1500), (20, 1500), (20, 100)]  # Define a polygon with at least 4 points

# Video writer
video_writer = cv2.VideoWriter("object_counting_output.avi",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       fps,
                       (w, h))

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    # Model prediction
    results = model(im0)

    # Extract predictions from the results
    fish_detections = []
    for result in results:
        for detection in result.xyxy[0].numpy():
            # Check if the detected object belongs to the desired categories
            if int(detection[5]) in FISH_CATEGORIES:
                fish_detections.append(detection)

    # Perform object counting
    im0 = counter.start_counting(im0, fish_detections)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
`
While this is giving me errors like Result object has no attribute 'xyxy'; But, the code for In_count and Out_count is working well with the video as well.

**Comment by glenn-jocher** [comment]
@NandiniLReddy hi there! 👋 It looks like you're on the right track with your fish counting implementation. The error you're encountering is likely due to how you're accessing the detection results. The `Results` object returned by the `model(im0)` call contains the detections, but you'll need to access them correctly.

Here's a corrected snippet of your code:

```python
# Model prediction
results = model(im0)

# Extract predictions from the results
fish_detections = []
for det in results.pred[0]:  # Accessing the predictions
    # Check if the detected object belongs to the desired categories
    if int(det[5]) in FISH_CATEGORIES:
        fish_detections.append(det.cpu().numpy())  # Convert to numpy array
```

Make sure to replace `result.xyxy[0].numpy()` with `results.pred[0]` and then convert the tensor to a numpy array with `.cpu().numpy()` if needed.

Give this a try, and it should resolve the 'xyxy' attribute error. Keep up the great work! If you have any more questions or need further assistance, feel free to ask. Happy coding! 🐟🔍

**Comment by NandiniLReddy** [comment]
@glenn-jocher, Thank you very much for answering my question.
Though it resolves the error of 'xyxy' attribute, I have encountered another error which states:
`AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_555493/1928526996.py in <module>
     38 
     39     # Check if there are any predictions
---> 40     if len(results.pred) == 0:
     41         video_writer.write(im0)
     42         continue

AttributeError: 'list' object has no attribute 'pred'`

Although, Yolo-V8 gives accurate predictions; 
P.S: Starting of the video, the conveyor belt doesn't have any fish.

Let me know your thoughts.
Thank you!

**Comment by glenn-jocher** [comment]
Hi @NandiniLReddy, glad to hear the previous fix helped with the 'xyxy' error! 🎉

Regarding the new error, it seems like there's a slight mix-up in checking for predictions. The `results.pred` is indeed a list, where each element corresponds to predictions for an image. To check if there are predictions, you should look at the first element of this list. Here's a quick fix:

```python
# Check if there are any predictions for the first image in the batch
if len(results.pred[0]) == 0:
    video_writer.write(im0)
    continue
```

This should resolve the AttributeError you're encountering. Remember, the `results.pred[0]` is for the first (or only) image in the batch. If you're processing a batch of images, you'll need to iterate over `results.pred`.

Let me know if this helps or if you have any more questions. Keep up the great work! 🚀

**Comment by NandiniLReddy** [comment]
Hi @glenn-jocher, Still the error persists. Not sure what is wrong. 

`from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

FISH_CATEGORIES = [0, 1, 2, 3, 4, 5, 6]  

MODEL = f"{HOME}/runs/{task}/{train_nos}/weights/best.pt"
model = YOLO(MODEL)
cap = cv2.VideoCapture("fish-video1.avi")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

region_points = [(750, 100), (750, 1500), (20, 1500), (20, 100)] 


video_writer = cv2.VideoWriter("object_counting_output.avi",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       fps,
                       (w, h))

counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    results = model(im0)

    if len(results.pred[0]) == 0:
        video_writer.write(im0)
        continue

    fish_detections = []
    for det in results.pred[0]: 

        if int(det[5]) in FISH_CATEGORIES:
            fish_detections.append(det.cpu().numpy()) 

    im0 = counter.start_counting(im0, fish_detections)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
`

Error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_555493/3312751476.py in <module>
     38 
     39     # Check if there are any predictions
---> 40     if len(results.pred[0]) == 0:
     41         video_writer.write(im0)
     42         continue

AttributeError: 'list' object has no attribute 'pred'
`

**Comment by glenn-jocher** [comment]
Hi @NandiniLReddy, thanks for reaching out again! 😊 It looks like the issue is with accessing the predictions. In YOLOv8, the results from the model are stored in a `Results` object, and the predictions can be accessed using `results.pred`. However, your error suggests that `results` is being interpreted as a list, which shouldn't be the case.

Let's try a slightly different approach to ensure we're accessing the predictions correctly:

```python
results = model(im0)

# Ensure we have predictions before proceeding
if results.pred is not None and len(results.pred[0]) > 0:
    fish_detections = []
    for det in results.pred[0]:  # Iterate through detections
        if int(det[5]) in FISH_CATEGORIES:
            fish_detections.append(det.cpu().numpy())

    # Process detections
    im0 = counter.start_counting(im0, fish_detections)
    video_writer.write(im0)
else:
    # No detections, just write the original frame
    video_writer.write(im0)
```

This snippet checks if `results.pred` is not `None` and contains predictions before proceeding. If there are no detections, it simply writes the original frame to the video.

If you're still encountering issues, please ensure you're using the latest version of the Ultralytics YOLOv8 library, as the API might have been updated.

Hope this helps! Let me know if there's anything else I can assist you with. 🚀

**Comment by glenn-jocher** [comment]
@NandiniLReddy hey there! 🙌 It's no bother at all; we're here to help!

From what you've described, it seems like the model might not be detecting any objects, or there's an issue with how detections are being processed. Here are a couple of things you might want to check:

1. **Model Confidence Threshold**: Ensure the model's confidence threshold isn't set too high, which might prevent detections from being considered significant. You can adjust this with the `conf` parameter when calling the model, e.g., `results = model(im0, conf=0.25)`.

2. **Correct Model and Categories**: Double-check that the `MODEL` path is correct and the model is trained to detect the `FISH_CATEGORIES` you're interested in.

3. **Detection Processing**: The way detections are processed seems a bit off. You should directly access `results.pred[0]` for detections. Here's a simplified snippet:

```python
results = model(im0)
if len(results.pred[0]):
    fish_detections = [det.cpu().numpy() for det in results.pred[0] if int(det[5]) in FISH_CATEGORIES]
    if fish_detections:
        im0 = counter.start_counting(im0, fish_detections)
        video_writer.write(im0)
else:
    video_writer.write(im0)
```

This snippet checks for detections, filters them based on your categories, and then processes them if any are found.

Give these suggestions a try, and let's see how it goes! Feel free to reach out if you have more questions or need further assistance. Happy coding! 🚀

**Comment by NandiniLReddy** [comment]
Thank you @glenn-jocher; the code by Ultralytics works fine and the model is working as well; 
I ran the model for the sample image: and this is what the result consists of:[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: ultralytics.engine.results.Masks object
 names: {0: 'flounder-witch', 1: 'flounder-witch-bottom', 2: 'haddock', 3: 'hake-red', 4: 'hake-silver', 5: 'pollock', 6: 'redfish'}
 obb: None
 orig_img: array([[[26, 29, 27],
         [26, 29, 27],
         [26, 29, 27],
         ...,
         [18, 26, 26],
         [20, 28, 28],
         [21, 29, 29]],
 
        [[26, 29, 27],
         [24, 29, 27],
         [26, 29, 27],
         ...,
         [18, 26, 26],
         [19, 27, 27],
         [19, 27, 27]],
 
        [[22, 27, 26],
         [21, 27, 26],
         [22, 27, 26],
         ...,
         [17, 25, 25],
         [17, 25, 25],
         [17, 25, 25]],
 
        ...,
 
        [[ 1,  2,  0],
         [ 0,  1,  0],
         [ 0,  1,  0],
         ...,
         [ 0,  0,  1],
         [ 0,  0,  1],
         [ 1,  0,  2]],
 
        [[ 1,  2,  0],
         [ 0,  1,  0],
         [ 0,  1,  0],
         ...,
         [ 0,  0,  1],
         [ 0,  0,  1],
         [ 1,  0,  2]],
 
        [[ 1,  2,  0],
         [ 0,  1,  0],
         [ 0,  1,  0],
         ...,
         [ 0,  0,  1],
         [ 0,  0,  1],
         [ 1,  0,  2]]], dtype=uint8)
 orig_shape: (1536, 2048)
 path: '/content/fish11.jpeg'
 probs: None
 save_dir: 'runs/segment/predict'
 speed: {'preprocess': 1.0638236999511719, 'inference': 113.39712142944336, 'postprocess': 24.009227752685547}]

I couldn't access the results.pred for the image as well.

**Comment by NandiniLReddy** [comment]
Instead i have all the values required in here: 

```
results = model('/content/fish11.jpeg')  # return a list of Results objects

# View results
for r in results:
    print(r.boxes)
```
output: 
```
image 1/1 /content/fish11.jpeg: 480x640 1 flounder-witch, 35.7ms
Speed: 5.9ms preprocess, 35.7ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0.], device='cuda:0')
conf: tensor([0.9834], device='cuda:0')
data: tensor([[2.4658e+02, 5.5678e+02, 1.4732e+03, 1.0749e+03, 9.8342e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1536, 2048)
shape: torch.Size([1, 6])
xywh: tensor([[ 859.8949,  815.8619, 1226.6309,  518.1681]], device='cuda:0')
xywhn: tensor([[0.4199, 0.5312, 0.5989, 0.3373]], device='cuda:0')
xyxy: tensor([[ 246.5795,  556.7778, 1473.2103, 1074.9459]], device='cuda:0')
xyxyn: tensor([[0.1204, 0.3625, 0.7193, 0.6998]], device='cuda:0')
```

**Comment by glenn-jocher** [comment]
@NandiniLReddy hey there! 🙌 It looks like you've got everything you need from the `results` object. To access the attributes of the `Boxes` object, you can directly call them like so:

```python
results = model('/content/fish11.jpeg')

# Assuming you're working with a single image and want to access the first (and only) result
r = results[0]  # Get the first (and only) Results object

# Now you can access the Boxes object attributes directly
print("Class IDs:", r.boxes.cls)
print("Confidences:", r.boxes.conf)
print("Bounding Boxes (xywh):", r.boxes.xywh)
```

This will give you direct access to the class IDs, confidence scores, and bounding box coordinates in the format you're looking for. Keep up the great work, and if you have any more questions, feel free to ask! 🚀

**Comment by NandiniLReddy** [comment]
@glenn-jocher, my model is working fine; all the attributes are stored in results but for the code I have implemented, the output video doesn't contain any count or bounding box not the line which we defined.
Not sure what could be the problem.

**Comment by glenn-jocher** [comment]
@NandiniLReddy hey there! 🌟 It's great to hear your model is working fine and you're able to access all the attributes from the results. If the output video doesn't show any counts, bounding boxes, or the defined line, it might be related to how the drawing or counting logic is implemented in your code. 

Make sure you're correctly processing and drawing on the frames before writing them to the video. Here's a quick snippet to ensure bounding boxes are drawn:

```python
for box in r.boxes.xyxy:
    cv2.rectangle(im0, (int(box[0]), int(box[1])), (int(box[2]), int(box[3])), (255, 0, 0), 2)
```

And for adding counts or lines, ensure you're using `cv2.putText()` or `cv2.line()` appropriately on `im0` before `video_writer.write(im0)`.

If you're already doing this and still facing issues, double-check the coordinates and values being passed to these functions. Sometimes, a small oversight in coordinates or forgetting to update the frame (`im0`) before writing it can lead to such issues.

Hope this nudges you in the right direction! Keep experimenting, and don't hesitate to reach out if you have more questions. Happy coding! 🚀

**Comment by NandiniLReddy** [comment]
Hi @glenn-jocher, Thank you for your response; While I implemented the whole, but still not sure why I'm not getting the desired output that is the count of each category of the fish every time it is detected. I have attached the code as well, let me know if there are any mistakes or I'm I doing it correctly. 

```
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

FISH_CATEGORIES = [0, 1, 2, 3, 4, 5, 6] 

MODEL = "/content/best.pt"
cap = cv2.VideoCapture("/content/fish-video1.avi")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Define region points
region_points = [(750, 100), (750, 1500), (20, 1500), (20, 100)]  # Define a polygon with at least 4 points

# Video writer
video_writer = cv2.VideoWriter("COUNT-18.avi",
                       cv2.VideoWriter_fourcc(*'XVID'),
                       fps,
                       (w, h))

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=YOLO(MODEL).names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    # Model prediction
    results = YOLO(MODEL)(im0)

    # Ensure we have predictions before proceeding
    if isinstance(results, list) and len(results) > 0:
        for result in results:
            if result.boxes is not None:
                fish_detections = []
                for i in range(len(result.boxes.xyxy)):  # Iterate through bounding boxes
                    box = result.boxes.xyxy[i]
                    cls_index = int(box[-1])
                    if cls_index in FISH_CATEGORIES:
                        fish_detections.append(box.cpu().numpy())

                # Process detections if fish_detections is not empty
                if fish_detections:
                    # Draw bounding boxes
                    for box in result.boxes.xyxy:
                        cv2.rectangle(im0, (int(box[0]), int(box[1])), (int(box[2]), int(box[3])), (255, 0, 0), 2)

                    im0 = counter.start_counting(im0, fish_detections)

                    # Add counts for each class
                    for class_name, count in counter.counts.items():
                        text = f"{class_name}: {count}"
                        cv2.putText(im0, text, (10, 30 + 30 * YOLO(MODEL).names.index(class_name)), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

                    video_writer.write(im0)
    else:
        # No detections, just write the original frame
        video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()

```

**Comment by glenn-jocher** [comment]
@NandiniLReddy hi there! 👋 It looks like you've got a solid setup for counting and tracking fish categories in your video. Your approach seems correct, but there are a couple of things to ensure for optimal results:

1. **Model Predictions**: Make sure `YOLO(MODEL)(im0)` is correctly returning predictions. It's more efficient to initialize the model once outside the loop and then call it within the loop to avoid reloading the model on each frame.

2. **Drawing and Counting Logic**: Your drawing and counting logic inside the loop looks good. Just ensure that `counter.start_counting()` is correctly updating `im0` with the drawn bounding boxes and counts.

3. **Class Names and Counts**: When displaying counts, ensure `counter.counts` is being updated correctly. It might be helpful to print `counter.counts` to debug.

Here's a slight optimization to initialize the model once:

```python
model = YOLO(MODEL)  # Initialize the model once outside the loop

while cap.isOpened():
    # Your loop logic here
    results = model(im0)  # Use the initialized model
```

This should help with performance and ensure your model's predictions are being processed correctly. Keep up the great work, and let me know if there's anything else I can help with! 🚀

**Comment by NandiniLReddy** [comment]
Hi @glenn-jocher, thank you for your reply;
Though I have predictions from the model; which are accessed using the results variable. 
and but while executing, it is not even entering the `if isinstance(results, list) and len(results) > 0:` loop itself; It is just runs `results = model(im0) `and ends.
Not sure why? Can you share your thoughts about this.
Thank you !

**Comment by glenn-jocher** [comment]
@NandiniLReddy hi there! 😊 It looks like the issue might be related to how you're checking for predictions. The `results` object returned by YOLOv8 is not a list but a custom `Results` object. So, the condition `if isinstance(results, list) and len(results) > 0:` won't work as expected.

Instead, you can directly check if `results.boxes` is not empty. Here's a quick example:

```python
results = model(im0)
if results.boxes is not None and len(results.boxes.xyxy[0]) > 0:
    # Now you're inside the loop, and you can process your detections
    print("Detections found!")
else:
    print("No detections.")
```

This should help you enter the loop when there are detections. Let me know if this solves the issue or if you need further assistance! 🚀
