### ISSUE TITLE
Edit Object Counting Output to Terminal

### ISSUE THREAD

**Issue by Toshea111** [ultralytics/ultralytics#8547]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using a YOLOv8 object counting script, and am interested in changing the prediction output to the terminal.

The script is as follows:

```
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

model = YOLO("C://Users//tao213//yolov5-master//ammophilaclose.pt")
cap = cv2.VideoCapture("C://Users//tao213//yolov5-master//Tests//AmmophilaCut.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Define region points
region_points = [(454, 326), (454, 630), (816, 630), (816, 306)]

# Video writer
video_writer = cv2.VideoWriter("object_counting_output_1.avi",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       fps,
                       (w, h))

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False)

    im0 = counter.start_counting(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

This produces the output:

```
0: 384x640 1 Ammophila, 1285.7ms
Speed: 5.0ms preprocess, 1285.7ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Ammophila, 813.6ms
Speed: 6.0ms preprocess, 813.6ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 669.2ms
Speed: 4.0ms preprocess, 669.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 723.7ms
Speed: 4.0ms preprocess, 723.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
```

I would like to edit this in order to output only the video frame ID and number of detections, as follows:

```
1 1
2 1
3 0
4 0
```

I am then writing it to a '.csv' file for analyses, hence this would avoid the need for reformatting.

Is this possible, or is there another way to customise the output?

**Comment by glenn-jocher** [comment]
@Toshea111 hey there! 👋

Absolutely, you can customize the output to show only the video frame ID and the number of detections. You'll need to modify the loop where you're processing each frame to count the detections and print or save the desired output format. Here's a quick example on how you could adjust your script:

```python
frame_id = 0  # Initialize frame counter
with open('detections.csv', 'w') as f:  # Open a file to write the output
    while cap.isOpened():
        success, im0 = cap.read()
        if not success:
            print("Video frame is empty or video processing has been successfully completed.")
            break
        tracks = model.track(im0, persist=True, show=False)
        
        # Count detections
        detections_count = len(tracks.boxes) if hasattr(tracks, 'boxes') else 0
        
        # Increment frame ID
        frame_id += 1
        
        # Print to terminal and write to file
        print(f"{frame_id} {detections_count}")
        f.write(f"{frame_id},{detections_count}\n")

        im0 = counter.start_counting(im0, tracks)
        video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

This script increments a `frame_id` for each frame processed, counts the number of detections using `len(tracks.boxes)`, and then prints and writes the frame ID and detection count to both the terminal and a CSV file named `detections.csv`. 

Hope this helps! Let us know if you have any more questions. 😊

**Comment by glenn-jocher** [comment]
@Toshea111 hey there! 😊

It looks like you're on the right track with your script modifications. If the detection count is not updating as expected, it might be due to how the `tracks` object is being accessed. Let's ensure we're correctly checking for detections.

Try modifying your detection count line like this:

```python
# Count detections
detections_count = len(tracks.boxes) if hasattr(tracks, 'boxes') and tracks.boxes is not None else 0
```

This ensures that we're not only checking if the `tracks` object has the `boxes` attribute but also that `tracks.boxes` is not `None` before attempting to count the detections.

If you're still facing issues, double-check that your model is correctly loaded and capable of detecting objects in your video frames. Sometimes, the issue might be with the input data or model performance rather than the script itself.

Keep me posted on your progress!

**Comment by Toshea111** [comment]
Hello @glenn-jocher,

I have managed to solve the issue by switching to `model.predict` and defining a `boxes` attribute.

The updated script is as follows:

```
from ultralytics import YOLO
import cv2
import csv

model = YOLO("C://Users//tao213//yolov5-master//ammophilaclose.pt")
cap = cv2.VideoCapture("C://Users//tao213//yolov5-master//Tests//AmmophilaCut.mp4")
assert cap.isOpened(), "Error reading video file"

count = 0
frame_id = 0
with open('detections1.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    header = ['Time (s)', 'Detections']
    writer.writerow(header)

    while cap.isOpened():
        success, im0 = cap.read()
        if success:
            count += 30
            cap.set(cv2.CAP_PROP_POS_FRAMES, count)
        results = model.predict(im0, iou = 0.2, show = True)
        for result in results:
            boxes = result.boxes
        
        detections_count = len(boxes)
        
        frame_id += 1
        
        print(f"{frame_id} {detections_count}")
        f.write(f"{frame_id},{detections_count}\n")

cap.release()
cv2.destroyAllWindows()
```
Do you know if it is possible to add an ROI, to ensure that only detections within its bounds are recorded?

**Comment by glenn-jocher** [comment]
@Toshea111 hey there! 👋

Awesome to hear you've made progress by switching to `model.predict`! 😊 Regarding your question about adding an ROI (Region of Interest) to consider only detections within certain bounds, yes, it's definitely achievable. You can filter the `boxes` to include only those within your ROI before counting them. Here's a slight modification to your script to illustrate:

```python
# Define your ROI [x_min, y_min, x_max, y_max]
roi = [x_min, y_min, x_max, y_max]

...

results = model.predict(im0, iou = 0.2, show = True)
for result in results:
    # Filter boxes to include only those within ROI
    boxes = [box for box in result.boxes if (roi[0] <= box.x1 <= roi[2]) and 
                                            (roi[1] <= box.y1 <= roi[3])]

detections_count = len(boxes)

...
```

Just replace `x_min, y_min, x_max, y_max` with the actual coordinates of your ROI. This script iterates through each detection, checking if its coordinates fall within the defined ROI, and counts only those that do.

Hope this helps! Let me know if you have any more questions.

**Comment by glenn-jocher** [comment]
Hey @Toshea111 👋,

Looks like there's a small fix needed for accessing the coordinates of the bounding boxes correctly. When working with the `Boxes` object from the `ultralytics` package, the bounding boxes are typically accessed through `.xyxy` format where each box in `result.boxes.xyxy` contains the coordinates `[x1, y1, x2, y2]`.

Here's a modified version of your script that correctly accesses these attributes:

```python
results = model.predict(im0, iou=0.2, show=True)
for result in results:
    if result.boxes is not None:
        # Convert bounding boxes to numpy array for easy manipulation
        boxes_np = result.boxes.xyxy[0].cpu().numpy()
        # Filter for boxes within the ROI
        boxes = [box for box in boxes_np if (roi[0] <= box[0] <= roi[2]) and 
                                            (roi[1] <= box[1] <= roi[3])]
    else:
        boxes = []
```

Make sure to adjust this as needed depending on your exact setup and package versions. This should resolve the `AttributeError` you were encountering. 😊

Let me know if this helps or if there are any more tweaks needed!

**Comment by Toshea111** [comment]
Hi @glenn-jocher,

I have modified the code as follows:

```
from ultralytics import YOLO
import cv2
import csv
import numpy

model = YOLO("C://Users//tao213//yolov5-master//ammophilaclose.pt")
cap = cv2.VideoCapture("C://Users//tao213//yolov5-master//Tests//AmmophilaCut.mp4")
assert cap.isOpened(), "Error reading video file"

count = 0
frame_id = 0
with open('detections1.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    header = ['Time (s)', 'Detections']
    writer.writerow(header)

    while cap.isOpened():
        success, im0 = cap.read()
        if success:
            count += 30
            cap.set(cv2.CAP_PROP_POS_FRAMES, count)
        results = model.predict(im0, iou=0.2, show=True)
        for result in results:
            if result.boxes is not None:
                boxes_np = result.boxes.xyxy[0].cpu().numpy()
                boxes = [box for box in boxes_np if (roi[0] <= box[0] <= roi[2]) and 
                                            (roi[1] <= box[1] <= roi[3])]
            else:
                boxes = []
        
        detections_count = len(boxes)
        
        frame_id += 1
        
        print(f"{frame_id} {detections_count}")
        f.write(f"{frame_id},{detections_count}\n")

cap.release()
cv2.destroyAllWindows()
```
It is now having issues finding the index, and thus producing the following error message:
```
Traceback (most recent call last):
  File "C:\Users\tao213\Miniconda3\DetectVisualiseROI.py", line 25, in <module>
    boxes_np = result.boxes.xyxy[0].cpu().numpy()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```
I have tried other indices, however the issue persists.

**Comment by glenn-jocher** [comment]
Hey @Toshea111 👋,

It looks like the error you're encountering is due to trying to access an index in an empty tensor. This can happen if no detections are found in the frames. To handle this, you should check if `result.boxes.xyxy` is not empty before trying to access its elements. Here’s a quick fix:

```python
for result in results:
    if result.boxes is not None and len(result.boxes.xyxy) > 0:
        boxes_np = result.boxes.xyxy[0].cpu().numpy()
        boxes = [box for box in boxes_np if (roi[0] <= box[0] <= roi[2]) and 
                                        (roi[1] <= box[1] <= roi[3])]
    else:
        boxes = []
```

This modification ensures that you only attempt to access `result.boxes.xyxy[0]` if there is at least one detection. This should resolve the `IndexError` you're seeing. Let me know if this helps or if you need further assistance! 😊

**Comment by Toshea111** [comment]
Hi @glenn-jocher,

Much appreciated, that edit has solved the issue in combination with an additional amendment, specifically changing `box[0]` and `box[1]` to `box`. I have also added a simple visualisation of the ROI, as this may be useful for confirming its coordinates in frame.

The revised script is as follows:
```
from ultralytics import YOLO
import cv2
import csv

model = YOLO("C://Users//tao213//yolov5-master//ammophilaclose.pt")
cap = cv2.VideoCapture("C://Users//tao213//yolov5-master//Tests//AmmophilaCut.mp4")
assert cap.isOpened(), "Error reading video file"
roi = [500, 200, 900, 700]

count = 0
frame_id = 0
with open('detections1.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    header = ['Time (s)', 'Detections']
    writer.writerow(header)

    while cap.isOpened():
        success, im0 = cap.read()
        if success:
            count += 30
            cap.set(cv2.CAP_PROP_POS_FRAMES, count)
            cv2.rectangle(im0, (500, 200), (900, 700), 
                                      (0, 0, 255), 5)

        results = model.predict(im0, iou = 0.2, show = True)

        for result in results:
            if result.boxes is not None and len(result.boxes.xyxy) > 0:
                boxes_np = result.boxes.xyxy[0].cpu().numpy()
                boxes = [box for box in boxes_np if (roi[0] <= box <= roi[2]) and 
                                                    (roi[1] <= box <= roi[3])]
            else:
                boxes = []
        
        detections_count = len(boxes)
        
        frame_id += 1
        
        print(f"{frame_id} {detections_count}")
        f.write(f"{frame_id},{detections_count}\n")

cap.release()
cv2.destroyAllWindows()
```
Thank you again, hopefully this will be useful to others with similar applications.

**Comment by glenn-jocher** [comment]
Hi @Toshea111,

Fantastic to hear that the modifications worked out well for you! 🎉 The addition of the ROI visualization is a great touch for practical applications, ensuring that the region is correctly set up. Thanks for sharing your updated script; it's definitely a helpful reference for others working on similar projects. If you have any more questions or need further assistance down the line, feel free to reach out. Happy coding! 😊
