### ISSUE TITLE
keep generating processes

### ISSUE THREAD

**Issue by zyy-xy** [ultralytics/ultralytics#8716]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hi! Excuse me,
I simply ran the sample code once and it produced a bunch of training result folders (as many as 16). As the code ran, I observed that it would keep spawning new processes until it ran out of memory, then crash and make pycharm flash back.
![image](https://github.com/ultralytics/ultralytics/assets/51401952/471fc3a0-d65b-4637-954d-87fd36265977)

### Environment

Ultralytics YOLOv8.1.24 🚀 Python-3.11.7 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)
Setup complete ✅ (8 CPUs, 7.9 GB RAM, 86.4/223.6 GB disk)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-pose.yaml')  # build a new model from YAML

# Train the model
results = model.train(data='coco8-pose.yaml', epochs=100, imgsz=640)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zyy-xy** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/51401952/6faf9948-5e62-4ebc-8a93-adc27189f06e)

**Comment by zyy-xy** [comment]
In addition, setting `workers=1, batch=1` was useless. 

I found that every time the function `InfiniteDataLoader()` run, a new thread was enabled and started running from the outermost code `results = model.train(data='coco8-pose.yaml', epochs=100, imgsz=640)`. Looped forever like this until it run out of memory.

**Comment by glenn-jocher** [comment]
@zyy-xy hello! Thank you for bringing this to our attention. It seems like you're encountering an issue where the training process is spawning an excessive number of processes, leading to memory exhaustion. This is certainly not the expected behavior, and we appreciate your detailed report.

The behavior you're observing with `InfiniteDataLoader()` continuously spawning new threads is unusual. Typically, setting `workers=1` should limit the number of subprocesses spawned for data loading, preventing the issue you're experiencing.

As a temporary workaround, you might want to try manually specifying the number of workers in your training script to see if it helps manage the number of processes being created:

```python
results = model.train(data='coco8-pose.yaml', epochs=100, imgsz=640, workers=0)
```

Setting `workers=0` forces the data loading to happen in the main process, which might help avoid the spawning of additional processes.

We'll investigate this issue further to understand the root cause and work on a fix. Your feedback is invaluable in helping us improve YOLOv8. Please stay tuned for updates on this issue in the repository. If you have any more insights or further questions, feel free to share. 🚀

**Comment by zyy-xy** [comment]
Thanks a lot! Setting `workers=0` helps! The problem was solved for the time being.

**Comment by zyy-xy** [comment]
> @zyy-xy hello! Thank you for bringing this to our attention. It seems like you're encountering an issue where the training process is spawning an excessive number of processes, leading to memory exhaustion. This is certainly not the expected behavior, and we appreciate your detailed report.
> 
> The behavior you're observing with `InfiniteDataLoader()` continuously spawning new threads is unusual. Typically, setting `workers=1` should limit the number of subprocesses spawned for data loading, preventing the issue you're experiencing.
> 
> As a temporary workaround, you might want to try manually specifying the number of workers in your training script to see if it helps manage the number of processes being created:
> 
> ```python
> results = model.train(data='coco8-pose.yaml', epochs=100, imgsz=640, workers=0)
> ```
> 
> Setting `workers=0` forces the data loading to happen in the main process, which might help avoid the spawning of additional processes.
> 
> We'll investigate this issue further to understand the root cause and work on a fix. Your feedback is invaluable in helping us improve YOLOv8. Please stay tuned for updates on this issue in the repository. If you have any more insights or further questions, feel free to share. 🚀

Hi! @glenn-jocher Thanks a lot! Setting `workers=0` helps! The problem was solved for the time being.

**Comment by glenn-jocher** [comment]
Hi @zyy-xy! That's great to hear! 🎉 I'm glad the workaround with `workers=0` resolved the issue for now. We're actively working on a more permanent fix and will keep you updated. Your contribution to improving YOLOv8 is truly appreciated. If anything else comes up or you have further insights, don't hesitate to reach out. Happy coding!

**Comment by glenn-jocher** [comment]
@zyy-xy We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by popy2k14** [comment]
~~Issue still exists for me on windows.~~
~~workers=0 temporarily fixed it.~~

~~@glenn-jocher Are there plans for a proper fix?~~

Found out thats per design.
workers=8 means (~8 worker threads, 16 val threads and 1x main thread).

**Comment by glenn-jocher** [comment]
Yes, that sounds consistent with expected train/val dataloader worker behavior rather than `InfiniteDataLoader()` recursively spawning itself; if you still see unbounded process growth on a current install, please open a new issue for visibility and include `yolo checks` or `ultralytics.utils.checks.collect_system_info()`, the full traceback, and a small repro following our [bug reporting guide](https://docs.ultralytics.com/help/contributing/).
