### ISSUE TITLE
Training parameter "val" has no effect

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#890]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation

### Bug

According to the [YOLOv8 docs](https://docs.ultralytics.com/cfg/#training) there is a training parameter `val` used to (de-)activate "validate/test during training".
I tried that in my test like so:

```python
model = YOLO("yolov8m.pt")
model.train(
    data=config_file,
    verbose=True,
    val=False,
)
```

That works fine, however, after training there still seems to be a final validation step based on the `best.pt` model:

```text
Validating training/ski-defects-sample/weights/best.pt...
Ultralytics YOLOv8.0.32 🚀 Python-3.10.6 torch-1.13.0+cu116 CUDA:0 (NVIDIA GeForce RTX 2070 with Max-Q Design, 7982MiB)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.33s/it]
                   all         25         64      0.123     0.0781     0.0357     0.0276
Speed: 0.1ms pre-process, 9.0ms inference, 0.0ms loss, 0.7ms post-process per image
Results saved to training/ski-defects-sample
```

Since I set `val=False` in my call to `train()`, as shown above, I would expect that last validation step not to happen.
Is this a bug, and if not, how else can I then deactivate that final validation step after training?

### Environment

- Ultralytics YOLOv8.0.32 🚀 Python-3.10.6 torch-1.13.0+cu116 CUDA:0
- Ubuntu 22.04
- Python 3.10

### Minimal Reproducible Example

```python
model = YOLO("yolov8m.pt")
model.train(
    data=config_file,
    verbose=True,
    val=False,
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
The last val is run independently after training is finished. The val=False was intended for "turning off validation during training". But I agree that this might be confusing to some users. Can you also provide your use-case for turning off validation completely?

**Comment by haimat** [comment]
@AyushExel This came up because of another issue - I wanted to retrieve the metrics from the final validation step (using the best.pt model) in my Python code. However, the `train()` function does not return these metrics, so I need to call `val()` explicitly again after training. Thus I thought I could omit that auto-validation, since I need to call it manually again anyway.

The ideal solution would be if the call to `train()` would return the metrics of the training and that last validation automatically.

**Comment by Laughing-q** [comment]
@haimat hi, @AyushExel has made a PR to support this, now you're able to access the metrics by the following script:
```python
model.train()
metrics = model.metrics
metrics.box.map    # map50-95
metrics.box.map50  # map50
metrics.box.map75  # map75
metrics.box.maps   # a list contains map50-95 of each category
metrics.box.mp  # precision
metrics.box.mr  # recall
```

**Comment by haimat** [comment]
@Laughing-q @AyushExel Thanks, but now with this change I get the following error from the `train()` call:

```python
 Traceback (most recent call last):
  File "/__w/head/head/src/dvc/yolov8-trainer.py", line 86, in <module>
    main()
  File "/__w/head/head/src/dvc/yolov8-trainer.py", line 36, in main
    model.train(
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 243, in train
    self.metrics_data = self.trainer.validator.metrics
AttributeError: 'NoneType' object has no attribute 'metrics'
```

I am using your `ultralytics/ultralytics:latest` Docker container.
Any ideas why this doesn't work any more?

**Comment by AyushExel** [comment]
That's strange. Our test here passed on the main branch 
https://github.com/ultralytics/ultralytics/blob/main/tests/test_python.py#L81

**Comment by haimat** [comment]
It's strange indeed, because locally on my dev machine this works. But in the `ultralytics` Docker container, even after running a `git -C /usr/src/ultralytics pull`, the call to `train()` leads to this error above. It seems the `self.train.validator` object is `None`. Any ideas what could be different when using your Docker container?

**Comment by AyushExel** [comment]
yeah that sounds right! I'll see whats up tomorrow

**Comment by haimat** [comment]
@AyushExel So I just checked within your `ultralytics` Docker image - the new line `self.metrics_data = self.trainer.validator.metrics` is there in the `train()` method as it should be. According to the stack trace above the problem is that the `validator` is object is None. I am wondering how this could happen - when I train a model then I can see the validation output after training, so I don't see why `validator` is None after training ...

**Comment by AyushExel** [comment]
Yes the main branch should work now

**Comment by haimat** [comment]
@AyushExel Great, thanks. So does this work for multi-GPU training as well, or would I not have access to these metrics then?

**Comment by AyushExel** [comment]
@haimat yes it should work with ddp mode as well. Let me know if you face any issues

**Comment by AyushExel** [comment]
@haimat yes it should work with ddp mode as well. Let me know if you face any issues

**Comment by haimat** [comment]
@AyushExel Unfortunately no, the issue is still the same, even with **Ultralytics YOLOv8.0.37**:

```python
 Traceback (most recent call last):
  File "/__w/head/head/src/dvc/yolov8-trainer.py", line 86, in <module>
    main()
  File "/__w/head/head/src/dvc/yolov8-trainer.py", line 36, in main
    model.train(
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 243, in train
    self.metrics_data = self.trainer.validator.metrics
AttributeError: 'NoneType' object has no attribute 'metrics'
```

**Comment by haimat** [comment]
@AyushExel Update: Running `train()` using only one GPU (but with the same Docker image on the same machine) does work. So it has something to do with multi-GPU training as it seems.

**Comment by AyushExel** [comment]
Hmm 🤔 okay I'll need to debug this in DDP mode then. I'll back to you

**Comment by glenn-jocher** [comment]
@haimat thanks for letting us know, I'll take a look. A patch fix would be to revert to 8.0.33. I checked our in-progress DDP trainings and they are running correctly in Docker using this version.

**Comment by glenn-jocher** [comment]
@AyushExel ok I'm able to reproduce this, but it's a little hard to debug since I can only SSH into our server. 

The two quick fixes are to revert the model metrics PR, since @Laughing-q was saying it may be edge case usage, or to return None to self.metrics if the validator object is None. This would fix the error but not resolve the underlying issue. What do you think?

**Comment by AyushExel** [comment]
@glenn-jocher yeah that seems like the only approach we have left. 
EDIT:
I think this might work but if not then let's just revert it..
```
def train():
     ...
     # after training outside the if RANK in [-1, 0] condition

  if self.trainer.validator:
       self.metrics_data = self.trainer.validator.metrics
```

**Comment by glenn-jocher** [comment]
@AyushExel I tried to update this line in but now getting a new error:
https://github.com/ultralytics/ultralytics/pull/972/commits/d46d82867ad6cf06e281d7c91c27154dffc6c15d

`AttributeError: 'DetectionTrainer' object has no attribute 'metrics'
`

**Comment by glenn-jocher** [comment]
@haimat @AyushExel ok I know what's going on here. I've patched the error by simply initializing the metrics attribute in the trainer in , but this will not allow return arguments from a DDP training since DDP trainings operate using an independent subprocess call that allows us to hack the torch.distributed.run command in python (same as lightning uses). 

https://github.com/ultralytics/ultralytics/pull/972/commits/fb1ceef00e26a750495bfa7a6307c4f5deda7570

<img width="725" alt="Screenshot 2023-02-14 at 19 21 34" src="https://user-images.githubusercontent.com/26833433/218781187-baa18da9-ad33-4581-ad29-442769304c1f.png">

**Comment by AyushExel** [comment]
> @AyushExel I tried to update this line in but now getting a new error: [d46d828](https://github.com/ultralytics/ultralytics/commit/d46d82867ad6cf06e281d7c91c27154dffc6c15d)
> 
> `AttributeError: 'DetectionTrainer' object has no attribute 'metrics' `

I tried this it's working on mac so its ddp specific problem

**Comment by AyushExel** [comment]
@glenn-jocher this won't be a complete solution as trainer.metrics is raw dict but validator.metrics is a Python object wrapper around the dict. So we also need to return validator.metrics.results_dict
 
set `self.metrics_data = validator.metrics.results_dict` in line 190 of model.py

**Comment by glenn-jocher** [comment]
@AyushExel ok I'll update and test

**Comment by glenn-jocher** [comment]
@AyushExel ok I've updated to retain non-dict metrics and return None in case of DDP:

```
            self.metrics_data = getattr(self.trainer.validator, 'metrics', None)  # TODO: no metrics returned by DDP
```

Can you check if this works locally for you?

**Comment by AyushExel** [comment]
@glenn-jocher works on mac m1

**Comment by glenn-jocher** [comment]
@haimat ok I think this is the best we can do right now as https://github.com/ultralytics/ultralytics/issues/890#issuecomment-1429925034 shows structural issues with returning metrics from DDP trainings.

You can always independently validate a DDP-trained model afterwards and then retrieve metrics that way, i.e.:


```
trained_model = YOLO('path/to/best.pt')
metrics = trained_model.val(data=...)
```

**Comment by haimat** [comment]
Thanks for your update, I will manually validate the model then.
When will you push the release to main?

**Comment by glenn-jocher** [comment]
@haimat pushed to `main` now.

**Comment by haimat** [comment]
Thanks, this issue is solved now.
However, [Multi-GPU training seems to be broken at the moment](https://github.com/ultralytics/ultralytics/issues/978).
Could you please advice?

**Comment by pderrenger** [comment]
@haimat I saw the multi-GPU training issue and added my thoughts there. Let's continue the discussion in the existing thread to avoid fragmentation.

**Comment by glenn-jocher** [comment]
@pderrenger Thank you for bringing this to our attention. I've responded in the multi-GPU training issue thread. Let's keep the conversation there to maintain clarity and focus on resolving the issue. 🛠️
