### ISSUE TITLE
tflite has problem in the bounding boxes

### ISSUE THREAD

**Issue by WikiGenius** [ultralytics/ultralytics#992]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Tflite has a problem with the bounding boxes.
I think the problem in the normalization of the bounding boxes.

Also, the prediction time is slower than tflite v7 and v6, however, the PyTorch v8 is very fast. I think the tflite is not optimised yet.
The second problem is the command line is still under development.

Thanks so much.

![image](https://user-images.githubusercontent.com/33193541/219142289-3677c4c7-4659-49be-9eb4-29f334034cd4.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@WikiGenius seems like user error. I can export and get correct results and identical mAP and fast inference.

![image](https://user-images.githubusercontent.com/26833433/219438437-bff57224-f153-41c6-8dd1-a53f82442d24.png)


<img width="1601" alt="Screenshot 2023-02-16 at 18 11 40" src="https://user-images.githubusercontent.com/26833433/219438422-c1b5a157-bc97-41ac-938b-6d64675180ab.png">

**Comment by glenn-jocher** [comment]
TFLite inference speed of 69ms on an M2 Macbook Air

**Comment by WikiGenius** [comment]
Hi @glenn-jocher 
I am not sure why this but the problem could because of the versions of libraries.
Could you please mention the requirements.txt?
I will try to upgrade the version of python from version 8 to 10 maybe it will solve the problem.

this is the output of mine

Ultralytics YOLOv8.0.39 🚀 Python-3.8.10 torch-1.13.1+cpu CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
WARNING ⚠️ YOLOv8 TensorFlow export support is still under development. Please consider contributing to the effort if you have TF expertise. Thank you!

TensorFlow SavedModel: starting export with tensorflow 2.11.0...

ONNX: starting export with onnx 1.13.0...
ONNX: export success ✅ 0.9s, saved as yolov8n.onnx (12.2 MB)
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: name 'ort' is not defined
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 279, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 357, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 48, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/onnx2tf/ops/Sub.py", line 172, in make_node
    tf.math.subtract(
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics/yolov8_env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.math.subtract" (type TFOpLambda).

Dimensions must be equal, but are 8400 and 2 for '{{node tf.math.subtract/Sub}} = Sub[T=DT_FLOAT](tf.math.subtract/Sub/x, Placeholder)' with input shapes: [1,8400,2], [1,2,8400].

Call arguments received by layer "tf.math.subtract" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 8400, 2), dtype=float32)
  • y=tf.Tensor(shape=(1, 2, 8400), dtype=float32)
  • name='/model.22/Sub'
ERROR: input_onnx_file_path: yolov8n.onnx
ERROR: onnx_op_name: /model.22/Sub
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
TensorFlow SavedModel: export failure ❌ 8.8s: SavedModel file does not exist at: yolov8n_saved_model/{saved_model.pbtxt|saved_model.pb}
  main ?:4  ❲p❳ yolov8_env  ~/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/ultralytics 

**Comment by glenn-jocher** [comment]
@WikiGenius hey I discovered a clue here! 

I saw that newly added CI in also shows incorrect TFLite boxes, and I was able to reproduce this in colab using code below, but locally on macOS I'm seeing correct results.

```bash
yolo export format=tflite
yolo task=detect mode=predict model=yolov8n_saved_model/yolov8n_float16.tflite imgsz=640
```

It's very strange, maybe related to dependency versions or perhaps any `if` statements that depend on platform, i.e. `if MACOS` maybe.

**Comment by glenn-jocher** [comment]
@WikiGenius in Colab everything exports correctly with https://github.com/ultralytics/ultralytics/pull/1014 (after restarting environment), but inference is incorrect as in your original message.

<img width="980" alt="Screenshot 2023-02-16 at 22 25 22" src="https://user-images.githubusercontent.com/26833433/219490297-aa19285a-403d-4b3d-9530-58723df120e4.png">

**Comment by glenn-jocher** [comment]
@WikiGenius I attempted to remove the scaling here, but this seems to have had no effect on the bug.
https://github.com/ultralytics/ultralytics/pull/1014/commits/c860cf111dac3ce2cccd325d395c8a141cf6d2f9

I also see the same problem with pb exports, not just tflite exports, so the problem seems to not be related to tflite specifically:
```
yolo export format=pb
```

Let me know if you discover anything, I'm at a loss.

**Comment by WikiGenius** [comment]
I want to check this clue. @glenn-jocher 
I think you're right.

I used python10 and I have the same error.
Depends on the version of libraries the the script will success or not in the exporting.

Could you send me screenshot of the tflite you have regarding the inputs and the output?

**Comment by WikiGenius** [comment]
![image](https://user-images.githubusercontent.com/33193541/219856751-21fdf2d0-8401-4ba3-b081-ebd6c6f1d675.png)

![image](https://user-images.githubusercontent.com/33193541/219856769-2d88073b-df5f-4fd9-993c-eb4ab6baf18d.png)

**Comment by glenn-jocher** [comment]
@WikiGenius ok I've had the chance to debug this a lot. I think this is a bug in `onnx2tf` package or one of its dependencies, because I can export correctly on my MacBook with Python 3.10, but all CI runners and Google Colab export incorrectly.

I was able to discover differences in the Netron models that seem centered around the boxes permute/transpose ops that were different. 

I captured the export logs for both and they show significant differences towards the end (you can diff these two files). I don't have a good solution other than to raise the issue on `onnx2tf` repo.

[output_colab.log](https://github.com/ultralytics/ultralytics/files/10783165/output_colab.log)
[output_local_good.log](https://github.com/ultralytics/ultralytics/files/10783167/output_local_good.log)

**Comment by glenn-jocher** [comment]
@zldrobit hey we could use some advice here. We've implemented new TF exports in YOLOv8 based on https://github.com/PINTO0309/onnx2tf, i.e.:

```
yolo export model=yolov8n.pt format=tflite
```

The main idea was to use `onnx2tf` to avoid the transpose ops caused by [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow), but it appears to be behaving differently in different environments. 

I get correct results with tensorflow-macos locally on my Macbook, but all other environments (Docker, Colab, Github CI action runners) are showing the bounding box issues raised by OP here. 

The alternative to `onnx2tf` would be to start building TF modules and models in this repo also just like in YOLOv5, but I'd hoped to avoid this since it requires more future maintenance, and also because users may run into problems exporting their custom models to TF. What do you think is the best approach here? Thanks!

@sergiossm @AyushExel @Laughing-q

**Comment by glenn-jocher** [comment]
@WikiGenius @sergiossm all TF Saved Model, Protobuf and TFLite modes are now exporting and predicting correctly with ultralytics 8.0.46 via PR https://github.com/ultralytics/ultralytics/pull/1141 as verified in our latest CI benchmarks below. Please update your package with `pip install -U ultralytics` and let us know if this resolves your issue and if you have any other problems. Thank you! 
https://github.com/ultralytics/ultralytics/actions/runs/4271012395/jobs/7435190444

<img width="1139" alt="Screenshot 2023-02-25 at 09 22 15" src="https://user-images.githubusercontent.com/26833433/221370745-43697ce1-0792-43d3-b87b-d4a5fb434eb9.png">

**Comment by WikiGenius** [comment]
Thanks, @glenn-jocher  
/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/test_yolov8/runs/detect/predict4/3.png
I didn't test the speed yet but the results are great

**Comment by glenn-jocher** [comment]
@WikiGenius awesome!!

**Comment by razacode** [comment]
Hi @glenn-jocher 

Please have a look into attached screenshot. I following the same procedure that you mentioned above and still getting errors. The code that I am using to do detection is as from the link: https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-ONNXRuntime/main.py

I have updated for tflite the code and I am commented line:
`image_data = np.transpose(image_data, (2, 0, 1))  # Channel first`

As it was giving error `ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 640 for dimension 1 of input 0.`

Looking forward 

![output](https://github.com/ultralytics/ultralytics/assets/22597483/fb54ae56-9e50-482b-8e56-8d3e545a3cdb)

**Comment by glenn-jocher** [comment]
@razacode hi, 

Thanks for reaching out. Based on the info provided, it seems there are mismatches in your image dimensions when trying to run the model. This error typically happens when the model expects a different input size than it's receiving.

In the YOLOv8 model, the image input is expected to be in the format (batch, channels, height, width). When using numpy's transpose function in image preprocessing, it's critical to ensure the dimensions match what the model is expecting. 

In your case, commenting out the transpose line might have resulted in the tensor being prepared in an incompatible format for the model, hence the error.

As a general advice, ensure you're using the correct data pipeline for preparing images and also ensure your YOLOv8 version is up-to-date.

For the performance chart attached, if you're experiencing slower times than expected, this might be due to many factors like hardware environment, model complexity, image resolution etc. Please make sure you're testing the model under optimal conditions, and remember that results can vary due to unforeseen circumstances.

Let me know if this helps and if there are other issues you're encountering.

**Comment by razacode** [comment]
Hi @glenn-jocher 

thank you for your reply.

Yes, agree i have make the transpose as below:
`[{'name': 'inputs_0', 'index': 0, 'shape': array([  1, 640, 640,   3]), 'shape_signature': array([  1, 640, 640,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 
0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 408, 'shape': array([   1,   84, 8400]), 'shape_signature': array([   1,   84, 8400]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
before (640, 640, 3)
AFTER (3, 640, 640)
(1, 3, 640, 640)`

The image input is now in expected format (1, 3, 640, 640) (batch, channels, height, width) now its working thanks for the support in this case

**Comment by glenn-jocher** [comment]
@razacode hello, 

I'm glad to hear that the issue has been resolved! By adjusting the array format to fit the model's expected input, you're allowing the model to process the data correctly. It's crucial to ensure that data is presented in the correct format (batch, channels, height, width) when dealing with high-dimensional arrays.

If you have any other questions or experience any more issues, feel free to ask. I'm here to help. Happy testing with YOLOv8!

**Comment by sachinlodhi** [comment]
there is still some problem.
I trained the model on colab and it was working fine on colab and on local machine but when I exported model in tflite format:
`python
from ultralytics import YOLO

# Load a model
# model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('/content/latest-custom-weights.pt')  # load a custom trained model

# Export the model
results = model.export(format='tflite')
`
It gave me following output:
`shell
Ultralytics YOLOv8.0.228 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
Model summary (fused): 168 layers, 3006038 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from '/content/latest-custom-weights.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 6, 8400) (6.0 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 1.9s, saved as '/content/latest-custom-weights.onnx' (11.6 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/latest-custom-weights.onnx" -o "/content/latest-custom-weights_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export success ✅ 16.0s, saved as '/content/latest-custom-weights_saved_model' (29.2 MB)

TensorFlow Lite: starting export with tensorflow 2.13.1...
TensorFlow Lite: export success ✅ 0.0s, saved as '/content/latest-custom-weights_saved_model/latest-custom-weights_float32.tflite' (11.6 MB)

Export complete (18.2s)
Results saved to /content
Predict:         yolo predict task=detect model=/content/latest-custom-weights_saved_model/latest-custom-weights_float32.tflite imgsz=640  
Validate:        yolo val task=detect model=/content/latest-custom-weights_saved_model/latest-custom-weights_float32.tflite imgsz=640 data=/content/knock-1/data.yaml  
Visualize:       https://netron.app/
`
now when I am using the same model for inference using following code:

`python
import numpy as np
import tensorflow as tf
import numpy as np
import cv2

#loading the model
interpreter = tf.lite.Interpreter(model_path="/content/best_float32.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
print(output_details)
`
`shell
[{'name': 'inputs_0', 'index': 0, 'shape': array([  1, 640, 640,   3], dtype=int32), 'shape_signature': array([  1, 640, 640,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 410, 'shape': array([   1,    6, 8400], dtype=int32), 'shape_signature': array([   1,    6, 8400], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
`
`python
# reading the image
image_path = '/content/frame_147.jpg'
image = cv2.imread(image_path)

# preprocessing image
input_image = cv2.resize(image, (640, 640))
input_data = np.array(input_image, dtype=np.float32)
input_data = np.expand_dims(input_data, axis=0)

# loading the data  
interpreter.set_tensor(input_details[0]['index'], input_data)
print(input_data.shape)
`
`shell
(1, 640, 640, 3)
`
`python
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
output_data.shape
`
`shell
(1, 6, 8400)
`
`python
reshaped_data = output_data.reshape(-1,6) # reshaping for iterating over all 8400 bboxes
`
now while I print first 5 rows from reshaped_data I get following output:
`shell
array([[0.00711319, 0.02504703, 0.03850756, 0.04507966, 0.07061896,
        0.06649399],
       [0.10250838, 0.09819403, 0.10642369, 0.11928182, 0.14746201,
        0.16413842],
       [0.17609067, 0.17584792, 0.1922584 , 0.18747139, 0.2186969 ,
        0.23277603],
       [0.244198  , 0.25878277, 0.26863518, 0.29733443, 0.29362723,
        0.3093121 ],
       [0.3317944 , 0.33196616, 0.3377972 , 0.3552277 , 0.37280715,
        0.3810348 ]], dtype=float32)
`
I get it that first 4 values are x_center,y_center, height, width and remaining two are confidence and class_score.

I want to know that how do I transform these values so I can use them to draw bounding box? Moreover I have tried multiplying the first 4 values by **640** but it doesn't show the correct bounding boxes. ANy help is appreciated.

**Comment by glenn-jocher** [comment]
@sachinlodhi hi,

It looks like you've successfully exported your custom model to TFLite and are able to perform inference, but need help interpreting the outputs to draw bounding boxes.

The bounding box data from the model's output indeed consists of center x, center y, width, height, confidence, and class probabilities. However, simply multiplying these values by the input size (640) may not be sufficient because:

- The output values may need to be scaled appropriately if your model outputs are in a normalized form (e.g., 0 to 1 range for the entire image dimension).
- X and Y centers must be translated into top-left corner coordinates.

For drawing bounding boxes, you would generally perform these steps:

1. Convert the center x, and center y values to the top-left corner of the bounding box.
2. Multiply these top-left values and the width and height by the input size (or the original image size if different) to scale them correctly.
3. Make sure to also apply a threshold to the confidence scores to filter out low-probability detections.

This logic is encapsulated in the Ultralytics inference pipeline when you use the CLI or the provided Python scripts. For a custom inference script in Python, these steps need to be manually reproduced.

It seems there might be some misunderstanding in this process or perhaps even a deeper issue with the way the TFLite outputs are being handled. It could also be potentially due to different preprocessing or postprocessing steps used in different environments.

Without the exact script or further inspection of the predictions, it's challenging to diagnose the root cause of the incorrect bounding box coordinates.

Please ensure that you are following the model's expected preprocessing and postprocessing steps accurately. If you continue to face issues, you may want to review the postprocessing part of the provided YOLOv8 scripts closely to compare with your own script.

**Comment by sachinlodhi** [comment]
```python
for detection in reshaped_data:
    # if detection[4] > 0.9:
        x_center, y_center, width, height = 640 * detection[:4]

        # Convert center coordinates to top-left corner
        x_top_left = int(x_center - (width / 2))
        y_top_left = int(y_center - (height / 2))

        # Convert size to bottom-right corner
        x_bottom_right = int(x_center + (width / 2))
        y_bottom_right = int(y_center + (height / 2))

        # Draw the bounding box on the image
        cv2.rectangle(input_image, (x_top_left, y_top_left), (x_bottom_right, y_bottom_right), (0, 255, 0), 1)
```

Here is the code that I used. Still it is giving wrong result as shown below:
![image](https://github.com/ultralytics/ultralytics/assets/28351261/58154f11-be57-4cca-8958-2d8fe0630ef6)

But when I use CLI the results and perfect.

**Comment by glenn-jocher** [comment]
@sachinlodhi 

The code snippet appears largely correct for transforming the model's output into bounding box coordinates. If results differ between the CLI and your script, there could be a discrepancy in pre- or post-processing steps.

Key areas to check are:
- Preprocessing alignment (Resize, Padding, Normalization schemes)
- Confidence threshold used for bounding box acceptance
- Postprocessing methods to interpret model outputs (e.g., non-maximum suppression)

Please carefully review your pipeline to ensure the input data and the way detections are handled are consistent with the CLI approach.

If the model is running correctly via CLI, reviewing the source code for CLI inference should provide insights into the expected processing steps. It's also advisable to ensure consistency in versions and environments when comparing results between Colab and the CLI.

**Comment by sachinlodhi** [comment]
can you please provide the source code for the CLI implementation so I can check that out? I know that the pre-processing steps are right as the required dimension in the first layer match with the result of pre-processing i.e. (1,640,640,3).  Any lead about  the post processing?
Thank you.

**Comment by glenn-jocher** [comment]
@sachinlodhi certainly! The source code for the CLI implementation can be found within the repository, specifically in the inference script that's used for the `predict` mode. Regarding post-processing, one critical step is non-maximum suppression, which filters out overlapping bounding boxes and selects the most likely prediction. This process typically includes applying a confidence threshold and an intersection over union (IoU) threshold to refine the bounding boxes after decoding.

Please refer to the documentation details or directly inspect the prediction and post-processing sections in the script for further insights. The logic therein governs how raw model outputs are translated into final bounding boxes and could serve as a guide for aligning your custom implementation.

**Comment by sachinlodhi** [comment]
> Thanks, @glenn-jocher ![3](https://user-images.githubusercontent.com/33193541/221375507-655acfe4-0271-4230-8c44-3615b2c3b9ef.png)
> 
> I didn't test the speed yet but the results are great
> 
> This is on ubuntu20 my local device

did you use the CLI mode or the tflite interpreter mode? Can you please let us know?

**Comment by sachinlodhi** [comment]
> @sachinlodhi certainly! The source code for the CLI implementation can be found within the repository, specifically in the inference script that's used for the `predict` mode. Regarding post-processing, one critical step is non-maximum suppression, which filters out overlapping bounding boxes and selects the most likely prediction. This process typically includes applying a confidence threshold and an intersection over union (IoU) threshold to refine the bounding boxes after decoding.
> 
> Please refer to the documentation details or directly inspect the prediction and post-processing sections in the script for further insights. The logic therein governs how raw model outputs are translated into final bounding boxes and could serve as a guide for aligning your custom implementation.

okay so If I am seeing the model.predict() then I need to explore this:
[ultralytics](https://github.com/ultralytics/ultralytics/tree/main)/[ultralytics](https://github.com/ultralytics/ultralytics/tree/main/ultralytics)/[engine](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/engine)
/predictor.py Right?

**Comment by glenn-jocher** [comment]
@sachinlodhi yes, that's correct. The `predictor.py` script within the `engine` directory contains the logic for the `model.predict()` method, including the necessary pre- and post-processing steps. Reviewing this script should provide clarity on how to properly handle the model outputs for drawing bounding boxes.

**Comment by PriyamDalwadii** [comment]
@sachinlodhi   @glenn-jocher  If you got your output as desired can you please assist me as I am having same problem with multiple bounding boxes  after prediction. My model takes input 320x320 and tflite model output shape is 1x6300x6. 

![output_with_boxes](https://github.com/ultralytics/ultralytics/assets/108300073/c710ef48-b0de-4e6b-9710-05aef9ffa908)

**Comment by sachinlodhi** [comment]
> @sachinlodhi @glenn-jocher If you got your output as desired can you please assist me as I am having same problem with multiple bounding boxes after prediction. My model takes input 320x320 and tflite model output shape is 1x6300x6.
> 
> ![output_with_boxes](https://private-user-images.githubusercontent.com/108300073/294979115-c710ef48-b0de-4e6b-9710-05aef9ffa908.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzU0ODUsIm5iZiI6MTcwNDczNTE4NSwicGF0aCI6Ii8xMDgzMDAwNzMvMjk0OTc5MTE1LWM3MTBlZjQ4LWIwZGUtNGU2Yi05NzEwLTA1YWVmOWZmYTkwOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNzMzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDc3YWU2N2JhZjUzMmQ0MTY4ODdhNTkxNWNjZDM0YzUwMTMyZGJjZWFiNTFjYmI5YmIzMDM3NDhjMmRkNTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P_1gt8m2vRK3wrglpII4a8zSo5hwKQqZ1ZOTcb9FSPY)

No @PriyamDalwadii No success yet. I was trying to use various configurations but as of now nothing worked in my case. I successfully got the output tensor and was trying to draw bounding box but no luck yet. I was trying to backtrack in yolo official implementation but no luck as it is very convoluted.

**Comment by wamiqraza** [comment]
I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.

https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime
https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python

**Comment by PriyamDalwadii** [comment]
> I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> 
> https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python

Thanks! It worked.

**Comment by sachinlodhi** [comment]
> > I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> > https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python
> 
> Thanks! It worked.

Hey congratulations!!! So you trained model from scratch or you are using pre-trained model?

**Comment by PriyamDalwadii** [comment]
> > > I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> > > https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python
> > 
> > 
> > Thanks! It worked.
> 
> Hey congratulations!!! So you trained model from scratch or you are using pre-trained model?
I have trained a custom yolov5 model and exported it to tflite. Using CLI ,results were perfect, only problem I was facing was while using tflite interpreter.

**Comment by sachinlodhi** [comment]
> > > > I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> > > > https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python
> > > 
> > > 
> > > Thanks! It worked.
> > 
> > 
> > Hey congratulations!!! So you trained model from scratch or you are using pre-trained model?
> > I have trained a custom yolov5 model and exported it to tflite. Using CLI ,results were perfect, only problem I was facing was while using tflite interpreter.

YEs same with me. I am retraining the model for two classes, exported it and it is working fine with "yolo detect command" in CLI but it is not working with the tflite interpreter. I tried the links he shared too but not luck still.... If possible can we discuss your implementation in details? Can we connect over discord or something? I really need to finish this task.

**Comment by wamiqraza** [comment]
> > > > I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> > > > https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python
> > > 
> > > 
> > > Thanks! It worked.
> > 
> > 
> > Hey congratulations!!! So you trained model from scratch or you are using pre-trained model?
> > I have trained a custom yolov5 model and exported it to tflite. Using CLI ,results were perfect, only problem I was facing was while using tflite interpreter.

@PriyamDalwadii 

> > I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> > https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python
> 
> Thanks! It worked.

@PriyamDalwadii, glad to hear that it work. You can follow me for more updates

**Comment by wamiqraza** [comment]
> > > > > I think @sachinlodhi and @PriyamDalwadii, you need to check the transpose part and have a look if image has expected format. I will refer you to below my branches which I worked recently hopefully it will solve the issue you are facing.
> > > > > https://github.com/wamiqraza/ultralytics/tree/yolovv8_tflite/examples/YOLOv8-OpenCV-tflite-Runtime https://github.com/wamiqraza/ultralytics/tree/yolov8-int8-tflite/examples/YOLOv8-OpenCV-int8-tflite-Python
> > > > 
> > > > 
> > > > Thanks! It worked.
> > > 
> > > 
> > > Hey congratulations!!! So you trained model from scratch or you are using pre-trained model?
> > > I have trained a custom yolov5 model and exported it to tflite. Using CLI ,results were perfect, only problem I was facing was while using tflite interpreter.
> 
> YEs same with me. I see you trained yolov5 an not yolov8 I am retraining the model for two classes, exported it and it is working fine with "yolo detect command" in CLI but it is not working with the tflite interpreter. I tried the links he shared too but not luck still.... If possible can we discuss your implementation in details? Can we connect over discord or something? I really need to finish this task.

Hi @sachinlodhi, still after referring into those resources you have issue feel free to follow and write me on LinkedIn. We can discuss there
